{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/thfssynapsedev sql azuresynapse net;dwhdev",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "thfcsynapsewsprod.sql.azuresynapse.net",
            "database": "dwhprd"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "kind": "SQL",
          "path": "thfcsynapsewsprod.sql.azuresynapse.net;dwhprd",
          "Username": "sqladminuser",
          "EncryptConnection": true
        }
      }
    ],
    "tables": [
      {
        "name": "Dim - Distributor",
        "columns": [
          {
            "name": "DISTRIBUTOR_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DISTRIBUTOR_WID"
          },
          {
            "name": "Role",
            "dataType": "string",
            "sourceColumn": "Role"
          },
          {
            "name": "Distributor Short Name",
            "dataType": "string",
            "sourceColumn": "Distributor Short Name"
          },
          {
            "name": "Distributor Name",
            "dataType": "string",
            "sourceColumn": "Distributor Name"
          },
          {
            "name": "Linked Vendor Code",
            "dataType": "string",
            "sourceColumn": "Linked Vendor Code"
          },
          {
            "name": "Linked Distributor Code",
            "dataType": "string",
            "sourceColumn": "Linked Distributor Code"
          },
          {
            "name": "Type",
            "dataType": "string",
            "sourceColumn": "Type"
          },
          {
            "name": "Email",
            "dataType": "string",
            "sourceColumn": "Email"
          },
          {
            "name": "Address Level 1",
            "dataType": "string",
            "sourceColumn": "Address Level 1"
          },
          {
            "name": "Address Level 2",
            "dataType": "string",
            "sourceColumn": "Address Level 2"
          },
          {
            "name": "Address Level 3",
            "dataType": "string",
            "sourceColumn": "Address Level 3"
          },
          {
            "name": "Phone No 1",
            "dataType": "string",
            "sourceColumn": "Phone No 1"
          },
          {
            "name": "Phone No 2",
            "dataType": "string",
            "sourceColumn": "Phone No 2"
          },
          {
            "name": "Fax",
            "dataType": "string",
            "sourceColumn": "Fax"
          },
          {
            "name": "Region Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Region Code"
          },
          {
            "name": "Region Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Region Name"
          },
          {
            "name": "Province Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Province Code"
          },
          {
            "name": "Province Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Province Name"
          },
          {
            "name": "District Code",
            "dataType": "string",
            "sourceColumn": "District Code"
          },
          {
            "name": "District Name",
            "dataType": "string",
            "sourceColumn": "District Name"
          },
          {
            "name": "Is Main Office",
            "dataType": "string",
            "sourceColumn": "Is Main Office"
          },
          {
            "name": "Distributor Code",
            "dataType": "string",
            "sourceColumn": "Distributor Code"
          },
          {
            "name": "First Order Date",
            "dataType": "dateTime",
            "sourceColumn": "First Order Date"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_DISTRIBUTOR_D = Source{[Schema=\"dbo\",Item=\"VW_DISTRIBUTOR_D\"]}[Data]",
                "in",
                "    dbo_VW_DISTRIBUTOR_D"
              ]
            }
          }
        ]
      },
      {
        "name": "Dim - Outlet",
        "columns": [
          {
            "name": "OUTLET_WID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "OUTLET_WID"
          },
          {
            "name": "Outlet Code",
            "dataType": "string",
            "sourceColumn": "Outlet Code"
          },
          {
            "name": "Baseline Date",
            "dataType": "dateTime",
            "sourceColumn": "Baseline Date"
          },
          {
            "name": "Outlet Type",
            "dataType": "string",
            "sourceColumn": "Outlet Type"
          },
          {
            "name": "Salutation",
            "dataType": "string",
            "sourceColumn": "Salutation"
          },
          {
            "name": "Email",
            "dataType": "string",
            "sourceColumn": "Email"
          },
          {
            "name": "Website",
            "dataType": "string",
            "sourceColumn": "Website"
          },
          {
            "name": "Phone No 1",
            "dataType": "string",
            "sourceColumn": "Phone No 1"
          },
          {
            "name": "Phone No 2",
            "dataType": "string",
            "sourceColumn": "Phone No 2"
          },
          {
            "name": "Ward Name",
            "dataType": "string",
            "sourceColumn": "Ward Name"
          },
          {
            "name": "Channel",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Channel"
          },
          {
            "name": "Sub Channel",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sub Channel"
          },
          {
            "name": "Shop Format",
            "dataType": "string",
            "sourceColumn": "Shop Format"
          },
          {
            "name": "Display Class",
            "dataType": "string",
            "sourceColumn": "Display Class"
          },
          {
            "name": "Loyalty Class",
            "dataType": "string",
            "sourceColumn": "Loyalty Class"
          },
          {
            "name": "Shop Area",
            "dataType": "string",
            "sourceColumn": "Shop Area"
          },
          {
            "name": "Shop Location",
            "dataType": "string",
            "sourceColumn": "Shop Location"
          },
          {
            "name": "Sales Level",
            "dataType": "string",
            "sourceColumn": "Sales Level"
          },
          {
            "name": "Shop Model",
            "dataType": "string",
            "sourceColumn": "Shop Model"
          },
          {
            "name": "Distributor Channel",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Distributor Channel"
          },
          {
            "name": "Outlet Name",
            "dataType": "string",
            "sourceColumn": "Outlet Name"
          },
          {
            "name": "Address Detail",
            "dataType": "string",
            "sourceColumn": "Address Detail"
          },
          {
            "name": "First Order Date",
            "dataType": "dateTime",
            "sourceColumn": "First Order Date"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_OUTLET_D = Source{[Schema=\"dbo\",Item=\"VW_OUTLET_D\"]}[Data]",
                "in",
                "    dbo_VW_OUTLET_D"
              ]
            }
          }
        ]
      },
      {
        "name": "Dim - Date",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "DATE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DATE_WID"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date"
          },
          {
            "name": "Date Number",
            "dataType": "int64",
            "sourceColumn": "Date Number",
            "summarizeBy": "none"
          },
          {
            "name": "Date Name",
            "dataType": "string",
            "sourceColumn": "Date Name",
            "sortByColumn": "Day Of Week VN"
          },
          {
            "name": "Week Of Month",
            "dataType": "int64",
            "sourceColumn": "Week Of Month",
            "summarizeBy": "none"
          },
          {
            "name": "Week Of Year",
            "dataType": "string",
            "sourceColumn": "Week Of Year"
          },
          {
            "name": "Week Number",
            "dataType": "int64",
            "sourceColumn": "Week Number",
            "summarizeBy": "none"
          },
          {
            "name": "Week Name",
            "dataType": "string",
            "sourceColumn": "Week Name"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "sortByColumn": "Month Number"
          },
          {
            "name": "Month Number",
            "dataType": "int64",
            "sourceColumn": "Month Number",
            "summarizeBy": "none"
          },
          {
            "name": "Month Name",
            "dataType": "string",
            "sourceColumn": "Month Name",
            "sortByColumn": "Month Number"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter"
          },
          {
            "name": "Quarter Number",
            "dataType": "int64",
            "sourceColumn": "Quarter Number",
            "summarizeBy": "none"
          },
          {
            "name": "Quarter Name",
            "dataType": "string",
            "sourceColumn": "Quarter Name",
            "sortByColumn": "Quarter Number"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year",
            "summarizeBy": "none"
          },
          {
            "name": "Holiday",
            "dataType": "string",
            "sourceColumn": "Holiday"
          },
          {
            "name": "Day Of Week VN",
            "dataType": "string",
            "sourceColumn": "Day Of Week VN"
          },
          {
            "name": "Period Type",
            "dataType": "string",
            "sourceColumn": "Period Type"
          },
          {
            "name": "Period Type Order",
            "dataType": "int64",
            "sourceColumn": "Period Type Order",
            "summarizeBy": "none"
          },
          {
            "name": "Closing Flag",
            "dataType": "string",
            "sourceColumn": "Closing Flag"
          },
          {
            "name": "Date Type",
            "dataType": "string",
            "sourceColumn": "Date Type"
          },
          {
            "name": "Is Holiday",
            "dataType": "string",
            "sourceColumn": "Is Holiday"
          },
          {
            "name": "Back 30 Working Day",
            "dataType": "dateTime",
            "sourceColumn": "Back 30 Working Day"
          },
          {
            "name": "Is Holiday NPP",
            "dataType": "string",
            "sourceColumn": "Is Holiday NPP"
          },
          {
            "name": "Is Holiday THS",
            "dataType": "string",
            "sourceColumn": "Is Holiday THS"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_CALENDAR_D = Source{[Schema=\"dbo\",Item=\"VW_CALENDAR_D\"]}[Data]",
                "in",
                "    dbo_VW_CALENDAR_D"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Total Non - Working Day",
            "expression": "CALCULATE( COUNT('Dim - Date'[Date]), 'Dim - Date'[Is Holiday] = \"Y\")",
            "formatString": "#,0"
          },
          {
            "name": "Total Working Day",
            "expression": "CALCULATE( COUNT('Dim - Date'[Date]), 'Dim - Date'[Is Holiday NPP] = \"N\")",
            "formatString": "#,0"
          },
          {
            "name": "Passing Days",
            "expression": " CALCULATE(COUNT('Dim - Date'[Date]),FILTER('Dim - Date',  'Dim - Date'[Date] < TODAY()&& 'Dim - Date'[Is Holiday] = \"N\"))",
            "formatString": "#,0"
          },
          {
            "name": "% Passing Days",
            "expression": " DIVIDE([Passing Days], [Total Working Day])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "Days Left",
            "expression": " [Total Working Day] - [Passing Days]",
            "formatString": "#,0"
          },
          {
            "name": "% Days Left",
            "expression": " DIVIDE([Days Left], [Total Working Day])",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "Passing Months",
            "expression": " TOTALYTD(DISTINCTCOUNT('Dim - Date'[Month]), 'Dim - Date'[Date])",
            "formatString": "0"
          },
          {
            "name": "Months Left",
            "expression": " 12 - [Passing Months]",
            "formatString": "0"
          },
          {
            "name": "Total Working Day THS",
            "expression": " CALCULATE( COUNT('Dim - Date'[Date]), 'Dim - Date'[Is Holiday THS] = \"N\",REMOVEFILTERS('Dim - Date'[Date],'Dim - Date'[Date Number],'Dim - Date'[Closing Flag]))",
            "formatString": "#,0"
          },
          {
            "name": "Total Working Day NPP",
            "expression": " CALCULATE( COUNT('Dim - Date'[Date]), 'Dim - Date'[Is Holiday NPP] = \"N\",REMOVEFILTERS('Dim - Date'[Date],'Dim - Date'[Date Number],'Dim - Date'[Closing Flag]))",
            "formatString": "#,0"
          },
          {
            "name": "Total Non - Working Day THS",
            "expression": "CALCULATE( COUNT('Dim - Date'[Date]), 'Dim - Date'[Is Holiday THS] = \"Y\")",
            "formatString": "#,0"
          },
          {
            "name": "Total Non - Working Day NPP",
            "expression": "CALCULATE( COUNT('Dim - Date'[Date]), 'Dim - Date'[Is Holiday NPP] = \"Y\")",
            "formatString": "#,0"
          },
          {
            "name": "Passing Days NPP",
            "expression": " CALCULATE(COUNT('Dim - Date'[Date]),FILTER('Dim - Date',  'Dim - Date'[Date] < TODAY()&& 'Dim - Date'[Is Holiday NPP] = \"N\"))"
          },
          {
            "name": "% Passing Days NPP",
            "expression": " DIVIDE([Passing Days NPP], [Total Working Day NPP])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Days Left NPP",
            "expression": " [Total Working Day NPP] - [Passing Days NPP]"
          },
          {
            "name": "ADS NPP",
            "expression": [
              "",
              "VAR AMTREMAINING = [Sell Out AOP/Target] - [Sell Out Amt/Qty MTD]",
              "VAR DAYSLEFT = [Total Working Day NPP] - [Passing Days NPP]",
              "VAR result =",
              "    IF ( DAYSLEFT = 0, AMTREMAINING, DIVIDE ( AMTREMAINING, DAYSLEFT, BLANK () ) )",
              "RETURN",
              "    IF ( result < 0, 0, result )"
            ],
            "formatString": "#,0"
          },
          {
            "name": "vs Time Gone NPP",
            "expression": [
              "",
              "VAR Timegone =",
              "    DIVIDE ( [Passing Days NPP], [Total Working Day NPP], BLANK () )",
              "VAR aoptargetmtd =",
              "    TOTALMTD ( [Sell Out AOP/Target], 'Dim - Date'[Date] )",
              "RETURN",
              "    DIVIDE ( DIVIDE ( [Sell Out Amt/Qty MTD], aoptargetmtd ), Timegone, BLANK () )"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Days Left THS",
            "expression": " [Total Working Day THS] - [Passing Days THS]"
          },
          {
            "name": "Passing Days THS",
            "expression": " CALCULATE(COUNT('Dim - Date'[Date]),FILTER('Dim - Date',  'Dim - Date'[Date] < TODAY()&& 'Dim - Date'[Is Holiday THS] = \"N\"))"
          },
          {
            "name": "% Passing Days THS",
            "expression": " DIVIDE([Passing Days THS], [Total Working Day THS])",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "ADS THS",
            "expression": [
              "",
              "VAR AMTREMAINING = [Sell Out AOP/Target] - [Sell Out Amt/Qty MTD]",
              "VAR DAYSLEFT = [Total Working Day THS] - [Passing Days THS]",
              "VAR result =",
              "    IF ( DAYSLEFT = 0, AMTREMAINING, DIVIDE ( AMTREMAINING, DAYSLEFT, BLANK () ) )",
              "RETURN",
              "    IF ( result < 0, 0, result )"
            ]
          },
          {
            "name": "vs Time Gone THS",
            "expression": [
              "",
              "VAR Timegone =",
              "    DIVIDE ( [Passing Days THS], [Total Working Day THS], BLANK () )",
              "VAR aoptargetmtd =",
              "    TOTALMTD ( [Sell Out AOP/Target], 'Dim - Date'[Date] )",
              "RETURN",
              "    DIVIDE ( DIVIDE ( [Sell Out Amt/Qty MTD], aoptargetmtd ), Timegone, BLANK () )"
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Month Selected",
            "expression": [
              "",
              "VAR TEMTAB =",
              "    ALLSELECTED (",
              "        'Dim - Date'[Month Name],",
              "        'Dim - Date'[Month Number],",
              "        'Dim - Date'[Month]",
              "    )",
              "RETURN",
              "    IF (",
              "        ISFILTERED ( 'Dim - Date'[Month] ),",
              "        CONCATENATEX ( TEMTAB, [Month Number], \", \", [Month Number] ),",
              "        \"All\"",
              "    )"
            ]
          },
          {
            "name": "Year Selected",
            "expression": " CONCATENATEX(ALLSELECTED('Dim - Date'[Year]),'Dim - Date'[Year],\", \")"
          },
          {
            "name": "Date Selected",
            "expression": [
              "",
              "IF (",
              "    ISFILTERED ( 'Dim - Date'[Date] ),",
              "    CONCATENATEX (",
              "        ALLSELECTED ( 'Dim - Date'[Date] ),",
              "        'Dim - Date'[Date],",
              "        \", \",",
              "        'Dim - Date'[Date]",
              "    ),",
              "    \"All\"",
              ")"
            ]
          },
          {
            "name": "Time Gone THS",
            "expression": [
              "  DIVIDE ( [Passing Days THS], [Total Working Day THS], BLANK () )",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Time Gone NPP",
            "expression": [
              "  DIVIDE ( [Passing Days NPP], [Total Working Day NPP], BLANK () )",
              ""
            ],
            "formatString": "0.0%;-0.0%;0.0%"
          }
        ]
      },
      {
        "name": "Fact - Sell Out",
        "columns": [
          {
            "name": "DATE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DATE_WID",
            "displayFolder": "Attribute"
          },
          {
            "name": "DISTRIBUTOR_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DISTRIBUTOR_WID",
            "displayFolder": "Attribute"
          },
          {
            "name": "OUTLET_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OUTLET_WID",
            "displayFolder": "Attribute"
          },
          {
            "name": "PRODUCT_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PRODUCT_WID",
            "displayFolder": "Attribute"
          },
          {
            "name": "PROMOTION_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PROMOTION_WID",
            "displayFolder": "Attribute"
          },
          {
            "name": "Route",
            "dataType": "string",
            "sourceColumn": "Route",
            "displayFolder": "Attribute"
          },
          {
            "name": "UOM",
            "dataType": "string",
            "sourceColumn": "Uom",
            "displayFolder": "Attribute"
          },
          {
            "name": "SALESFORCE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SALESFORCE_WID",
            "displayFolder": "Attribute"
          },
          {
            "name": "Order Number",
            "dataType": "string",
            "sourceColumn": "Order Number",
            "displayFolder": "Attribute"
          },
          {
            "name": "Order Type",
            "dataType": "string",
            "sourceColumn": "Order Type",
            "displayFolder": "Attribute"
          },
          {
            "name": "Order Line Number",
            "dataType": "string",
            "sourceColumn": "Order Line Number",
            "displayFolder": "Attribute"
          },
          {
            "name": "Invoice Date",
            "dataType": "dateTime",
            "sourceColumn": "Invoice Date",
            "displayFolder": "Attribute"
          },
          {
            "name": "Unit Price",
            "dataType": "double",
            "sourceColumn": "Unit Price",
            "displayFolder": "Attribute"
          },
          {
            "name": "Is Free",
            "dataType": "string",
            "sourceColumn": "Is Free",
            "displayFolder": "Attribute"
          },
          {
            "name": "Order Qty",
            "dataType": "double",
            "sourceColumn": "Order Qty",
            "displayFolder": "Attribute"
          },
          {
            "name": "Discount Amt",
            "dataType": "double",
            "sourceColumn": "Discount Amt",
            "displayFolder": "Attribute"
          },
          {
            "name": "Is Return Order Flg",
            "dataType": "string",
            "sourceColumn": "Is Return Order Flg",
            "displayFolder": "Attribute"
          },
          {
            "name": "SALES_TERRITORY_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SALES_TERRITORY_WID",
            "displayFolder": "Attribute"
          },
          {
            "name": "CHANNEL_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CHANNEL_WID",
            "displayFolder": "Attribute"
          },
          {
            "name": "STORE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "STORE_WID",
            "displayFolder": "Attribute"
          },
          {
            "name": "Invoice Split Number",
            "dataType": "int64",
            "sourceColumn": "Invoice Split Number",
            "displayFolder": "Attribute"
          },
          {
            "name": "Distributor ID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Distributor ID",
            "displayFolder": "Attribute"
          },
          {
            "name": "Net Amt",
            "dataType": "double",
            "sourceColumn": "Net Amt",
            "displayFolder": "Attribute"
          },
          {
            "name": "TENDER_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TENDER_WID",
            "displayFolder": "Attribute"
          },
          {
            "name": "SALE_TYPE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SALE_TYPE_WID",
            "displayFolder": "Attribute"
          },
          {
            "name": "MEMBER_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "MEMBER_WID",
            "displayFolder": "Attribute"
          },
          {
            "name": "TIME_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TIME_WID",
            "displayFolder": "Attribute"
          },
          {
            "name": "Store Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Store Code",
            "displayFolder": "Attribute"
          },
          {
            "name": "Product ID/Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product ID/Code",
            "displayFolder": "Attribute"
          },
          {
            "name": "Invoice Number",
            "dataType": "string",
            "sourceColumn": "Invoice Number",
            "displayFolder": "Attribute"
          },
          {
            "name": "Shipped Qty",
            "dataType": "double",
            "sourceColumn": "Shipped Qty",
            "displayFolder": "Attribute"
          },
          {
            "name": "Vat Amt",
            "dataType": "double",
            "sourceColumn": "Vat Amt",
            "displayFolder": "Attribute"
          },
          {
            "name": "Gross Amt",
            "dataType": "double",
            "sourceColumn": "Gross Amt",
            "displayFolder": "Attribute"
          },
          {
            "name": "Estimated Amt",
            "dataType": "double",
            "sourceColumn": "Estimated Amt",
            "displayFolder": "Attribute"
          },
          {
            "name": "Outlet ID/Member Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Outlet ID/Member Code",
            "displayFolder": "Attribute"
          },
          {
            "name": "Route Type Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Route Type Code",
            "displayFolder": "Attribute"
          },
          {
            "name": "ROUTE_TYPE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ROUTE_TYPE_WID",
            "displayFolder": "Attribute"
          },
          {
            "name": "Convert Rate to Ml",
            "dataType": "double",
            "sourceColumn": "Convert Rate to Ml",
            "displayFolder": "Attribute"
          },
          {
            "name": "Convert Rate to Gram",
            "dataType": "double",
            "sourceColumn": "Convert Rate to Gram",
            "displayFolder": "Attribute"
          },
          {
            "name": "Source Type",
            "dataType": "string",
            "sourceColumn": "Source Type",
            "displayFolder": "Attribute"
          },
          {
            "name": "Carton Shipped Qty",
            "dataType": "double",
            "sourceColumn": "Carton Shipped Qty",
            "displayFolder": "Attribute"
          },
          {
            "name": "ORDER_AMT_RANGE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ORDER_AMT_RANGE_WID",
            "displayFolder": "Attribute"
          },
          {
            "name": "STORE_AMT_RANGE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "STORE_AMT_RANGE_WID",
            "displayFolder": "Attribute"
          },
          {
            "name": "Store Aging",
            "dataType": "int64",
            "sourceColumn": "Store Aging",
            "displayFolder": "Attribute"
          },
          {
            "name": "Order Date",
            "dataType": "dateTime",
            "sourceColumn": "Order Date",
            "displayFolder": "Attribute"
          }
        ],
        "partitions": [
          {
            "name": "Part202101",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20210101 and [DATE_WID] < 20210201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data]",
                  "in",
                  "    dbo_VW_SELLOUT_INVOICE_F</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202102",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20210201 and [DATE_WID] < 20210301)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20210201 and [DATE_WID] < 20210301)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202103",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20210301 and [DATE_WID] < 20210401)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20210301 and [DATE_WID] < 20210401)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202104",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20210401 and [DATE_WID] < 20210501)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20210401 and [DATE_WID] < 20210501)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202105",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20210501 and [DATE_WID] < 20210601)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20210501 and [DATE_WID] < 20210601)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202106",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20210601 and [DATE_WID] < 20210701)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20210601 and [DATE_WID] < 20210701)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202107",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20210701 and [DATE_WID] < 20210801)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20210701 and [DATE_WID] < 20210801)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202108",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20210801 and [DATE_WID] < 20210901)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20210801 and [DATE_WID] < 20210901)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202109",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20210901 and [DATE_WID] < 20211001)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20210901 and [DATE_WID] < 20211001)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202110",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20211001 and [DATE_WID] < 20211101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20211001 and [DATE_WID] < 20211101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202111",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20211101 and [DATE_WID] < 20211201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20211101 and [DATE_WID] < 20211201)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202112",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20211201 and [DATE_WID] < 20220101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20211201 and [DATE_WID] < 20220101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202001",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20200101 and [DATE_WID] < 20200201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202002",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20200201 and [DATE_WID] < 20200301)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202003",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20200301 and [DATE_WID] < 20200401)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202004",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20200401 and [DATE_WID] < 20200501)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202005",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20200501 and [DATE_WID] < 20200601)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202006",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20200601 and [DATE_WID] < 20200701)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202007",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20200701 and [DATE_WID] < 20200801)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202008",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20200801 and [DATE_WID] < 20200901)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202009",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20200901 and [DATE_WID] < 20201001)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202010",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20201001 and [DATE_WID] < 20201101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202011",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20201101 and [DATE_WID] < 20201201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202012",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20201201 and [DATE_WID] < 20210101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201901",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20190101 and [DATE_WID] < 20190201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201902",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20190201 and [DATE_WID] < 20190301)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201903",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20190301 and [DATE_WID] < 20190401)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201904",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20190401 and [DATE_WID] < 20190501)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201905",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20190501 and [DATE_WID] < 20190601)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201906",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20190601 and [DATE_WID] < 20190701)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201907",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20190701 and [DATE_WID] < 20190801)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201908",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20190801 and [DATE_WID] < 20190901)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201909",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20190901 and [DATE_WID] < 20191001)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201910",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20191001 and [DATE_WID] < 20191101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201911",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20191101 and [DATE_WID] < 20191201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201912",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SELLOUT_INVOICE_F = Source{[Schema=\"dbo\",Item=\"VW_SELLOUT_INVOICE_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_SELLOUT_INVOICE_F, each [DATE_WID] >= 20191201 and [DATE_WID] < 20200101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "# of invoices",
            "expression": [
              "",
              "COUNTROWS (",
              "    FILTER (",
              "        SUMMARIZE (",
              "            'Fact - Sell Out',",
              "            'Fact - Sell Out'[Invoice Number],",
              "            \"@NetAmt\", SUM ( 'Fact - Sell Out'[Net Amt] )",
              "        ),",
              "        [@NetAmt] > 0",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Orders",
            "expression": [
              " ",
              "var _Ordertb = SUMMARIZE('Fact - Sell Out', 'Fact - Sell Out'[DATE_WID], 'Fact - Sell Out'[Outlet ID/Member Code])",
              "return",
              "COUNTROWS(_Ordertb)",
              "",
              "/*DISTINCTCOUNT('Fact - Sell Out'[Order Number]) */"
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Successful Orders",
            "expression": [
              " ",
              "var _Ordertb = /*FILTER(SUMMARIZE('Fact - Sell Out', 'Fact - Sell Out'[DATE_WID], 'Fact - Sell Out'[Outlet ID/Member Code], 'Fact - Sell Out'[Invoice Number],'Fact - Sell Out'[Is Free], 'Fact - Sell Out'[Route Type Code]), 'Fact - Sell Out'[Invoice Number] <> \"\" && 'Fact - Sell Out'[Route Type Code] <> \"VI\" && 'Fact - Sell Out'[Route Type Code] <> \"19LNM\"&&'Fact - Sell Out'[Is Free] = \"N\" )*/",
              "FILTER(SUMMARIZE('Fact - Sell Out', 'Fact - Sell Out'[DATE_WID], 'Fact - Sell Out'[Outlet ID/Member Code], 'Fact - Sell Out'[order Number],'Fact - Sell Out'[Is Free], 'Fact - Sell Out'[Route Type Code]), 'Fact - Sell Out'[order Number] <> \"\" &&'Fact - Sell Out'[Is Free] = \"N\" )",
              "var _SuccessOrder = SUMMARIZE(_Ordertb, 'Fact - Sell Out'[DATE_WID], 'Fact - Sell Out'[Outlet ID/Member Code])",
              "return",
              "COUNTROWS(_SuccessOrder)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "Sell Out Amt LM",
            "expression": " CALCULATE([Sell Out Amt], DATEADD('Dim - Date'[Date], -1, MONTH))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt LY",
            "expression": " CALCULATE([Sell Out Amt],SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt Growth % vs LM",
            "expression": " IF(ISBLANK(DIVIDE([Sell Out Amt], [Sell Out Amt LM])), BLANK(), DIVIDE([Sell Out Amt], [Sell Out Amt LM]) - 1)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt Growth % vs LY",
            "expression": " IF(ISBLANK(DIVIDE([Sell Out Amt], [Sell Out Amt LY])), BLANK(), DIVIDE([Sell Out Amt], [Sell Out Amt LY]) - 1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt MTD",
            "expression": " TOTALMTD([Sell Out Amt], 'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt YTD",
            "expression": " TOTALYTD([Sell Out Amt], 'Dim - Date'[Date])",
            "formatString": "#,0.00",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt MTD LM",
            "expression": " CALCULATE([Sell Out Amt MTD], DATEADD('Dim - Date'[Date], -1 , MONTH))",
            "formatString": "0.00",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt MTD LY",
            "expression": " CALCULATE([Sell Out Amt MTD], SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Qty",
            "expression": " CALCULATE(SUM('Fact - Sell Out'[Shipped Qty]),  'Fact - Sell Out'[Shipped Qty] <> 0, KEEPFILTERS('Fact - Sell Out'))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Qty LM",
            "expression": " CALCULATE([Sell Out Qty], DATEADD('Dim - Date'[Date], -1, MONTH))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Qty LY",
            "expression": " CALCULATE([Sell Out Qty],SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Qty Growth % vs LM",
            "expression": " IF(ISBLANK(DIVIDE([Sell Out Qty], [Sell Out Qty LM])), BLANK(), DIVIDE([Sell Out Qty], [Sell Out Qty LM]) - 1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Qty Growth % vs LY",
            "expression": " IF(ISBLANK(DIVIDE([Sell Out Qty], [Sell Out Qty LY])), BLANK(), DIVIDE([Sell Out Qty], [Sell Out Qty LY]) - 1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Qty MTD",
            "expression": " TOTALMTD([Sell Out Qty], 'Dim - Date'[Date])",
            "formatString": "#,0.00",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Qty YTD",
            "expression": " TOTALYTD([Sell Out Qty], 'Dim - Date'[Date])",
            "formatString": "#,0.00",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Qty MTD LM",
            "expression": " CALCULATE([Sell Out Qty MTD], DATEADD('Dim - Date'[Date], -1, MONTH))",
            "formatString": "#,0.00",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Qty MTD LY",
            "expression": " CALCULATE([Sell Out Qty MTD], SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
            "formatString": "#,0.00",
            "displayFolder": "Sell Out"
          },
          {
            "name": "AVG Daily Sell Out Qty",
            "expression": " DIVIDE([Sell Out Qty MTD], [Passing Days])",
            "formatString": "#,0.00",
            "displayFolder": "Sell Out"
          },
          {
            "name": "AVG Daily Sell Out Amt",
            "expression": " DIVIDE([Sell Out Amt MTD], [Passing Days])",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt % vs Target",
            "expression": " DIVIDE([Sell Out Amt], [Sell Out Amt Target])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Qty % vs Target",
            "expression": " DIVIDE([Sell Out Qty], [Sell Out Qty Target])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt % vs AOP",
            "expression": " DIVIDE([Sell Out Amt], [Sell Out Amt AOP])",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Qty % vs AOP",
            "expression": " DIVIDE([Sell Out Qty], [Sell Out Qty AOP])",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt % vs AOP FY",
            "expression": " DIVIDE([Sell Out Amt], [Sell Out Amt AOP FY])",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Qty % vs AOP FY",
            "expression": " DIVIDE([Sell Out Qty], [Sell Out Qty AOP FY])",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt Remaining vs AOP",
            "expression": " [Sell Out Amt AOP] - [Sell Out Amt MTD]",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Qty Remaining vs AOP",
            "expression": " [Sell Out Qty AOP] - [Sell Out Qty MTD]",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt Remaining vs AOP FY",
            "expression": " [Sell Out Amt AOP FY] - [Sell Out Amt YTD]",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt Projection",
            "expression": " [AVG Daily Sell Out Amt]*[Total Working Day]",
            "formatString": "#,0.00",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Qty Projection",
            "expression": " [AVG Daily Sell Out Qty]*[Total Working Day]",
            "formatString": "#,0.00",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt Projection % vs Target",
            "expression": " DIVIDE([Sell Out Amt Projection], [Sell Out Amt Target])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Qty Projection % vs Target",
            "expression": " DIVIDE([Sell Out Qty Projection], [Sell Out Qty Target])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt Projection % vs AOP",
            "expression": " DIVIDE([Sell Out Amt Projection], [Sell Out Amt AOP])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Qty Projection % vs AOP",
            "expression": " DIVIDE([Sell Out Qty Projection], [Sell Out Qty AOP])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "# of ASO",
            "expression": [
              "  CALCULATE(DISTINCTCOUNT('Fact - Sell Out'[Outlet ID/Member Code]), 'Fact - Sell Out'[Gross Amt] > 0)",
              "/*CALCULATE(DISTINCTCOUNT('Fact - Sell Out'[Outlet ID/Member Code]), 'Fact - Sell Out'[Gross Amt] > 0, 'Fact - Sell Out'[Route Type Code] <> \"19LNM\",  'Fact - Sell Out'[Route Type Code] <> \"VI\") */"
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of ASO MTD",
            "expression": " TOTALMTD([# of ASO], 'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of ASO YTD",
            "expression": " TOTALYTD([# of ASO], 'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of ASO LM",
            "expression": " CALCULATE([# of ASO], DATEADD('Dim - Date'[Date],-1,MONTH))",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of ASO MTD LM",
            "expression": " CALCULATE([# of ASO MTD], PREVIOUSMONTH('Dim - Date'[Date]))",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of ASO LY",
            "expression": " CALCULATE([# of ASO], SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of ASO YTD LY",
            "expression": " CALCULATE([# of ASO YTD], SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "ASO Growth % vs LM",
            "expression": " IF(OR([# of ASO]=0, [# of ASO LM]=0), BLANK(), DIVIDE([# of ASO]- [# of ASO LM], [# of ASO LM]))",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "displayFolder": "KPI"
          },
          {
            "name": "ASO Growth % vs LY",
            "expression": " IF(OR([# of ASO]=0, [# of ASO LY]=0), BLANK(), DIVIDE([# of ASO] - [# of ASO LY], [# of ASO LY]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "ASO MTD Growth % vs LM",
            "expression": " IF(ISBLANK(DIVIDE([# of ASO MTD], [# of ASO MTD LM])), BLANK(), DIVIDE([# of ASO MTD], [# of ASO MTD LM]))",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI"
          },
          {
            "name": "ASO YTD Growth % vs LM",
            "expression": " IF(ISBLANK(DIVIDE([# of ASO YTD], [# of ASO YTD LY])), BLANK(), DIVIDE([# of ASO YTD], [# of ASO YTD LY]))",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI"
          },
          {
            "name": "# of ASO by Amt Range",
            "expression": [
              "",
              "VAR minsel = MIN('Amt Range'[Value])",
              "VAR maxsel = MAX('Amt Range'[Value])",
              "VAR temtab =",
              "    FILTER (",
              "        ADDCOLUMNS (",
              "            SUMMARIZE ( 'Fact - Sell Out','Dim - Distributor'[Distributor Code], 'Dim - Outlet'[Outlet Code] ,'Fact - Sell Out'[Route]),",
              "            \"@amt\", [Sell Out Amt]",
              "        ),",
              "        [@amt] >= minsel",
              "            && [@amt] <= maxsel",
              "    )",
              "RETURN",
              "    COUNTROWS ( temtab )"
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of ASO by Qty Range",
            "expression": [
              "",
              "var _SelectedQtyMin = 10",
              "var _SelectedQtyMax = 20",
              "Return ",
              "CALCULATE(DISTINCTCOUNT('Fact - Sell Out'[OUTLET_WID]), 'Fact - Sell Out'[Order Qty] >= _SelectedQtyMin, 'Fact - Order Detail'[Order Qty] <= _SelectedQtyMax)",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of New ASO by Date Range",
            "expression": [
              "",
              "var _selectedmindate = MIN('Dim - Date'[Date])",
              "var _selectedmaxdate = MAX('Dim - Date'[Date])",
              "return",
              "CALCULATE(DISTINCTCOUNT('Fact - Sell Out'[Outlet ID/Member Code]),'Dim - Outlet'[First Order Date] >= _selectedmindate, 'Dim - Outlet'[First Order Date]<= _selectedmaxdate)"
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of New ASO",
            "expression": [
              " ",
              "VAR mindate =",
              "    MIN ( 'Dim - Date'[Date] )",
              "VAR maxdate =",
              "    MAX ('Dim - Date'[Date] )",
              "RETURN",
              "    COUNTROWS(FILTER (",
              "    ADDCOLUMNS (",
              "        SUMMARIZE (",
              "            'Fact - Sell Out',",
              "            'Dim - Outlet'[Outlet Code],",
              "            'Dim - Outlet'[First Order Date]",
              "        ),",
              "        \"@S\", [Sell Out Amt]",
              "    ),",
              "    'Dim - Outlet'[First Order Date] >= mindate",
              "        && 'Dim - Outlet'[First Order Date] <= maxdate",
              "        && [@S] > 0",
              "))"
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of New ASO MTD",
            "expression": " TOTALMTD([# of New ASO], 'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of New ASO YTD",
            "expression": " TOTALYTD([# of New ASO], 'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of New ASO LY",
            "expression": " CALCULATE([# of New ASO], SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of New ASO MTD LM",
            "expression": " CALCULATE([# of New ASO MTD], DATEADD('Dim - Date'[Date], -1, MONTH))",
            "displayFolder": "KPI"
          },
          {
            "name": "# of New ASO YTD LY",
            "expression": " CALCULATE([# of New ASO YTD], SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Repurchased ASO",
            "expression": [
              "",
              "VAR mindate =",
              "    MIN ( 'Fact - Sell Out'[Order Date] )",
              "VAR past_ids =",
              "    SUMMARIZE (",
              "        CALCULATETABLE (",
              "            'Fact - Sell Out',",
              "            REMOVEFILTERS ( 'Dim - Date' ),",
              "            'Fact - Sell Out'[Order Date] < mindate,",
              "            NOT ISBLANK ( 'Fact - Sell Out'[Order Date] ),",
              "            'Fact - Sell Out'[Gross Amt] > 0            ",
              "        ),",
              "        'Fact - Sell Out'[Outlet ID/Member Code]",
              "    )",
              "VAR current_ids =",
              "    SUMMARIZE (",
              "        CALCULATETABLE ( 'Fact - Sell Out', 'Fact - Sell Out'[Gross Amt] > 0 ),",
              "        'Fact - Sell Out'[Outlet ID/Member Code]",
              "    )",
              "VAR temtab =",
              "    INTERSECT ( current_ids, past_ids )",
              "VAR result =",
              "    COUNTROWS ( SUMMARIZE ( temtab, [Outlet ID/Member Code] ) )",
              "RETURN",
              "    result"
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Repurchased ASO MTD",
            "expression": " TOTALMTD([# of Repurchased ASO], 'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Repurchased ASO YTD",
            "expression": " TOTALYTD([# of Repurchased ASO], 'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Repurchased ASO LM",
            "expression": " CALCULATE([# of Repurchased ASO], DATEADD('Dim - Date'[Date],-1,MONTH))",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Repurchased ASO LY",
            "expression": " CALCULATE([# of Repurchased ASO], SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Repurchased ASO MTD LM",
            "expression": " CALCULATE([# of Repurchased ASO MTD], DATEADD('Dim - Date'[Date],-1,MONTH))",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Repurchased ASO YTD LY",
            "expression": " CALCULATE([# of Repurchased ASO YTD], SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
            "displayFolder": "KPI"
          },
          {
            "name": "Monthly Frequency ASO",
            "expression": [
              " ",
              "var _NoDays = -10",
              "return",
              "CALCULATE([# of ASO], DATESINPERIOD('Dim - Date'[Date], MAX('Dim - Date'[Date]), _NoDays, DAY))"
            ],
            "formatString": "0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of MCP",
            "expression": " DISTINCTCOUNT('Fact - MCP'[Outlet ID])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "VPO",
            "expression": " DIVIDE([Sell Out Amt/Qty], [# of ASO])",
            "formatString": "#,0.0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Calls Plan",
            "expression": " COUNT('Fact - MCP'[Call Plan Id])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of AVG Calls Plan per Day",
            "expression": " DIVIDE([# of Calls Plan], [Passing Days])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Successful Calls",
            "expression": " CALCULATE([# of Visited Calls], 'Fact - Actual Visit'[Order Number] <> \"\")",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "% Strike Rate",
            "expression": " DIVIDE([# of Successful Calls], [# of Calls Plan])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI"
          },
          {
            "name": "ASO/ MCP",
            "expression": " DIVIDE([# of ASO], [# of MCP])",
            "displayFolder": "KPI"
          },
          {
            "name": "ASO/ Route",
            "expression": " DIVIDE([# of ASO], [# of Invoiced Route])",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Order by Qty Range",
            "expression": [
              " ",
              "var _QtySelected = 10",
              "var _OrderValue = ADDCOLUMNS(SUMMARIZE('Fact - Sell Out', 'Fact - Sell Out'[Order Number]), \"_Qty\", [Sell Out Qty])",
              "var _OderValueHasCondition = FILTER(_OrderValue, [_Qty] >= _QtySelected)",
              "return ",
              "COUNTROWS(_OderValueHasCondition)"
            ],
            "displayFolder": "KPI"
          },
          {
            "name": "# of Unique SKUs",
            "expression": [
              " ",
              "VAR TEMTAB =",
              "    CALCULATETABLE (",
              "        'Fact - Sell Out',",
              "        'Fact - Sell Out'[Invoice Number] <> BLANK (),",
              "        'Fact - Sell Out'[Product ID/Code] <> BLANK ()",
              "    )",
              "VAR resultab =",
              "    SUMMARIZE (",
              "        TEMTAB,",
              "          'Fact - Sell Out'[Product ID/Code],",
              "        'Fact - Sell Out'[Invoice Number]",
              "    )",
              "RETURN",
              "    COUNTROWS ( resultab )"
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of SKUs",
            "expression": [
              " ",
              "var _Skutb = /*FILTER(SUMMARIZE('Fact - Sell Out', 'Fact - Sell Out'[DATE_WID], 'Fact - Sell Out'[Outlet ID/Member Code], 'Fact - Sell Out'[Product ID/Code], 'Fact - Sell Out'[Route Type Code], 'Fact - Sell Out'[Is Free]),  'Fact - Sell Out'[Route Type Code] <> \"VI\" && 'Fact - Sell Out'[Route Type Code] <> \"19LNM\" &&  'Fact - Sell Out'[Is Free] = \"N\") */",
              "FILTER(SUMMARIZE('Fact - Sell Out', 'Fact - Sell Out'[DATE_WID], 'Fact - Sell Out'[Outlet ID/Member Code], 'Fact - Sell Out'[Product ID/Code], 'Fact - Sell Out'[Route Type Code], 'Fact - Sell Out'[Is Free]),   'Fact - Sell Out'[Is Free] = \"N\")",
              "var _Sku = SUMMARIZE(_Skutb, 'Fact - Sell Out'[DATE_WID], 'Fact - Sell Out'[Outlet ID/Member Code], 'Fact - Sell Out'[Product ID/Code])",
              "return",
              "COUNTROWS(_Sku)",
              "",
              "/*CALCULATE(COUNT('Fact - Sell Out'[Product ID/Code]), 'Fact - Sell Out'[Route Type Code] <> \"VI\", 'Fact - Sell Out'[Route Type Code] <> \"19LNM\") */"
            ],
            "formatString": "#,0.00",
            "displayFolder": "KPI"
          },
          {
            "name": "# of SKUs per Successful Order",
            "expression": " DIVIDE([# of SKUs], [# of Successful Orders])",
            "formatString": "#,0.00",
            "displayFolder": "KPI"
          },
          {
            "name": "# of SKUs per ASO",
            "expression": " DIVIDE([# of SKUs], [# of ASO])",
            "formatString": "0.00",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Daily ASO",
            "expression": [
              " ",
              "VAR _Seleteddate = MIN('Dim - Date'[Date])",
              "return",
              "CALCULATE([# of ASO], 'Fact - Sell Out'[Order Date] = _Seleteddate)"
            ],
            "displayFolder": "KPI"
          },
          {
            "name": "# of Active Distributor",
            "expression": " CALCULATE(DISTINCTCOUNT('Fact - Sell Out'[Distributor ID]), 'Fact - Sell Out'[Gross Amt] >0)",
            "displayFolder": "KPI"
          },
          {
            "name": "DropSize",
            "expression": " DIVIDE([Sell Out Amt], [# of Successful Orders])",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Distributor by Amt Range",
            "expression": " ",
            "displayFolder": "KPI"
          },
          {
            "name": "# of New Distributor",
            "expression": [
              "",
              "VAR mindate =",
              "    MIN ( 'Dim - Date'[Date] )",
              "VAR maxdate =",
              "    MAX ('Dim - Date'[Date] )",
              "RETURN",
              "    COUNTROWS(FILTER (",
              "    ADDCOLUMNS (",
              "        SUMMARIZE (",
              "            'Fact - Sell Out',",
              "           'Dim - Distributor'[Distributor Code],",
              "            'Dim - Distributor'[First Order Date]",
              "        ),",
              "        \"@S\", [Sell Out Amt]",
              "    ),",
              "    'Dim - Distributor'[First Order Date]",
              " >= mindate &&",
              "         'Dim - Distributor'[First Order Date]",
              " <= maxdate",
              "        && [@S] > 0",
              "))"
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Bills of Members",
            "expression": " CALCULATE([# of invoices], 'Fact - Sell Out'[MEMBER_WID] <> 0 )",
            "displayFolder": "KPI"
          },
          {
            "name": "AVG Sell Out per Bill",
            "expression": " DIVIDE([Sell Out True Mart Net Amt], [# of invoices])",
            "formatString": "#,0.00",
            "displayFolder": "KPI"
          },
          {
            "name": "# of SKU per Bill",
            "expression": " DIVIDE( [# of Unique SKUs], [# of invoices])",
            "formatString": "#,0.00",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Bills by Amt Range",
            "expression": [
              " ",
              "var _SelectedAmtMin = 100",
              "var _SelectedAmtMax = 1000",
              "Return ",
              "CALCULATE(DISTINCTCOUNT('Fact - Sell Out'[Invoice Number]), 'Fact - Sell Out'[Gross Amt] >= _SelectedAmtMin, 'Fact - Sell Out'[Gross Amt] <= _SelectedAmtMax)"
            ],
            "displayFolder": "KPI"
          },
          {
            "name": "# of Active Members",
            "expression": " CALCULATE(DISTINCTCOUNT('Fact - Sell Out'[Outlet ID/Member Code]),'Fact - Sell Out'[Gross Amt]>0)",
            "displayFolder": "KPI"
          },
          {
            "name": "Sell Out Amt THS AOP",
            "expression": [
              "",
              "CALCULATE ( SUM ( 'Fact - AOP'[AOP Value] ), 'Fact - AOP'[AOP Type] = \"Amt\" )"
            ],
            "isHidden": true
          },
          {
            "name": "Sell Out Amt THS AOP FY",
            "expression": [
              "",
              "CALCULATE (",
              "    [Sell Out Amt THS AOP],",
              "    REMOVEFILTERS ( 'Dim - Date'[Date], 'Dim - Date'[Month] )",
              ")"
            ],
            "isHidden": true
          },
          {
            "name": "Sell Out Net Amt",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'Fact - Sell Out'[Net Amt] ),",
              "    'Fact - Sell Out',",
              "    'Fact - Sell Out'[Is Free] = \"N\",",
              "    'Fact - Sell Out'[Shipped Qty] <> 0,",
              "    'Dim - Product'[Is POSM] = \"N\",",
              "    KEEPFILTERS ( 'Fact - Sell Out' )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt Excl Voucher",
            "expression": " CALCULATE([Sell Out Amt], FILTER('Dim - Tender', NOT ( 'Dim - Tender'[Tender Type Name] IN { \"Voucher khng tch im\", \"Voucher tch im\" })))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt Voucher",
            "expression": "  CALCULATE([Sell Out Net Amt]*0.03,FILTER('Dim - Tender', 'Dim - Tender'[Tender Type Name] IN { \"Voucher khng tch im\", \"Voucher tch im\" }))",
            "formatString": "#,0.00",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out THs tnh thng",
            "expression": " [Sell Out Amt Voucher] + [Sell Out True Mart Net Amt]",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out THs tnh thng LM",
            "expression": " CALCULATE([Sell Out THs tnh thng], DATEADD('Dim - Date'[Date], -1, MONTH))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out THs tnh thng MTD",
            "expression": " TOTALMTD([Sell Out THs tnh thng], 'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out THs tnh thng MTD LM",
            "expression": "  CALCULATE([Sell Out THs tnh thng MTD], DATEADD('Dim - Date'[Date], -1, MONTH))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out THs tnh thng YTD",
            "expression": " TOTALYTD([Sell Out THs tnh thng], 'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out THs tnh thng YTD LY",
            "expression": "  CALCULATE([Sell Out THs tnh thng YTD], DATEADD('Dim - Date'[Date], -1, YEAR))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Qty Order THS",
            "expression": [
              " SUM('Fact - Order Detail'[Order Qty])",
              ""
            ],
            "isHidden": true,
            "displayFolder": "Sell Out"
          },
          {
            "name": "# of Repeated ASO",
            "expression": [
              " ",
              "VAR temtab =",
              "    SUMMARIZE (",
              "        CALCULATETABLE (",
              "            'Fact - Sell Out',",
              "            NOT ISBLANK ( 'Fact - Sell Out'[Order Date] ),",
              "            NOT ISBLANK ( 'Dim - Outlet'[Outlet Code] ),",
              "            'Fact - Sell Out'[Gross Amt]>0",
              "        ),",
              "        'Dim - Outlet'[Outlet Code],",
              "        'Fact - Sell Out'[Order Date]",
              "    )",
              "VAR temtab2 =",
              "    SUMMARIZE (",
              "        temtab,",
              "        [Outlet Code],",
              "        \"@C\", CALCULATE ( DISTINCTCOUNTNOBLANK ( 'Fact - Sell Out'[Order Date] ) )",
              "    )",
              "VAR temtab3 =",
              "    FILTER ( temtab2, [@C] >= 2 )",
              "RETURN ",
              "    COUNTROWS(temtab3)"
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Stores",
            "expression": " CALCULATE(DISTINCTCOUNT('Fact - Sell Out'[Store Code]))",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Store LM",
            "expression": " CALCULATE([# of Stores], DATEADD('Dim - Date'[Date],-1,MONTH))",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Store LY",
            "expression": " CALCULATE([# of Stores], SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Stores MTD",
            "expression": " TOTALMTD([# of Stores], 'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Stores MTD LM",
            "expression": " CALCULATE([# of Stores MTD], PREVIOUSMONTH('Dim - Date'[Date]))",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Stores YTD",
            "expression": " TOTALYTD([# of Stores], 'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Stores YTD LY",
            "expression": " CALCULATE([# of Stores YTD], SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of New Stores",
            "expression": [
              " ",
              "VAR mindate =",
              "    MIN ( 'Dim - Date'[Date] )",
              "VAR maxdate =",
              "    MAX ('Dim - Date'[Date] )",
              "RETURN",
              "    COUNTROWS(FILTER (",
              "    ADDCOLUMNS (",
              "        SUMMARIZE (",
              "            'Fact - Sell Out',",
              "           'Dim - Store'[Store Code],",
              "           'Dim - Store'[First Order Date]",
              "        ),",
              "        \"@S\", [Sell Out Amt]",
              "    ),",
              "    'Dim - Store'[First Order Date]",
              " >= mindate &&",
              "         'Dim - Store'[First Order Date]",
              " <= maxdate",
              "        && [@S] > 0",
              "))"
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Active Stores",
            "expression": " CALCULATE(DISTINCTCOUNT('Fact - Sell Out'[Store Code]),'Fact - Sell Out'[Gross Amt]>0)",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "Store Growth % vs LM",
            "expression": " IF(ISBLANK(DIVIDE([# of Stores], [# of Store LM])), BLANK(), DIVIDE([# of Stores], [# of Store LM]))-1",
            "formatString": "0%;-0%;0%",
            "displayFolder": "KPI"
          },
          {
            "name": "Store Growth % vs LY",
            "expression": " IF(ISBLANK(DIVIDE([# of Stores], [# of Store LY])), BLANK(), DIVIDE([# of Stores], [# of Store LY]))-1",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "KPI"
          },
          {
            "name": "# of New Members",
            "expression": [
              " ",
              "VAR mindate =",
              "    MIN ( 'Dim - Date'[Date])",
              "VAR maxdate =",
              "    MAX ( 'Dim - Date'[Date])",
              "RETURN",
              "    COUNTROWS(FILTER (",
              "    ADDCOLUMNS (",
              "        SUMMARIZE (",
              "            'Fact - Sell Out',",
              "            --'Dim - Channel'[Channel Name],",
              "            'Fact - Sell Out'[Outlet ID/Member Code],",
              "            'Dim - Member Ths'[First Order Date]",
              "        ),",
              "        \"@S\", [Sell Out Amt]",
              "    ),",
              "    'Dim - Member Ths'[First Order Date]",
              " >= mindate &&",
              "        'Dim - Member Ths'[First Order Date]",
              " <= maxdate",
              "        && [@S] > 0",
              "))"
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Repurchased Members",
            "expression": [
              "",
              "VAR mindate =",
              "    MIN ( 'Fact - Sell Out'[Order Date] )",
              "VAR past_ids =",
              "    SUMMARIZE (",
              "        CALCULATETABLE (",
              "            'Fact - Sell Out',",
              "            REMOVEFILTERS ( 'Dim - Date' ),",
              "            'Fact - Sell Out'[Order Date] < mindate,",
              "            NOT ISBLANK ( 'Fact - Sell Out'[Order Date] ),",
              "            'Fact - Sell Out'[Gross Amt] > 0            ",
              "        ),",
              "        'Fact - Sell Out'[MEMBER_WID]",
              "    )",
              "VAR current_ids =",
              "    SUMMARIZE (",
              "        CALCULATETABLE ( 'Fact - Sell Out', 'Fact - Sell Out'[Gross Amt] > 0 ),",
              "        'Fact - Sell Out'[MEMBER_WID]",
              "    )",
              "VAR temtab =",
              "    INTERSECT ( current_ids, past_ids )",
              "VAR result =",
              "    COUNTROWS ( SUMMARIZE ( temtab, [MEMBER_WID] ) )",
              "RETURN",
              "    result"
            ],
            "displayFolder": "KPI"
          },
          {
            "name": "# of Repeated Members",
            "expression": [
              " ",
              "VAR temtab =",
              "    SUMMARIZE (",
              "        CALCULATETABLE (",
              "            'Fact - Sell Out',",
              "            NOT ISBLANK ( 'Fact - Sell Out'[Order Date] ),",
              "            NOT ISBLANK ( 'Dim - Member Ths'[Member Card Code] ),",
              "            'Fact - Sell Out'[Gross Amt]>0",
              "        ),",
              "        'Dim - Member Ths'[Member Card Code],",
              "        'Fact - Sell Out'[Order Date]",
              "    )",
              "VAR temtab2 =",
              "    SUMMARIZE (",
              "        temtab,",
              "        [Member Card Code],",
              "        \"@C\", CALCULATE ( DISTINCTCOUNTNOBLANK ( 'Fact - Sell Out'[Order Date] ) )",
              "    )",
              "VAR temtab3 =",
              "    FILTER ( temtab2, [@C] >= 2 )",
              "RETURN ",
              "    COUNTROWS(temtab3)"
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "AVG Sell Out per Store",
            "expression": " DIVIDE(DIVIDE([Sell Out Amt], [# of Stores]),[Time Gone THS],BLANK())",
            "formatString": "#,0.0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "AVG Sell Out per day/ Store",
            "expression": " DIVIDE([AVG Sell Out per Store],[Total Working Day],0)",
            "displayFolder": "Sell Out"
          },
          {
            "name": "# of Inactive Members",
            "expression": [
              "",
              "VAR temtab =",
              "    SUMMARIZE (",
              "        CALCULATETABLE (",
              "            'Fact - Sell Out',",
              "            NOT ISBLANK ( 'Fact - Sell Out'[Order Date] ),",
              "            NOT ISBLANK ( 'Fact - Sell Out'[MEMBER_WID] ),",
              "            'Fact - Sell Out'[Gross Amt] > 0",
              "        ),",
              "        'Fact - Sell Out'[MEMBER_WID],",
              "        \"SO\", [Sell Out Amt]",
              "    )",
              "RETURN",
              "    COUNTROWS ( FILTER ( temtab, [SO] > 0 ) )"
            ],
            "displayFolder": "KPI"
          },
          {
            "name": "Sell Out Discount Amt",
            "expression": " SUM('Fact - Sell Out'[Discount Amt])",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Promotion Estimated Amt",
            "expression": " SUM('Fact - Sell Out'[Estimated Amt])",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Promotion Qty",
            "expression": [
              " ",
              "CALCULATE(SUM('Fact - Sell Out'[Shipped Qty]),'Fact - Sell Out'[Is Free] <> \"N\") "
            ],
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Total Promotion Amt",
            "expression": " [Sell Out Discount Amt] + [Promotion Estimated Amt]",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out True Mart Amt",
            "expression": " CALCULATE([Sell Out Amt Excl Voucher], FILTER('Dim - Channel', 'Dim - Channel'[Channel Name] <> \"ECOM\"))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out True Mart Amt LM",
            "expression": " CALCULATE([Sell Out True Mart Amt], DATEADD('Dim - Date'[Date], -1, MONTH))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out True Mart Amt MTD",
            "expression": " TOTALMTD([Sell Out True Mart Amt], 'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out True Mart Amt MTD LM",
            "expression": " CALCULATE([Sell Out True Mart Amt MTD], DATEADD('Dim - Date'[Date], -1, MONTH))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out True Mart Amt YTD",
            "expression": " TOTALYTD([Sell Out True Mart Amt], 'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out True Mart Amt YTD LY",
            "expression": " CALCULATE([Sell Out True Mart Amt YTD], DATEADD('Dim - Date'[Date], -1, YEAR))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Qty Excl Voucher",
            "expression": " CALCULATE([Sell Out Qty], FILTER('Dim - Tender', NOT ( 'Dim - Tender'[Tender Type Name] IN { \"Voucher khng tch im\", \"Voucher tch im\" })))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out True Mart Qty",
            "expression": " CALCULATE([Sell Out Qty Excl Voucher], FILTER('Dim - Channel', 'Dim - Channel'[Channel Name] <> \"ECOM\"))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "# of Bills per Member",
            "expression": " DIVIDE([# of invoices],[# of Active Members],0)",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "Sell Out Amt",
            "expression": [
              "",
              "VAR selected = SELECTEDVALUE('Selection Amt Qty'[Abb])",
              "VAR result = ",
              "SWITCH(",
              "    selected,",
              "    \"Gross Amt\", [Sell Out Gross Amt],",
              "    [Sell Out Net Amt]",
              ")",
              "RETURN result"
            ],
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "# of SKUs per Member",
            "expression": " DIVIDE([# of Unique SKUs], [# of Active Members])",
            "formatString": "#,0.00",
            "displayFolder": "KPI"
          },
          {
            "name": "# of MCP Route",
            "expression": " DISTINCTCOUNT('Fact - MCP'[Route])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Visited Route",
            "expression": " DISTINCTCOUNT('Fact - Actual Visit'[Route Code])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Invoiced Route",
            "expression": " DISTINCTCOUNT('Fact - Sell Out'[Route])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "Sell Out True Mart Net Amt",
            "expression": " CALCULATE([Sell Out Net Amt Excl Voucher], FILTER('Dim - Channel', 'Dim - Channel'[Channel Name] <> \"ECOM\"))",
            "formatString": "#,0.00",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Net Amt Excl Voucher",
            "expression": " CALCULATE([Sell Out Net Amt], FILTER('Dim - Tender', NOT ( 'Dim - Tender'[Tender Type Name] IN { \"Voucher khng tch im\", \"Voucher tch im\" })))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Min Amt Selected",
            "expression": " MIN('Amt Range'[Value])",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Max Amt Selected",
            "expression": " MAX('Amt Range'[Value])",
            "formatString": "#,0",
            "displayFolder": "Others"
          },
          {
            "name": "# of Successful Order per day",
            "expression": [
              "",
              "VAR _Ordertb =",
              "    FILTER (",
              "        SUMMARIZE (",
              "            'Fact - Sell Out',",
              "            'Dim - Date'[Date],",
              "            'Dim - Outlet'[Outlet Code],",
              "            'Fact - Sell Out'[Order Number],",
              "            'Fact - Sell Out'[Is Free]",
              "            ),",
              "        'Fact - Sell Out'[Order Number] <> \"\"",
              "            && 'Fact - Sell Out'[Is Free] = \"N\"",
              "    )",
              "VAR _SuccessOrder =",
              "    SUMMARIZE (",
              "        _Ordertb,",
              "        'Dim - Date'[Date],",
              "        'Dim - Outlet'[Outlet Code],",
              "        'Fact - Sell Out'[Order Number]",
              "    )",
              "RETURN",
              "    COUNTROWS ( _SuccessOrder )"
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "Sell Out True Mart Net Amt % vs AOP",
            "expression": " DIVIDE([Sell Out True Mart Net Amt], [Sell Out Amt AOP])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out True Mart Net Amt % vs Target",
            "expression": " DIVIDE([Sell Out True Mart Net Amt], [Sell Out Amt Target])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out True Mart Qty % vs AOP",
            "expression": " DIVIDE([Sell Out True Mart Qty], [Sell Out Qty AOP])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out True Mart Qty % vs Target",
            "expression": " DIVIDE([Sell Out True Mart Qty], [Sell Out Qty Target])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Qty Voucher",
            "expression": "  CALCULATE([Sell Out Qty]*0.03,FILTER('Dim - Tender', 'Dim - Tender'[Tender Type Name] IN { \"Voucher khng tch im\", \"Voucher tch im\" }))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out THs tnh thng QTY",
            "expression": " [Sell Out Qty Voucher]",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell out Qty 3D- Chill",
            "expression": [
              " ",
              "VAR daysbefore = 3",
              "VAR currentmindate =",
              "    MIN ( 'Dim - Date'[Date] )",
              "VAR temtab =",
              "    SUMMARIZE (",
              "        CALCULATETABLE (",
              "            'Dim - Date',",
              "            'Dim - Date'[Is Holiday THS] = \"N\",",
              "            'Dim - Date'[Date] < currentmindate",
              "        ),",
              "        'Dim - Date'[Date]",
              "    )",
              "VAR datesets =",
              "    TOPN ( daysbefore, temtab, [Date], DESC )",
              "RETURN",
              "    CALCULATE (",
              "        CALCULATE (",
              "            [Sell Out Qty],",
              "            'Dim - Product'[Category by Storage in EN] = \"Chill\"",
              "        ),",
              "        datesets",
              "    )"
            ],
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "% THs Provide Standard Stock  - Chill",
            "expression": " DIVIDE([THs Closing Stock Qty - Chill],[Sell out Qty 3D- Chill],0)",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "# of Visited Calls",
            "expression": " COUNT('Fact - Actual Visit'[Visited Plan ID])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of invoices YTD",
            "expression": " TOTALYTD([# of invoices],'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Successful Orders YTD",
            "expression": " TOTALYTD([# of Successful Orders],'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Orders YTD",
            "expression": [
              " TOTALYTD([# of Orders],'Dim - Date'[Date])",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "Monthly Frequency ASO YTD",
            "expression": [
              " TOTALYTD([Monthly Frequency ASO],'Dim - Date'[Date])",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "VPO YTD",
            "expression": " TOTALYTD([VPO],'Dim - Date'[Date])",
            "formatString": "0.00",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Calls Plan YTD",
            "expression": " TOTALYTD([# of Calls Plan],'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Order by Amt Range",
            "expression": [
              " ",
              "var _AmtSelected = 10000",
              "var _OrderValue = ADDCOLUMNS(SUMMARIZE('Fact - Sell Out', 'Fact - Sell Out'[Order Number]), \"_Amt\", [Sell Out Amt])",
              "var _OderValueHasCondition = FILTER(_OrderValue, [_Amt] >= _AmtSelected)",
              "return ",
              "COUNTROWS(_OderValueHasCondition)"
            ],
            "displayFolder": "KPI"
          },
          {
            "name": "# of Visited Calls YTD",
            "expression": " TOTALYTD([# of Visited Calls],'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of AVG Calls Plan per Day YTD",
            "expression": " TOTALYTD([# of AVG Calls Plan per Day],'Dim - Date'[Date])",
            "formatString": "0.00",
            "displayFolder": "KPI"
          },
          {
            "name": "% Strike Rate YTD",
            "expression": " TOTALYTD([% Strike Rate],'Dim - Date'[Date])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Order by Amt Range YTD",
            "expression": [
              " TOTALYTD([# of Order by Amt Range],'Dim - Date'[Date])",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Order by Qty Range YTD",
            "expression": [
              " TOTALYTD([# of Order by Qty Range],'Dim - Date'[Date])",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Unique SKUs YTD",
            "expression": " TOTALYTD([# of Unique SKUs],'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of SKUs YTD",
            "expression": " TOTALYTD([# of SKUs],'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Successful Order per day YTD",
            "expression": [
              " TOTALYTD([# of Successful Order per day],'Dim - Date'[Date])",
              ""
            ],
            "formatString": "0.00",
            "displayFolder": "KPI"
          },
          {
            "name": "# of SKUs per Successful Order YTD",
            "expression": " TOTALYTD([# of SKUs per Successful Order],'Dim - Date'[Date])",
            "formatString": "0.00",
            "displayFolder": "KPI"
          },
          {
            "name": "# of SKUs per ASO YTD",
            "expression": " TOTALYTD([# of SKUs per ASO],'Dim - Date'[Date])",
            "formatString": "0.00",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Daily ASO YTD",
            "expression": " TOTALYTD([# of Daily ASO],'Dim - Date'[Date]) ",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "DropSize YTD",
            "expression": " TOTALYTD([DropSize],'Dim - Date'[Date])",
            "formatString": "0.00",
            "displayFolder": "KPI"
          },
          {
            "name": "# of New Distributor YTD",
            "expression": " TOTALYTD([# of New Distributor],'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Distributor by Amt Range YTD",
            "expression": " TOTALYTD([# of Distributor by Amt Range],'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "#of Successful Calls YTD",
            "expression": " TOTALYTD([# of Successful Calls],'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "#of repeated ASO YTD",
            "expression": " TOTALYTD([# of Repeated ASO],'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "VPO # of Repeated ASO",
            "expression": [
              " ",
              "VAR selloutofrepeatedaso = ",
              "\tVAR temtab =",
              "\t    SUMMARIZE (",
              "\t        CALCULATETABLE (",
              "\t            'Fact - Sell Out',",
              "\t            NOT ISBLANK ( 'Fact - Sell Out'[Order Date] ),",
              "\t            NOT ISBLANK ( 'Fact - Sell Out'[Outlet ID/Member Code] ),",
              "\t            'Fact - Sell Out'[Gross Amt]>0",
              "\t        ),",
              "\t        'Fact - Sell Out'[Outlet ID/Member Code],",
              "\t        'Fact - Sell Out'[Order Date]",
              "\t    )",
              "\tVAR temtab2 =",
              "\t    SUMMARIZE (",
              "\t        temtab,",
              "\t        [Outlet ID/Member Code],",
              "\t        \"@C\", CALCULATE ( DISTINCTCOUNTNOBLANK ( 'Fact - Sell Out'[Order Date] ) )",
              "\t    )",
              "\tVAR temtab3 =",
              "\t    FILTER ( temtab2, [@C] >= 2 )",
              "\t",
              "\tVAR temtab4 = ",
              "\t    ADDCOLUMNS(temtab3,\"@amt\",[Sell Out Amt])",
              "\t",
              "\tRETURN ",
              "\t    SUMX(temtab4,[@amt])",
              "RETURN ",
              "\tDIVIDE(selloutofrepeatedaso,[# of Repeated ASO],BLANK())"
            ],
            "formatString": "0.00",
            "displayFolder": "KPI"
          },
          {
            "name": "VPO of Repurchased ASO",
            "expression": [
              "",
              "VAR selloutofrepurchaseaso = ",
              "\tVAR mindate =",
              "\t    MIN ( 'Fact - Sell Out'[Order Date] )",
              "\tVAR past_ids =",
              "\t    SUMMARIZE (",
              "\t        CALCULATETABLE (",
              "\t            'Fact - Sell Out',",
              "\t            REMOVEFILTERS ( 'Dim - Date' ),",
              "\t            'Fact - Sell Out'[Order Date] < mindate,",
              "\t            NOT ISBLANK ( 'Fact - Sell Out'[Order Date] ),",
              "\t            'Fact - Sell Out'[Gross Amt] > 0            ",
              "\t        ),",
              "\t        'Fact - Sell Out'[Outlet ID/Member Code]",
              "\t    )",
              "\tVAR current_ids =",
              "\t    SUMMARIZE (",
              "\t        CALCULATETABLE ( 'Fact - Sell Out', 'Fact - Sell Out'[Gross Amt] > 0 ),",
              "\t        'Fact - Sell Out'[Outlet ID/Member Code]",
              "\t    )",
              "\tVAR temtab =",
              "\t    INTERSECT ( current_ids, past_ids )",
              "\tVAR temtab2 =",
              "\t    ADDCOLUMNS(SUMMARIZE ( temtab, [Outlet ID/Member Code] ),\"@amt\",[Sell Out Amt])",
              "\tRETURN",
              "\t   SUMX(temtab2,[@amt])",
              "RETURN ",
              "\tDIVIDE(selloutofrepurchaseaso,[# of Repurchased ASO],BLANK())"
            ],
            "formatString": "0.00",
            "displayFolder": "KPI"
          },
          {
            "name": "% Promotion Amt / Sell out",
            "expression": " DIVIDE([Total Promotion Amt],[Sell Out Amt],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Distributor KPIs View",
            "expression": [
              " ",
              "VAR selected = SELECTEDVALUE('Distributor Views'[Value1])",
              "RETURN ",
              "SWITCH(",
              "    selected,",
              "    \"# Route\",[# of Invoiced Route],",
              "    \"ASO\",[# of ASO],",
              "    \"ASO/MCP\",[ASO/ MCP],",
              "    \"ASO/Route\",[ASO/ Route],",
              "    \"ASO_DONG LANH\",[# of ASO_ng_Lnh],",
              "    \"ASO_KHO\",[# of ASO_Kh],",
              "    \"ASO_LANH\",[# of ASO_Lnh],",
              "    \"ASO_OFF\",[# of ASO_OFF],",
              "    \"ASO_ON\",[# of ASO_ON],",
              "    \"Call/Route/day- Act\",[Actual Call/ Route/ Working Day],",
              "    \"Dropsize\",[DropSize],",
              "    \"AVG Sell Out by Month\",[AVG Sell Out by Month],",
              "    \"AVG Sell Out by Route\",[AVG Sell Out by Route],",
              "    \"SKUs/DH\",[# of SKUs per Successful Order],",
              "    \"Strike rate\",[% Strike Rate],",
              "    \"VPO\",[VPO]",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "Sell Out Discount Amt LM",
            "expression": " CALCULATE([Sell Out Discount Amt],DATEADD('Dim - Date'[Date],-1,MONTH))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Promotion Estimated Amt LM",
            "expression": " CALCULATE([Promotion Estimated Amt],DATEADD('Dim - Date'[Date],-1,MONTH))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "% Promotion Amt / Sell out LM",
            "expression": " CALCULATE([% Promotion Amt / Sell out],DATEADD('Dim - Date'[Date],-1,MONTH))",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "% Promotion Amt / Sell out LY",
            "expression": " CALCULATE([% Promotion Amt / Sell out],SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "KPI"
          },
          {
            "name": "# of ASO_ON",
            "expression": [
              "  CALCULATE(DISTINCTCOUNT('Fact - Sell Out'[Outlet ID/Member Code]), 'Fact - Sell Out'[Gross Amt] > 0,'Dim - Outlet'[Shop Location]=\"ON\")",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of ASO_OFF",
            "expression": [
              "  CALCULATE(DISTINCTCOUNT('Fact - Sell Out'[Outlet ID/Member Code]), 'Fact - Sell Out'[Gross Amt] > 0,'Dim - Outlet'[Shop Location]=\"OFF\")",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "Distributor KPIs View LM",
            "expression": " CALCULATE([Distributor KPIs View],DATEADD('Dim - Date'[Date],-1,MONTH))",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "Distributor KPIs View LY",
            "expression": " CALCULATE([Distributor KPIs View],SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "Total Promotion Amt LM",
            "expression": " CALCULATE([Total Promotion Amt],DATEADD('Dim - Date'[Date],-1,MONTH))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "VPO LM",
            "expression": " CALCULATE([VPO],DATEADD('Dim - Date'[Date],-1,MONTH))",
            "formatString": "0.00",
            "displayFolder": "KPI"
          },
          {
            "name": "Sell Out Qty per Route per day",
            "expression": " DIVIDE(DIVIDE([Sell Out Qty],[# of Invoiced Route],BLANK()),[Total Working Day NPP],BLANK())",
            "formatString": "#,0.0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Invoices per Route per day",
            "expression": " DIVIDE(DIVIDE([# of invoices],[# of Invoiced Route],BLANK()),[Total Working Day NPP],BLANK())",
            "formatString": "#,0.0",
            "displayFolder": "KPI"
          },
          {
            "name": "ASO per Route per day",
            "expression": " DIVIDE(DIVIDE([# of ASO],[# of Invoiced Route],BLANK()),[Total Working Day NPP],BLANK())",
            "formatString": "#,0.0",
            "displayFolder": "KPI"
          },
          {
            "name": "Refreshed Date",
            "expression": " CALCULATE(MAX('Fact - Sell Out'[Invoice Date]),REMOVEFILTERS())",
            "formatString": "Short Date",
            "displayFolder": "Others",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Today",
            "expression": " TODAY()",
            "formatString": "Short Date",
            "displayFolder": "Others",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Sell Out Amt Order",
            "expression": [
              " ",
              "VAR grossamt = SUM('Fact - Order Detail'[Gross Amt])",
              "VAR netamt = SUM('Fact - Order Detail'[Net Amt])",
              "VAR selected = SELECTEDVALUE('Selection Amt Qty'[Abb])",
              "RETURN ",
              "SWITCH(",
              "selected,",
              "\"Gross Amt\",grossamt,",
              "\"Net Amt\",netamt,",
              "netamt",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt/Qty",
            "expression": [
              " ",
              "VAR selected = SELECTEDVALUE('Selection Amt Qty'[Abb])",
              "VAR carton = SUM('Fact - Sell Out'[Carton Shipped Qty])",
              "var kg = SUMX('Fact - Sell Out','Fact - Sell Out'[Shipped Qty] * 'Fact - Sell Out'[Convert Rate to Gram]/1000)",
              "VAR result = ",
              "SWITCH(",
              "    selected,",
              "    \"Amt (+VAT)\", [Sell Out Gross Amt],",
              "    \"Amt (-VAT)\", [Sell Out Net Amt],",
              "    \"Qty - Carton\", carton,",
              "    \"Qty - Kg\", kg",
              ")",
              "RETURN result"
            ],
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Order Amt/Qty",
            "expression": [
              " ",
              "VAR SelectedAmtQty = SELECTEDVALUE('Selection Amt Qty'[Abb])",
              "RETURN ",
              "SWITCH(",
              "    SelectedAmtQty,",
              "    \"Amt\",[Sell Out Amt Order],",
              "    \"Qty\",[Sell Out Qty Order]",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Qty Order",
            "expression": [
              " SUM('Fact - Order Detail'[Shiped Qty])",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out AOP/Target",
            "expression": [
              " ",
              "",
              "VAR AmtAOP = [Sell Out Amt AOP]",
              "VAR AmtTarget = [Sell Out Amt Target]",
              "VAR AmtAopRev = [Sell Out Amt AOP Revised]",
              "VAR QtyAOP = [Sell Out Qty AOP]",
              "VAR QtyTarget = [Sell Out Qty Target]",
              "VAR QtyAopRev = [Sell Out Qty AOP Revised]",
              "VAR SelectedAOPTarget =",
              "    SELECTEDVALUE ( 'Selection AOP Target'[Value] )",
              "VAR SelectedAmtQty =",
              "    SELECTEDVALUE ( 'Selection Amt Qty'[Abb] )",
              "VAR SoAOPTargetAmt =",
              "    SWITCH ( SelectedAOPTarget, \"AOP\", AmtAOP, \"Target\", AmtTarget,AmtAopRev)",
              "VAR SoAOPTargetQty =",
              "    SWITCH ( SelectedAOPTarget, \"AOP\", QtyAOP, \"Target\", QtyTarget ,QtyAopRev)",
              "RETURN",
              "    SWITCH ( SelectedAmtQty, ",
              "    \"Amt (+VAT)\", SoAOPTargetAmt,",
              "    \"Amt (-VAT)\", SoAOPTargetAmt,",
              "     \"Qty - Carton\", SoAOPTargetQty,",
              "     \"Qty - Kg\", SoAOPTargetQty",
              "      )"
            ],
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Icon for Sell Out Amt vs LM",
            "expression": [
              " ",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            [Sell Out Amt Growth % vs LM] > 0, UNICHAR ( 9650 ),",
              "            [Sell Out Amt Growth % vs LM] < 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLM =",
              "        FORMAT ( ABS ( [Sell Out Amt Growth % vs LM] ), \"#%\" )",
              "    RETURN",
              "        \"vs LM: \" & icon & growthvsLM",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "Icon for Sell Out Qty vs LM",
            "expression": [
              " ",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            [Sell Out Qty Growth % vs LM] > 0, UNICHAR ( 9650 ),",
              "            [Sell Out Qty Growth % vs LM] < 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLM =",
              "        FORMAT ( ABS ( [Sell Out Qty Growth % vs LM] ), \"#%\" )",
              "    RETURN",
              "        \"vs LM: \" & icon & growthvsLM",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "Icon for Sell Out Amt vs LY",
            "expression": [
              " ",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            [Sell Out Amt Growth % vs LY] > 0, UNICHAR ( 9650 ),",
              "            [Sell Out Amt Growth % vs LY] < 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLY =",
              "        FORMAT ( ABS ( [Sell Out Amt Growth % vs LY] ), \"#%\" )",
              "    RETURN",
              "        \"vs LY: \" & icon & growthvsLY",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "Icon for Sell Out Qty vs LY",
            "expression": [
              " ",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            [Sell Out Qty Growth % vs LY] > 0, UNICHAR ( 9650 ),",
              "            [Sell Out Qty Growth % vs LY] < 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLY =",
              "        FORMAT ( ABS ( [Sell Out Qty Growth % vs LY] ), \"#%\" )",
              "    RETURN",
              "        \"vs LY: \" & icon & growthvsLY",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "Sell Out % vs AOP/Target",
            "expression": [
              " ",
              "VAR soamtqty = [Sell Out Amt/Qty]",
              "VAR soaoptarget = [Sell Out AOP/Target]",
              "VAR temp = DIVIDE(soamtqty,soaoptarget,0)",
              "RETURN temp"
            ],
            "formatString": "#,0.0%;-#,0.0%;#,0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Icon for SO vs AOP/Target",
            "expression": [
              " ",
              "VAR number = [Sell Out % vs AOP/Target]",
              "VAR icon =",
              "    SWITCH ( TRUE (), number >= 0.8, UNICHAR ( 128504 ), UNICHAR ( 128500 ) )",
              "RETURN",
              "    icon & \" \"",
              "        & FORMAT ( [Sell Out % vs AOP/Target], \"#%\" )"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "Icon for ASO vs LM",
            "expression": [
              " ",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            [ASO Growth % vs LM] > 0, UNICHAR ( 9650 ),",
              "            [ASO Growth % vs LM] < 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLM =",
              "        FORMAT ( ABS ( [ASO Growth % vs LM] ), \"#%\" )",
              "    RETURN",
              "        \"vs LM: \" & icon & growthvsLM",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "Icon for ASO vs LY",
            "expression": [
              " ",
              "",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            [ASO Growth % vs LY] > 0, UNICHAR ( 9650 ),",
              "            [ASO Growth % vs LY] < 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLY =",
              "        FORMAT ( ABS ( [ASO Growth % vs LY] ), \"#%\" )",
              "    RETURN",
              "        \"vs LY: \" & icon & growthvsLY",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "% New ASO / ASO",
            "expression": " DIVIDE([# of New ASO],[# of ASO],0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "KPI"
          },
          {
            "name": "Sell Out Gross Amt",
            "expression": [
              "",
              "CALCULATE (",
              "    SUM ( 'Fact - Sell Out'[Gross Amt] ),",
              "    'Fact - Sell Out',",
              "    'Fact - Sell Out'[Is Free] = \"N\",",
              "    'Fact - Sell Out'[Shipped Qty] <> 0,",
              "    'Dim - Product'[Is POSM] = \"N\",",
              "    KEEPFILTERS ( 'Fact - Sell Out' )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt/Qty MTD",
            "expression": [
              " ",
              "TOTALMTD([Sell Out Amt/Qty],'Dim - Date'[Date])"
            ],
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt/Qty YTD",
            "expression": [
              " ",
              "TOTALYTD([Sell Out Amt/Qty],'Dim - Date'[Date])"
            ],
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt/Qty MTD LM",
            "expression": [
              " ",
              "CALCULATE([Sell Out Amt/Qty MTD],DATEADD('Dim - Date'[Date],-1,MONTH))"
            ],
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt/Qty YTD LY",
            "expression": [
              " ",
              "CALCULATE([Sell Out Amt/Qty YTD],SAMEPERIODLASTYEAR('Dim - Date'[Date]))"
            ],
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt/Qty Growth % vs LM",
            "expression": " IF(ISBLANK(DIVIDE([Sell Out Amt/Qty], [Sell Out Amt/Qty LM])), BLANK(), DIVIDE([Sell Out Amt/Qty], [Sell Out Amt/Qty LM]) - 1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt/Qty LM",
            "expression": " CALCULATE([Sell Out Amt/Qty],DATEADD('Dim - Date'[Date],-1,MONTH))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt/Qty LY",
            "expression": " CALCULATE([Sell Out Amt/Qty],SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt/Qty Growth % vs LY",
            "expression": [
              " ",
              "VAR numberforpastmonth = DIVIDE([Sell Out Amt/Qty], CALCULATE([Sell Out Amt/Qty],SAMEPERIODLASTYEAR('Dim - Date'[Date])),BLANK())",
              "VAR numberforcurrentmonth = DIVIDE([Sell Out Amt/Qty MTD], CALCULATE([Sell Out Amt/Qty MTD],SAMEPERIODLASTYEAR('Dim - Date'[Date])),BLANK())",
              "VAR numberforalldateselected = DIVIDE([Sell Out Amt/Qty YTD], CALCULATE([Sell Out Amt/Qty YTD],SAMEPERIODLASTYEAR('Dim - Date'[Date])),BLANK())",
              "VAR result = ",
              "SWITCH(",
              "\tTRUE(),",
              "\tNOT ISFILTERED('Dim - Date'[Month]),numberforalldateselected,",
              "\t[Time Gone THS]=1,numberforpastmonth,",
              "\t[Time Gone THS]<>1,numberforcurrentmonth)",
              "RETURN ",
              "IF(ISBLANK(result), BLANK(),result- 1)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Icon for Sell Out Amt/Qty vs LM",
            "expression": [
              " ",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            [Sell Out Amt/Qty Growth % vs LM] > 0, UNICHAR ( 9650 ),",
              "            [Sell Out Amt/Qty Growth % vs LM] < 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLM =",
              "        FORMAT ( ABS ( [Sell Out Amt/Qty Growth % vs LM] ), \"#%\" )",
              "    RETURN",
              "        \"vs LM: \" & icon & growthvsLM",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "Icon for Sell Out Amt/Qty vs LY",
            "expression": [
              " ",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            [Sell Out Amt/Qty Growth % vs LY] > 0, UNICHAR ( 9650 ),",
              "            [Sell Out Amt/Qty Growth % vs LY] < 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLY =",
              "        FORMAT ( ABS ( [Sell Out Amt/Qty Growth % vs LY] ), \"#%\" )",
              "    RETURN",
              "        \"vs LY: \" & icon & growthvsLY",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "Sell Out /Salesman/ Month",
            "expression": [
              " ",
              "var SOAM = [Sell Out Amt]",
              "VAR salesman = CALCULATE(DISTINCTCOUNT('Dim - Sales Force'[Employee Code]),'Fact - Sell Out'[Gross Amt]>0)",
              "VAR selectedmonths = COUNTROWS(SUMMARIZE('Dim - Date','Dim - Date'[Month],'Dim - Date'[Year]))",
              "RETURN DIVIDE(DIVIDE(SOAM,salesman,0),selectedmonths,0)"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "To Show VPO",
            "expression": [
              " ",
              "var selected = SELECTEDVALUE('Selection ASO VPO'[Value])",
              "var vpo = [VPO]",
              "var rpuaso = [VPO of Repurchased ASO]",
              "var rptaso = [VPO # of Repeated ASO]",
              "VAR RESULT = ",
              "SWITCH(",
              "    selected,",
              "    \"# of ASO\",vpo,",
              "    \"# of Repurchase ASO\",rpuaso,",
              "    \"# of Repeated ASO\",rptaso",
              ")",
              "RETURN RESULT"
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "To Show ASO",
            "expression": [
              " ",
              "var selected = SELECTEDVALUE('Selection ASO VPO'[Value])",
              "VAR ASO = [# of ASO]",
              "VAR NEWASO = [# of New ASO]",
              "VAR RPUASO = [# of Repurchased ASO]",
              "VAR RPTASO = [# of Repeated ASO]",
              "VAR RESULT = ",
              "SWITCH(",
              "    selected,",
              "    \"# of ASO\",ASO,",
              "    \"# of New ASO\", NEWASO,",
              "    \"# of Repurchase ASO\",RPUASO,",
              "    \"# of Repeated ASO\",RPTASO",
              ")",
              "RETURN RESULT"
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "AVG Sell Out by Route",
            "expression": " DIVIDE([Sell Out Amt/Qty],DISTINCTCOUNTNOBLANK('Fact - Sell Out'[Route]),BLANK())",
            "formatString": "#,0.0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "AVG Sell Out by Month",
            "expression": [
              "",
              "VAR temtab1 =",
              "    SUMMARIZE (",
              "        'Fact - Sell Out',",
              "        'Dim - Date'[Month],",
              "        'Dim - Date'[Year],",
              "        \"@amt\", [Sell Out Amt/Qty]",
              "    )",
              "VAR temtab2 =",
              "    FILTER ( temtab1, [@amt] > 0 )",
              "VAR totalsellout =",
              "    AVERAGEX ( temtab2, [@amt] )",
              "RETURN",
              "    IF ( NOT ( ISFILTERED ( 'Dim - Date' ) ), BLANK (), totalsellout )"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Call Plan / MCP Route",
            "expression": " DIVIDE([# of Calls Plan],[# of MCP Route],BLANK())",
            "formatString": "#,0.0",
            "displayFolder": "KPI"
          },
          {
            "name": "Visited Calls / Actual Route",
            "expression": " DIVIDE([# of Visited Calls],[# of Visited Route],BLANK())",
            "formatString": "#,0.0",
            "displayFolder": "KPI"
          },
          {
            "name": "Successful Calls / Actual Route",
            "expression": " DIVIDE([# of Successful Calls],[# of Visited Route],BLANK())",
            "formatString": "#,0.0",
            "displayFolder": "KPI"
          },
          {
            "name": "AVG Sell Out Rolling n-month",
            "expression": [
              "",
              "var _numperiod = MAX('Dim - Date'[Month Number])*(-1)",
              "return ",
              "CALCULATE([AVG Sell Out per Store], DATESINPERIOD('Dim - Date'[Date], EOMONTH(MAX('Dim - Date'[Date]),0), _numperiod, MONTH))"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt Rolling n-month",
            "expression": [
              "",
              "var _numperiod = MAX('Dim - Date'[Month Number])*(-1)",
              "return ",
              "CALCULATE([Sell Out Amt], DATESINPERIOD('Dim - Date'[Date], MAX('Dim - Date'[Date]), _numperiod, MONTH))"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt Growth % vs LM Rolling n-month",
            "expression": [
              "",
              "var _numperiod = MAX('Dim - Date'[Month Number])*(-1)",
              "return ",
              "CALCULATE([Sell Out Amt Growth % vs LM], DATESINPERIOD('Dim - Date'[Date], MAX('Dim - Date'[Date]), _numperiod, MONTH))"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "# Members Show Report",
            "expression": [
              " ",
              "var selected = SELECTEDVALUE('Selection Members'[Value])",
              "var _numperiod = max('Dim - Date'[Month Number]) *(-1)",
              "VAR RESULT = ",
              "SWITCH(",
              "    selected,",
              "    \"# of Active Members\", CALCULATE([# of Active Members],DATESINPERIOD('Dim - Date'[Date], MAX('Dim - Date'[Date]), _numperiod, MONTH)),\t",
              "    \"# of New Members\", CALCULATE( [# of New Members],DATESINPERIOD('Dim - Date'[Date], MAX('Dim - Date'[Date]), _numperiod, MONTH)),\t",
              "    \"# of Repurchased Members\",CALCULATE([# of Repurchased Members],DATESINPERIOD('Dim - Date'[Date], MAX('Dim - Date'[Date]), _numperiod, MONTH)),\t",
              "    \"# of Repeated Members\",CALCULATE([# of Repeated Members],DATESINPERIOD('Dim - Date'[Date], MAX('Dim - Date'[Date]), _numperiod, MONTH)),\t",
              "    \"# of Inactive Members\",CALCULATE([# of Inactive Members] ,DATESINPERIOD('Dim - Date'[Date], MAX('Dim - Date'[Date]), _numperiod, MONTH))\t",
              ")",
              "RETURN RESULT"
            ],
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "Bills/Days/Store",
            "expression": " DIVIDE(DIVIDE([# of invoices],[Total Working Day THS],0),[# of Stores],0)",
            "formatString": "#,0.00",
            "displayFolder": "KPI"
          },
          {
            "name": "# Total Distributor",
            "expression": " DISTINCTCOUNTNOBLANK('Dim - Distributor'[Distributor Code])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "Sell Out Net Amt ASO Asset",
            "expression": " SUM('Fact - POSM Assignment'[NET_AMT])",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Net Amt ASO Asset LM",
            "expression": " CALCULATE([Sell Out Net Amt ASO Asset],DATEADD('Dim - Date'[Date],-1,MONTH))",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Net Amt ASO Asset Growth % vs LM",
            "expression": " IF(ISBLANK(DIVIDE([Sell Out Net Amt ASO Asset], [Sell Out Net Amt ASO Asset LM])), BLANK(), DIVIDE([Sell Out Net Amt ASO Asset], [Sell Out Net Amt ASO Asset LM]) - 1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "# of ASO Asset",
            "expression": " DISTINCTCOUNTNOBLANK('Fact - POSM Assignment'[OUTLET_CODE])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of ASO Asset LM",
            "expression": " CALCULATE([# of ASO Asset],DATEADD('Dim - Date'[Date],-1,MONTH))",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of ASO Asset Growth % vs LM",
            "expression": " IF(ISBLANK(DIVIDE([# of ASO Asset], [# of ASO Asset LM])), BLANK(), DIVIDE([# of ASO Asset], [# of ASO Asset LM]) - 1)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "KPI"
          },
          {
            "name": "SKUs / ASO Asset",
            "expression": " DIVIDE([# of SKUs],[# of ASO Asset],BLANK())",
            "formatString": "0.0",
            "displayFolder": "KPI"
          },
          {
            "name": "Sell Out Net Amt ASO Asset / Sell Out Net Amt",
            "expression": " DIVIDE([Sell Out Net Amt ASO Asset],[Sell Out Net Amt],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Net Amt ASO Asset LM/ Sell Out Net Amt LM",
            "expression": " DIVIDE([Sell Out Net Amt ASO Asset LM],CALCULATE([Sell Out Net Amt],DATEADD('Dim - Date'[Date],-1,MONTH)),BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "# ASO Assets/# ASO",
            "expression": " DIVIDE([# of ASO Asset],[# of ASO],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "KPI"
          },
          {
            "name": "Icon for Stores vs LM",
            "expression": [
              " ",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            [Store Growth % vs LM] > 0, UNICHAR ( 9650 ),",
              "            [Store Growth % vs LM] < 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLM =",
              "        FORMAT ( ABS ( [Store Growth % vs LM] ), \"#%\" )",
              "    RETURN",
              "        \"vs LM: \" & icon & growthvsLM",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "Icon for Stores vs LY",
            "expression": [
              " ",
              "",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            [Store Growth % vs LY] > 0, UNICHAR ( 9650 ),",
              "           [Store Growth % vs LY] < 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLY =",
              "        FORMAT ( ABS ([Store Growth % vs LY] ), \"#%\" )",
              "    RETURN",
              "        \"vs LY: \" & icon & growthvsLY",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "% New Stores / Stores",
            "expression": " DIVIDE([# of New Stores],[# of Stores],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "KPI"
          },
          {
            "name": "Product Invoices/ Total Invoices",
            "expression": [
              " ",
              "VAR TotalInvoice =",
              "    CALCULATE ( [# of invoices], REMOVEFILTERS ( 'Dim - Product' ) )",
              "RETURN",
              "    DIVIDE ( [# of invoices], TotalInvoice, 0 )"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "KPI"
          },
          {
            "name": "Club Sell Out Growth % vs LM",
            "expression": " IF(ISBLANK(DIVIDE([Club Sell Out Amt], [Club Sell Out Amt LM])), BLANK(), DIVIDE([Club Sell Out Amt], [Club Sell Out Amt LM]) - 1)",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Club ASO Active Growth % vs LM",
            "expression": " IF(ISBLANK(DIVIDE([# of Club ASO Active], [# of Club ASO Active LM])), BLANK(), DIVIDE([# of Club ASO Active], [# of Club ASO Active LM]) - 1)",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Sell Out AOP/Target YTD",
            "expression": " TOTALYTD([Sell Out AOP/Target],'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Icon for Sell Out Amt/Qty vs YTD LY",
            "expression": [
              " ",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            [Sell Out Amt/Qty YTD Growth % vs LY YTD] > 0, UNICHAR ( 9650 ),",
              "            [Sell Out Amt/Qty YTD Growth % vs LY YTD] < 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLY =",
              "        FORMAT ( ABS ([Sell Out Amt/Qty YTD Growth % vs LY YTD] ), \"#%\" )",
              "    RETURN",
              "        \"vs LY: \" & icon & growthvsLY",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "Sell Out Amt/Qty YTD Growth % vs LM YTD",
            "expression": [
              "",
              "var amtytdlm = CALCULATE([Sell Out Amt/Qty YTD],DATEADD('Dim - Date'[Date],-1,MONTH))",
              "RETURN IF (",
              "    ISBLANK ( DIVIDE ( [Sell Out Amt/Qty YTD], amtytdlm ) ),",
              "    BLANK (),",
              "    DIVIDE ( [Sell Out Amt/Qty YTD],amtytdlm) - 1",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Icon for Sell Out Amt/Qty vs YTD LM",
            "expression": [
              " ",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            [Sell Out Amt/Qty YTD Growth % vs LM YTD] > 0, UNICHAR ( 9650 ),",
              "            [Sell Out Amt/Qty YTD Growth % vs LM YTD] < 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLY =",
              "        FORMAT ( ABS ([Sell Out Amt/Qty YTD Growth % vs LM YTD] ), \"#%\" )",
              "    RETURN",
              "        \"vs LY: \" & icon & growthvsLY",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "# of Stores YTD LM",
            "expression": " CALCULATE([# of Stores YTD], DATEADD('Dim - Date'[Date],-1,MONTH))",
            "displayFolder": "KPI"
          },
          {
            "name": "# of New Stores YTD",
            "expression": " TOTALYTD([# of New Stores],'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "% New Stores / Stores YTD",
            "expression": " DIVIDE([# of New Stores YTD],[# of Stores YTD],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "KPI"
          },
          {
            "name": "# Store YTD Growth % vs LM YTD",
            "expression": [
              "",
              "var amtytdlm = CALCULATE([# of Stores YTD],DATEADD('Dim - Date'[Date],-1,MONTH))",
              "RETURN IF (",
              "    ISBLANK ( DIVIDE ( [# of Stores YTD], amtytdlm ) ),",
              "    BLANK (),",
              "    DIVIDE ( [# of Stores YTD],amtytdlm) - 1",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "KPI"
          },
          {
            "name": "Icon for # of Stores Growth % vs YTD LY",
            "expression": [
              " ",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            [# Store YTD Growth % vs YTD LY] > 0, UNICHAR ( 9650 ),",
              "            [# Store YTD Growth % vs YTD LY]< 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLY =",
              "        FORMAT ( ABS ([# Store YTD Growth % vs YTD LY] ), \"#%\" )",
              "    RETURN",
              "        \"vs LY: \" & icon & growthvsLY",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "Icon for # of Stores Growth % vs YTD LM",
            "expression": [
              " ",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            [# Store YTD Growth % vs LM YTD] > 0, UNICHAR ( 9650 ),",
              "            [# Store YTD Growth % vs LM YTD]< 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLY =",
              "        FORMAT ( ABS ([# Store YTD Growth % vs Lm YTD] ), \"#%\" )",
              "    RETURN",
              "        \"vs LM: \" & icon & growthvsLY",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "Bills/Days/Store YTD",
            "expression": " TOTALYTD([Bills/Days/Store],'Dim - Date'[Date])",
            "formatString": "0.00",
            "displayFolder": "KPI"
          },
          {
            "name": "SKU Per Bill YTD",
            "expression": " TOTALYTD([# of SKU per Bill],'Dim - Date'[Date])",
            "formatString": "0.0",
            "displayFolder": "KPI"
          },
          {
            "name": "AVG Sell Out per Store YTD",
            "expression": "TOTALYTD([AVG Sell Out per Store],'Dim - Date'[Date])",
            "formatString": "0.0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "# of Active Members YTD",
            "expression": "TOTALYTD([# of Active Members],'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "AVG Sell Out Amt/Qty",
            "expression": " AVERAGEX('Dim - Date',[Sell Out Amt/Qty])",
            "formatString": "#,0.0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "AVG Invoices",
            "expression": "  AVERAGEX('Dim - Date',[# of invoices])",
            "formatString": "#,0.0",
            "displayFolder": "KPI"
          },
          {
            "name": "Sell Out % vs AOP/Target YTD",
            "expression": [
              " ",
              "VAR soamtqty = [Sell Out Amt/Qty YTD]",
              "VAR soaoptarget = [Sell Out AOP/Target YTD]",
              "VAR temp = DIVIDE(soamtqty,soaoptarget,0)",
              "RETURN temp"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Icon for SO vs AOP/Target YTD",
            "expression": [
              " ",
              "VAR number = [Sell Out % vs AOP/Target YTD]",
              "VAR icon =",
              "    SWITCH ( TRUE (), number >= 0.8, UNICHAR ( 128504 ), UNICHAR ( 128500 ) )",
              "RETURN",
              "    icon & \" \"",
              "        & FORMAT ( [Sell Out % vs AOP/Target YTD], \"#%\" )"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "Sell Out Amt MTD Growth % vs MTD LM",
            "expression": [
              "",
              "IF (",
              "    ISBLANK ( DIVIDE ( [Sell Out Amt MTD], [Sell Out Amt MTD LM] ) ),",
              "    BLANK (),",
              "    DIVIDE ( [Sell Out Amt MTD], [Sell Out Amt MTD LM] ) - 1",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt YTD Growth % vs YTD LY",
            "expression": [
              "",
              "IF (",
              "    ISBLANK ( DIVIDE ( [Sell Out Amt YTD], [Sell Out Amt YTD LY] ) ),",
              "    BLANK (),",
              "    DIVIDE ( [Sell Out Amt YTD], [Sell Out Amt YTD LY] ) - 1",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "# Store YTD Growth % vs YTD LY",
            "expression": [
              "",
              "var amtytdlY = CALCULATE([# of Stores YTD],SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
              "RETURN IF (",
              "    ISBLANK ( DIVIDE ( [# of Stores YTD], amtytdlY ) ),",
              "    BLANK (),",
              "    DIVIDE ( [# of Stores YTD],amtytdlY) - 1",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "KPI"
          },
          {
            "name": "Sell Out AOP/Target MTD",
            "expression": " TOTALMTD([Sell Out AOP/Target],'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt/Qty MTD Growth % vs MTD LY",
            "expression": [
              "",
              "var MTDLY = CALCULATE([Sell Out Amt/Qty MTD],SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
              "return IF (",
              "    ISBLANK ( DIVIDE ( [Sell Out Amt/Qty MTD], MTDLY ) ),",
              "    BLANK (),",
              "    DIVIDE ( [Sell Out Amt/Qty MTD],MTDLY  ) - 1",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Icon for Sell Out Amt/Qty vs MTD LM",
            "expression": [
              " ",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            [Sell Out Amt/Qty MTD Growth % vs LM MTD] > 0, UNICHAR ( 9650 ),",
              "            [Sell Out Amt/Qty MTD Growth % vs LM MTD] < 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLY =",
              "        FORMAT ( ABS ( [Sell Out Amt/Qty MTD Growth % vs LM MTD]), \"#%\" )",
              "    RETURN",
              "        \"vs LM: \" & icon & growthvsLY",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "Icon for Sell Out Amt/Qty vs MTD LY",
            "expression": [
              " ",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            [Sell Out Amt/Qty MTD Growth % vs MTD LY]> 0, UNICHAR ( 9650 ),",
              "            [Sell Out Amt/Qty MTD Growth % vs MTD LY] < 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLY =",
              "        FORMAT ( ABS ([Sell Out Amt/Qty MTD Growth % vs MTD LY] ), \"#%\" )",
              "    RETURN",
              "        \"vs LY: \" & icon & growthvsLY",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "Sell Out Amt/Qty MTD Growth % vs LM MTD",
            "expression": [
              "",
              "IF (",
              "    ISBLANK ( DIVIDE ( [Sell Out Amt/Qty MTD], [Sell Out Amt/Qty MTD LM] ) ),",
              "    BLANK (),",
              "    DIVIDE ( [Sell Out Amt/Qty MTD], [Sell Out Amt/Qty MTD LM]  ) - 1",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Amt/Qty YTD Growth % vs LY YTD",
            "expression": [
              "",
              "IF (",
              "    ISBLANK ( DIVIDE ( [Sell Out Amt/Qty YTD], [Sell Out Amt/Qty YTD LY] ) ),",
              "    BLANK (),",
              "    DIVIDE ( [Sell Out Amt/Qty YTD], [Sell Out Amt/Qty YTD LY] ) - 1",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out % vs AOP/Target MTD",
            "expression": [
              " ",
              "VAR soamtqty = [Sell Out Amt/Qty MTD]",
              "VAR soaoptarget = [Sell Out AOP/Target MTD]",
              "VAR temp = DIVIDE(soamtqty,soaoptarget,0)",
              "RETURN temp"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Icon for SO vs AOP/Target MTD",
            "expression": [
              " ",
              "VAR number = [Sell Out % vs AOP/Target MTD]",
              "VAR icon =",
              "    SWITCH ( TRUE (), number >= 0.8, UNICHAR ( 128504 ), UNICHAR ( 128500 ) )",
              "RETURN",
              "    icon & \" \"",
              "        & FORMAT ( [Sell Out % vs AOP/Target MTD], \"#%\" )"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "# of Stores MTD LY",
            "expression": " CALCULATE([# of Stores MTD],SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# Store MTD Growth % vs MTD LY",
            "expression": [
              "",
              "var amtmtdlY = CALCULATE([# of Stores MTD],SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
              "RETURN IF (",
              "    ISBLANK ( DIVIDE ( [# of Stores MTD], amtmtdlY ) ),",
              "    BLANK (),",
              "    DIVIDE ( [# of Stores MTD],amtmtdlY) - 1",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "KPI"
          },
          {
            "name": "# Store MTD Growth % vs MTD LM",
            "expression": [
              "",
              "var amtmtdlY = CALCULATE([# of Stores MTD],SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
              "RETURN IF (",
              "    ISBLANK ( DIVIDE ( [# of Stores MTD], [# of Stores MTD LM] ) ),",
              "    BLANK (),",
              "    DIVIDE ( [# of Stores MTD], [# of Stores MTD LM] ) - 1",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "KPI"
          },
          {
            "name": "Icon for # of Stores Growth % vs MTD LY",
            "expression": [
              " ",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            [# Store MTD Growth % vs MTD LY] > 0, UNICHAR ( 9650 ),",
              "            [# Store MTD Growth % vs MTD LY] < 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLY =",
              "        FORMAT ( ABS ( [# Store MTD Growth % vs MTD LY] ), \"#%\" )",
              "    RETURN",
              "        \"vs LY: \" & icon & growthvsLY",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "Icon for # of Stores Growth % vs MTD LM",
            "expression": [
              " ",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            [# Store MTD Growth % vs MTD LM] > 0, UNICHAR ( 9650 ),",
              "            [# Store MTD Growth % vs MTD LM]< 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLY =",
              "        FORMAT ( ABS ([# Store MTD Growth % vs MTD LM] ), \"#%\" )",
              "    RETURN",
              "        \"vs LM: \" & icon & growthvsLY",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "# of New Stores MTD",
            "expression": " TOTALMTD([# of New Stores],'Dim - Date'[Date])",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "% New Stores / Stores MTD",
            "expression": " DIVIDE([# of New Stores MTD],[# of Stores MTD],BLANK())",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "KPI"
          },
          {
            "name": "VPO MTD",
            "expression": " TOTALMTD([VPO],'Dim - Date'[Date])",
            "formatString": "0.0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of New Distributor MTD",
            "expression": " TOTALMTD([# of New Distributor],'Dim - Date'[Date])",
            "displayFolder": "KPI"
          },
          {
            "name": "# ASO MTD Growth % vs MTD LM",
            "expression": [
              "",
              "var amt = CALCULATE([# of ASO MTD],DATEADD('Dim - Date'[Date],-1,MONTH))",
              "RETURN IF (",
              "    ISBLANK ( DIVIDE ([# of ASO MTD],[# of ASO MTD LM] ) ),",
              "    BLANK (),",
              "    DIVIDE ([# of ASO MTD],[# of ASO MTD LM] ) - 1",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "KPI"
          },
          {
            "name": "# ASO MTD Growth % vs MTD LY",
            "expression": [
              "",
              "var amt = CALCULATE([# of ASO MTD],SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
              "RETURN IF (",
              "    ISBLANK ( DIVIDE ([# of ASO MTD],amt ) ),",
              "    BLANK (),",
              "    DIVIDE ([# of ASO MTD],amt) - 1",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "KPI"
          },
          {
            "name": "# ASO YTD Growth % vs YTD LM",
            "expression": [
              "",
              "var amt = CALCULATE([# of ASO YTD],DATEADD('Dim - Date'[Date],-1,MONTH))",
              "RETURN IF (",
              "    ISBLANK ( DIVIDE ([# of ASO YTD],AMT) ),",
              "    BLANK (),",
              "    DIVIDE ([# of ASO YTD],AMT ) - 1",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "KPI"
          },
          {
            "name": "# ASO YTD Growth % vs YTD LY",
            "expression": [
              "",
              "var amt = CALCULATE([# of ASO YTD],SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
              "RETURN IF (",
              "    ISBLANK ( DIVIDE ([# of ASO YTD],AMT) ),",
              "    BLANK (),",
              "    DIVIDE ([# of ASO YTD],AMT ) - 1",
              ")"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "KPI"
          },
          {
            "name": "Icon for # of ASO Growth % vs MTD LM",
            "expression": [
              " ",
              "VAR number = [# ASO MTD Growth % vs MTD LM]",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            number > 0, UNICHAR ( 9650 ),",
              "            number< 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLY =",
              "        FORMAT ( ABS (number ), \"#%\" )",
              "    RETURN",
              "        \"vs LM: \" & icon & growthvsLY",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "Icon for # of ASO Growth % vs MTD LY",
            "expression": [
              " ",
              "VAR number = [# ASO MTD Growth % vs MTD LY]",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            number > 0, UNICHAR ( 9650 ),",
              "            number< 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLY =",
              "        FORMAT ( ABS (number ), \"#%\" )",
              "    RETURN",
              "        \"vs LY: \" & icon & growthvsLY",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "Icon for # of ASO Growth % vs YTD LM",
            "expression": [
              " ",
              "VAR number = [# ASO YTD Growth % vs YTD LM]",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            number > 0, UNICHAR ( 9650 ),",
              "            number< 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLY =",
              "        FORMAT ( ABS (number ), \"#%\" )",
              "    RETURN",
              "        \"vs LM: \" & icon & growthvsLY",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "Icon for # of ASO Growth % vs YTD LY",
            "expression": [
              " ",
              "VAR number = [# ASO YTD Growth % vs YTD LY]",
              "VAR result =",
              "    VAR icon =",
              "        SWITCH (",
              "            TRUE (),",
              "            number > 0, UNICHAR ( 9650 ),",
              "            number< 0, UNICHAR ( 9660 ),",
              "            UNICHAR ( 9632 )",
              "        )",
              "    VAR growthvsLY =",
              "        FORMAT ( ABS (number ), \"#%\" )",
              "    RETURN",
              "        \"vs LM: \" & icon & growthvsLY",
              "",
              "RETURN",
              "    result"
            ],
            "displayFolder": "Others"
          },
          {
            "name": "% New ASO / ASO MTD",
            "expression": " DIVIDE([# of New ASO MTD],[# of ASO MTD],0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "KPI"
          },
          {
            "name": "% New ASO / ASO YTD",
            "expression": " DIVIDE([# of New ASO YTD],[# of ASO YTD],0)",
            "formatString": "0.0%;-0.0%;0.0%",
            "displayFolder": "KPI"
          },
          {
            "name": "# of Active Stores by AMT Range",
            "expression": " CALCULATE(DISTINCTCOUNT('Fact - Sell Out'[Store Code]),'Fact - Sell Out'[Gross Amt]>0,USERELATIONSHIP('Dim - Store Amt Range'[RANGE_WID],'Fact - Sell Out'[STORE_AMT_RANGE_WID]))",
            "formatString": "#,0"
          },
          {
            "name": "AVG Sell Out /Store/ Month",
            "expression": [
              " ",
              "VAR temtab1 =",
              "    SUMMARIZE (",
              "        'Fact - Sell Out',",
              "        'Dim - Date'[Month],",
              "        'Dim - Store'[Store Code],",
              "        'Dim - Date'[Year],",
              "        \"@amt\", [Sell Out Amt]",
              "    )",
              "VAR temtab2 =",
              "    FILTER ( temtab1, [@amt] > 0 && NOT ISBLANK([Store Code]) )",
              "VAR totalsellout =",
              "    AVERAGEX ( temtab2, [@amt] )",
              "RETURN",
              "    IF ( NOT ( ISFILTERED ( 'Dim - Date' ) ), BLANK (), totalsellout )"
            ],
            "formatString": "#,0.0"
          },
          {
            "name": "# of Store with AVG Amt Less Than BE Point",
            "expression": [
              "  ",
              "VAR selectedval = SELECTEDVALUE('Dim - Store Amt Range'[To Value])",
              "",
              "VAR temtab1 =",
              "    SUMMARIZE (",
              "        'Fact - Sell Out',",
              "        'Dim - Date'[Month],",
              "        'Dim - Store'[Store Code],",
              "        'Dim - Date'[Year],",
              "        \"@avgamt\", [AVG Sell Out /Store/ Month]",
              "    )",
              "VAR temtab2 =",
              "    FILTER ( temtab1, [@avgamt] <selectedval && NOT ISBLANK([Store Code]) )",
              "",
              "RETURN COUNTROWS(temtab2)"
            ],
            "formatString": "#,0"
          }
        ]
      },
      {
        "name": "Fact - Actual Visit",
        "columns": [
          {
            "name": "DATE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DATE_WID"
          },
          {
            "name": "DISTRIBUTOR_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DISTRIBUTOR_WID"
          },
          {
            "name": "OUTLET_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OUTLET_WID"
          },
          {
            "name": "SALES_FORCE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SALES_FORCE_WID"
          },
          {
            "name": "SALES_TERRITORY_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SALES_TERRITORY_WID"
          },
          {
            "name": "REASON",
            "dataType": "string",
            "sourceColumn": "Reason"
          },
          {
            "name": "STATUS",
            "dataType": "string",
            "sourceColumn": "Status"
          },
          {
            "name": "CHANNEL_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CHANNEL_WID"
          },
          {
            "name": "Distributor Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Distributor Code"
          },
          {
            "name": "Visit Date",
            "dataType": "dateTime",
            "sourceColumn": "Visit Date"
          },
          {
            "name": "Route Code",
            "dataType": "string",
            "sourceColumn": "Route Code"
          },
          {
            "name": "Is Mcp",
            "dataType": "string",
            "sourceColumn": "Is Mcp"
          },
          {
            "name": "Visited Plan ID",
            "dataType": "string",
            "sourceColumn": "Visited Plan ID"
          },
          {
            "name": "Order Number",
            "dataType": "string",
            "sourceColumn": "Order Number"
          },
          {
            "name": "Outlet Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Outlet Code"
          },
          {
            "name": "Start Time",
            "dataType": "dateTime",
            "sourceColumn": "Start Time"
          },
          {
            "name": "End Time",
            "dataType": "dateTime",
            "sourceColumn": "End Time"
          },
          {
            "name": "Visited Duration Time",
            "dataType": "int64",
            "sourceColumn": "Visited Duration Time"
          },
          {
            "name": "Working Time in Route",
            "dataType": "int64",
            "sourceColumn": "Working Time in Route"
          },
          {
            "name": "Sales Man",
            "dataType": "string",
            "sourceColumn": "Sales Man"
          },
          {
            "name": "ROUTE_TYPE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ROUTE_TYPE_WID"
          },
          {
            "name": "TIME_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "TIME_WID"
          }
        ],
        "partitions": [
          {
            "name": "Part202101",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20210101 and [DATE_WID] < 20210201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20210101 and [DATE_WID] < 20210201)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202102",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20210201 and [DATE_WID] < 20210301)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20210201 and [DATE_WID] < 20210301)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202103",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20210301 and [DATE_WID] < 20210401)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20210301 and [DATE_WID] < 20210401)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202104",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20210401 and [DATE_WID] < 20210501)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20210401 and [DATE_WID] < 20210501)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202105",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20210501 and [DATE_WID] < 20210601)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20210501 and [DATE_WID] < 20210601)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202106",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20210601 and [DATE_WID] < 20210701)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20210601 and [DATE_WID] < 20210701)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202107",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20210701 and [DATE_WID] < 20210801)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20210701 and [DATE_WID] < 20210801)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202108",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20210801 and [DATE_WID] < 20210901)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20210801 and [DATE_WID] < 20210901)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202109",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20210901 and [DATE_WID] < 20211001)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20210901 and [DATE_WID] < 20211001)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202110",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20211001 and [DATE_WID] < 20211101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20211001 and [DATE_WID] < 20211101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202111",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20211101 and [DATE_WID] < 20211201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20211101 and [DATE_WID] < 20211201)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202112",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20211201 and [DATE_WID] < 20220101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20211201 and [DATE_WID] < 20220101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202001",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20200101 and [DATE_WID] < 20200201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20200101 and [DATE_WID] < 20200201)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202002",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20200201 and [DATE_WID] < 20200301)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20200201 and [DATE_WID] < 20200301)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202003",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20200301 and [DATE_WID] < 20200401)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20200301 and [DATE_WID] < 20200401)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202004",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20200401 and [DATE_WID] < 20200501)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20200401 and [DATE_WID] < 20200501)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202005",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20200501 and [DATE_WID] < 20200601)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20200501 and [DATE_WID] < 20200601)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202006",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20200601 and [DATE_WID] < 20200701)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20200601 and [DATE_WID] < 20200701)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202007",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20200701 and [DATE_WID] < 20200801)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20200701 and [DATE_WID] < 20200801)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202008",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20200801 and [DATE_WID] < 20200901)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20200801 and [DATE_WID] < 20200901)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202009",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20200901 and [DATE_WID] < 20201001)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20200901 and [DATE_WID] < 20201001)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202010",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20201001 and [DATE_WID] < 20201101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20201001 and [DATE_WID] < 20201101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202011",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20201101 and [DATE_WID] < 20201201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20201101 and [DATE_WID] < 20201201)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202012",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20201201 and [DATE_WID] < 20210101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ACTUAL_VISIT_F = Source{[Schema=\"dbo\",Item=\"VW_ACTUAL_VISIT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ACTUAL_VISIT_F, each [DATE_WID] >= 20201201 and [DATE_WID] < 20210101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "First Visit Time in Day",
            "expression": " MIN('Fact - Actual Visit'[Start Time])",
            "formatString": "MM/dd/yyyy HH:mm:ss",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralLongDateTime\" FormatString=\"MM/dd/yyyy HH:mm:ss\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Last Visit Time in Day",
            "expression": " MAX('Fact - Actual Visit'[Start Time])",
            "formatString": "MM/dd/yyyy HH:mm:ss",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralLongDateTime\" FormatString=\"MM/dd/yyyy HH:mm:ss\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Visit Duration Time",
            "expression": " SUM('Fact - Actual Visit'[Visited Duration Time])",
            "formatString": "#,0"
          },
          {
            "name": "WorkingTime on Route",
            "expression": " SUM('Fact - Actual Visit'[Working Time in Route])",
            "formatString": "#,0"
          },
          {
            "name": "# of SalesMan",
            "expression": " DISTINCTCOUNT('Fact - Actual Visit'[Sales Man])"
          },
          {
            "name": "Working Time on Route (mins)",
            "expression": " SUM('Fact - Actual Visit'[Working Time in Route])",
            "formatString": "#,0"
          },
          {
            "name": "Visit Duration Time (mins)",
            "expression": " SUM('Fact - Actual Visit'[Visited Duration Time])",
            "formatString": "#,0"
          },
          {
            "name": "Visited Call in Route",
            "expression": [
              " ",
              "CALCULATE (",
              "    COUNT ( 'Fact - Actual Visit'[Visited Plan ID] ),",
              "    'Fact - Actual Visit'[Route Code] IN DISTINCT ( 'Fact - MCP'[Route] )",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Visited Call out Route",
            "expression": [
              " ",
              "CALCULATE (",
              "    COUNT ( 'Fact - Actual Visit'[Visited Plan ID] ),",
              "    NOT('Fact - Actual Visit'[Route Code] IN DISTINCT ( 'Fact - MCP'[Route] ))",
              ")"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Plan Call/ Route/ Working Day",
            "expression": [
              "",
              "DIVIDE (",
              "    DIVIDE ( [# of Calls Plan], [# of MCP Route], \"\" ),",
              "    [Total Working Day NPP],",
              "    \"\"",
              ")"
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "Actual Call/ Route/ Working Day",
            "expression": [
              "",
              "DIVIDE (",
              "    DIVIDE ( [# of Visited Calls], [# of Visited Route], \"\" ),",
              "    [Total Working Day NPP],",
              "    \"\"",
              ")"
            ],
            "formatString": "0.00"
          },
          {
            "name": "Visited Call in Route YTD",
            "expression": " TOTALYTD([Visited Call in Route],'Dim - Date'[Date])",
            "formatString": "#,0"
          },
          {
            "name": "Visited Call out Route YTD",
            "expression": [
              " TOTALYTD([Visited Call out Route],'Dim - Date'[Date])",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "# of ASO_Kh",
            "expression": " CALCULATE([# of ASO],'Dim - Product'[Category by Storage in VN]=\"Kh\")",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of ASO_Lnh",
            "expression": " CALCULATE([# of ASO],'Dim - Product'[Category by Storage in VN]=\"Lnh\")",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "# of ASO_ng_Lnh",
            "expression": " CALCULATE([# of ASO],'Dim - Product'[Category by Storage in VN]=\"ng Lnh\")",
            "formatString": "#,0",
            "displayFolder": "KPI"
          },
          {
            "name": "canh",
            "expression": "1"
          },
          {
            "name": "canhnguyen",
            "expression": "3",
            "formatString": "#,0"
          },
          {
            "name": "ola",
            "expression": "100"
          }
        ]
      },
      {
        "name": "Dim - Club Program",
        "columns": [
          {
            "name": "CLUB_PROGRAM_WID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CLUB_PROGRAM_WID"
          },
          {
            "name": "Program Code",
            "dataType": "string",
            "sourceColumn": "Program Code"
          },
          {
            "name": "Product Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product Name"
          },
          {
            "name": "Program Type",
            "dataType": "string",
            "sourceColumn": "Program Type"
          },
          {
            "name": "Program Desc",
            "dataType": "string",
            "sourceColumn": "Program Desc"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status"
          },
          {
            "name": "Is Accumulate",
            "dataType": "string",
            "sourceColumn": "Is Accumulate"
          },
          {
            "name": "Accumulate By",
            "dataType": "string",
            "sourceColumn": "Accumulate By"
          },
          {
            "name": "Is Ratio",
            "dataType": "string",
            "sourceColumn": "Is Ratio"
          },
          {
            "name": "Start Register Date",
            "dataType": "dateTime",
            "sourceColumn": "Start Register Date"
          },
          {
            "name": "End Register Date",
            "dataType": "dateTime",
            "sourceColumn": "End Register Date"
          },
          {
            "name": "Start Execution Date",
            "dataType": "dateTime",
            "sourceColumn": "Start Execution Date"
          },
          {
            "name": "End Execution Date",
            "dataType": "dateTime",
            "sourceColumn": "End Execution Date"
          },
          {
            "name": "SAP Program Code",
            "dataType": "string",
            "sourceColumn": "SAP Program Code"
          },
          {
            "name": "SAP Program Name",
            "dataType": "string",
            "sourceColumn": "SAP Program Name"
          },
          {
            "name": "Is Active",
            "dataType": "string",
            "sourceColumn": "Is Active"
          },
          {
            "name": "Program Level",
            "dataType": "string",
            "sourceColumn": "Program Level"
          },
          {
            "name": "Revenue Target",
            "dataType": "double",
            "sourceColumn": "Revenue Target"
          },
          {
            "name": "Quantity Target",
            "dataType": "double",
            "sourceColumn": "Quantity Target"
          },
          {
            "name": "Product Code",
            "dataType": "string",
            "sourceColumn": "Product Code"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_CLUB_PROGRAM_D = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_D\"]}[Data]",
                "in",
                "    dbo_VW_CLUB_PROGRAM_D"
              ]
            }
          }
        ]
      },
      {
        "name": "Fact - Inventory",
        "columns": [
          {
            "name": "DISTRIBUTOR_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DISTRIBUTOR_WID"
          },
          {
            "name": "PRODUCT_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PRODUCT_WID"
          },
          {
            "name": "SALES_TERRITORY_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SALES_TERRITORY_WID"
          },
          {
            "name": "Transaction Date",
            "dataType": "dateTime",
            "sourceColumn": "Transaction Date"
          },
          {
            "name": "Lot Serial Number",
            "dataType": "string",
            "sourceColumn": "Lot Serial Number"
          },
          {
            "name": "Expired Date",
            "dataType": "dateTime",
            "sourceColumn": "Expired Date"
          },
          {
            "name": "CHANNEL_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CHANNEL_WID"
          },
          {
            "name": "DATE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DATE_WID"
          },
          {
            "name": "SHELFLIFE_WID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SHELFLIFE_WID"
          },
          {
            "name": "Manufacturing Date",
            "dataType": "int64",
            "sourceColumn": "Manufacturing Date"
          },
          {
            "name": "Total Shelf Life Days",
            "dataType": "double",
            "sourceColumn": "Total Shelf Life Days"
          },
          {
            "name": "INLOCATION_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "INLOCATION_WID"
          },
          {
            "name": "DISTRIBUTOR_ID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DISTRIBUTOR_ID"
          },
          {
            "name": "PRODUCT_ID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PRODUCT_ID"
          },
          {
            "name": "LOCATION_ID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "LOCATION_ID"
          },
          {
            "name": "Buy Promotion_In",
            "dataType": "double",
            "sourceColumn": "Buy Promotion_In"
          },
          {
            "name": "Other_In",
            "dataType": "double",
            "sourceColumn": "Other_In"
          },
          {
            "name": "Customer Return In",
            "dataType": "double",
            "sourceColumn": "Customer Return In"
          },
          {
            "name": "Promotion Return In",
            "dataType": "double",
            "sourceColumn": "Promotion Return In"
          },
          {
            "name": "Transfer In",
            "dataType": "double",
            "sourceColumn": "Transfer In"
          },
          {
            "name": "Upper Adj In",
            "dataType": "double",
            "sourceColumn": "Upper Adj In"
          },
          {
            "name": "Return In",
            "dataType": "double",
            "sourceColumn": "Return In"
          },
          {
            "name": "Total In",
            "dataType": "double",
            "sourceColumn": "Total In"
          },
          {
            "name": "Other Out",
            "dataType": "double",
            "sourceColumn": "Other Out"
          },
          {
            "name": "Transfer Out",
            "dataType": "double",
            "sourceColumn": "Transfer Out"
          },
          {
            "name": "Lower Adj Out",
            "dataType": "double",
            "sourceColumn": "Lower Adj Out"
          },
          {
            "name": "Debit Out",
            "dataType": "double",
            "sourceColumn": "Debit Out"
          },
          {
            "name": "Sell Out",
            "dataType": "double",
            "sourceColumn": "Sell Out"
          },
          {
            "name": "Promotion Out",
            "dataType": "double",
            "sourceColumn": "Promotion Out"
          },
          {
            "name": "Reward Out",
            "dataType": "double",
            "sourceColumn": "Reward Out"
          },
          {
            "name": "Total Out",
            "dataType": "double",
            "sourceColumn": "Total Out"
          },
          {
            "name": "Is Free",
            "dataType": "string",
            "sourceColumn": "Is Free"
          },
          {
            "name": "Supplier Return Out",
            "dataType": "double",
            "sourceColumn": "Supplier Return Out"
          },
          {
            "name": "Year Expired Date",
            "dataType": "int64",
            "sourceColumn": "Year Expired Date"
          },
          {
            "name": "Month Expired Date",
            "dataType": "int64",
            "sourceColumn": "Month Expired Date"
          }
        ],
        "partitions": [
          {
            "name": "Part202101",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20210101 and [DATE_WID] < 20210201),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_F\"]}[Data]",
                  "in",
                  "    dbo_VW_INVENTORY_F</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202102",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20210201 and [DATE_WID] < 20210301),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20210201 and [DATE_WID] < 20210301),",
                  "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                  "in",
                  "    #\"Changed Type\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202103",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20210301 and [DATE_WID] < 20210401),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20210301 and [DATE_WID] < 20210401),",
                  "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                  "in",
                  "    #\"Changed Type\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202104",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20210401 and [DATE_WID] < 20210501),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20210401 and [DATE_WID] < 20210501),",
                  "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                  "in",
                  "    #\"Changed Type\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202105",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20210501 and [DATE_WID] < 20210601),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20210501 and [DATE_WID] < 20210601),",
                  "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                  "in",
                  "    #\"Changed Type\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202106",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20210601 and [DATE_WID] < 20210701),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20210601 and [DATE_WID] < 20210701),",
                  "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                  "in",
                  "    #\"Changed Type\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202107",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20210701 and [DATE_WID] < 20210801),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20210701 and [DATE_WID] < 20210801),",
                  "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                  "in",
                  "    #\"Changed Type\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202108",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20210801 and [DATE_WID] < 20210901),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20210801 and [DATE_WID] < 20210901),",
                  "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                  "in",
                  "    #\"Changed Type\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202109",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20210901 and [DATE_WID] < 20211001),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20210901 and [DATE_WID] < 20211001),",
                  "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                  "in",
                  "    #\"Changed Type\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202110",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20211001 and [DATE_WID] < 20211101),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20211001 and [DATE_WID] < 20211101),",
                  "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                  "in",
                  "    #\"Changed Type\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202111",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20211101 and [DATE_WID] < 20211201),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20211101 and [DATE_WID] < 20211201),",
                  "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                  "in",
                  "    #\"Changed Type\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202112",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20211201 and [DATE_WID] < 20220101),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20211201 and [DATE_WID] < 20220101),",
                  "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                  "in",
                  "    #\"Changed Type\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202012",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20201201 and [DATE_WID] < 20210101),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                "in",
                "    #\"Changed Type\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_DMS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_DMS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_DMS_F, each [DATE_WID] >= 20201201 and [DATE_WID] < 20210101),",
                  "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Filtered Rows\",{{\"Manufacturing Date\", Int64.Type}})",
                  "in",
                  "    #\"Changed Type\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Distributor Opening Stock Qty",
            "expression": [
              " ",
              "VAR MINDAY = MIN('Dim - Date'[Date])",
              "var tem = ",
              "CALCULATE(SUMX('Fact - Inventory', 'Fact - Inventory'[Total In] + 'Fact - Inventory'[Total Out]), FILTER(ALL('Dim - Date'),  'Dim - Date'[Date]<MINDAY)) ",
              "return if(tem=0,BLANK(),tem)",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "Distributor Stock In Qty",
            "expression": [
              " ",
              "var tem = SUM('Fact - Inventory'[Total In])",
              "return if(tem=0,BLANK(),tem)"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Distributor Stock Out Qty",
            "expression": [
              " ",
              "var tem = SUM('Fact - Inventory'[Total Out])",
              "return if(tem=0,BLANK(),tem)"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Distributor Closing Stock Qty",
            "expression": [
              " ",
              "var tem = [Distributor Opening Stock Qty] + [Distributor Stock In Qty] + [Distributor Stock Out Qty] ",
              "RETURN if(tem = 0, BLANK(),tem)"
            ],
            "formatString": "#,0"
          },
          {
            "name": "AVG Daily Sales by day range",
            "expression": [
              " ",
              "VAR _mindate = MIN('Dim - Date'[Date])",
              "VAR _maxdate = MAX('Dim - Date'[Date])",
              "VAR _NoofDay = CALCULATE(COUNT('Dim - Date'[Date]), 'Dim - Date'[Date] >= _mindate , 'Dim - Date'[Date] <= _maxdate)",
              "VAR _TotalAmt = CALCULATE(SUM('Fact - Sell Out'[Shipped Qty]),  'Dim - Date'[Date] >= _mindate , 'Dim - Date'[Date] <= _maxdate)",
              "RETURN",
              "DIVIDE(_TotalAmt , _NoofDay)",
              "",
              "",
              ""
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "Distributor Actual DOS by day range",
            "expression": [
              " DIVIDE([Distributor Closing Stock Qty], [AVG Daily Sales by day range])",
              ""
            ]
          },
          {
            "name": "Distributor Actual DOS",
            "expression": " DIVIDE([Distributor Closing Stock Qty], [Distributor AVG 30 Daily Sales])",
            "formatString": "#,0.0"
          },
          {
            "name": "Distributor Target DOS",
            "expression": [
              " DIVIDE([Distributor Closing Stock Qty],DIVIDE([Sell Out Qty Target],[Total Working Day NPP],0),0)",
              ""
            ],
            "formatString": "0.0"
          },
          {
            "name": "%  Distributor Shelf life",
            "expression": " IF(ISTEXT( [# of Distributor Remaining Shelf life Days]),0,DIVIDE([# of Distributor Shelf life Days], [# of Distributor Remaining Shelf life Days]))",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%"
          },
          {
            "name": "# of Distributor Shelf life Days",
            "expression": [
              " SUM('Fact - Inventory'[Total Shelf Life Days])",
              "",
              ""
            ]
          },
          {
            "name": "# of Distributor Remaining Shelf life Days",
            "expression": [
              " ",
              "VAR maxdate =",
              "    MAX ( 'Dim - Date'[Date] )",
              "VAR expireddate =",
              "    VAR temdate =",
              "        MAX ( 'Fact - Inventory'[Expired Date] )",
              "    VAR expireddatewhenblank =",
              "        CALCULATE (",
              "            MAX ( 'Fact - Inventory'[Expired Date] ),",
              "            ALLEXCEPT ( 'Fact - Inventory', 'Fact - Inventory'[Lot Serial Number] )",
              "        )",
              "    RETURN",
              "        IF ( ISBLANK ( temdate ), expireddatewhenblank, temdate )",
              "VAR temresult =",
              "    DATEDIFF ( maxdate, expireddate, DAY )",
              "VAR result =",
              "    IF (",
              "        ISINSCOPE ( 'Fact - Inventory'[Lot Serial Number] ),",
              "        temresult,",
              "        \"Not in Lot Serial Number Level\"",
              "    )",
              "VAR stockblank =",
              "    ISBLANK ( [Distributor Opening Stock Qty]) && ISBLANK ( [Distributor Stock In Qty] )",
              "        && ISBLANK ( [Distributor Stock Out Qty] )",
              "        && ISBLANK ( [Distributor Closing Stock Qty] )",
              "RETURN",
              "    IF ( stockblank, BLANK (), result )"
            ],
            "formatString": "#,0"
          },
          {
            "name": "NPP/THs Min DOS",
            "expression": [
              " AVERAGE('Fact - DOS Target'[Min DOS])",
              ""
            ],
            "formatString": "0.00"
          },
          {
            "name": "NPP/THs Max DOS",
            "expression": [
              " AVERAGE('Fact - DOS Target'[Max DOS])",
              ""
            ],
            "formatString": "0.00"
          },
          {
            "name": "THs AVG 30 Daily Sales",
            "expression": [
              "",
              "VAR daysbefore = 30",
              "VAR currentmindate =",
              "    MIN ( 'Dim - Date'[Date] )",
              "VAR temtab =",
              "    SUMMARIZE (",
              "        CALCULATETABLE (",
              "            'Dim - Date',",
              "            'Dim - Date'[Is Holiday THS] = \"N\",",
              "            'Dim - Date'[Date] < currentmindate",
              "        ),",
              "        'Dim - Date'[Date]",
              "    )",
              "VAR datesets =",
              "    TOPN ( daysbefore, temtab, [Date], DESC )",
              "RETURN",
              "    CALCULATE ( DIVIDE ( [Sell Out Qty], daysbefore, 0 ), datesets )"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Distributor AVG 30 Daily Sales",
            "expression": [
              "",
              "VAR daysbefore = 30",
              "VAR currentmindate =",
              "    MIN ( 'Dim - Date'[Date] )",
              "VAR temtab =",
              "    SUMMARIZE (",
              "        CALCULATETABLE (",
              "            'Dim - Date',",
              "            'Dim - Date'[Is Holiday NPP] = \"N\",",
              "            'Dim - Date'[Date] < currentmindate",
              "        ),",
              "        'Dim - Date'[Date]",
              "    )",
              "VAR datesets =",
              "    TOPN ( daysbefore, temtab, [Date], DESC )",
              "RETURN",
              "    CALCULATE ( DIVIDE ( [Sell Out Qty], daysbefore, 0 ), datesets )"
            ],
            "formatString": "#,0"
          },
          {
            "name": "SKUs w Actual < Target DOS",
            "expression": [
              "",
              "VAR temtab =",
              "    ADDCOLUMNS (",
              "        SUMMARIZE ( 'Dim - Product', 'Dim - Product'[Product Code] ),",
              "        \"@actualdos\", [Distributor Actual DOS],",
              "        \"@targetdos\", [Distributor Target DOS]",
              "    )",
              "VAR temtab2 =",
              "    FILTER (",
              "        temtab,",
              "        NOT ( ISBLANK ( [@actualdos] ) )",
              "            && NOT ( ISBLANK ( [@targetdos] ) )",
              "                && [@actualdos] <= [@targetdos]",
              "    )",
              "RETURN",
              "    COUNTROWS ( temtab2 )"
            ],
            "formatString": "#,0"
          }
        ]
      },
      {
        "name": "Fact - MCP",
        "columns": [
          {
            "name": "DATE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DATE_WID"
          },
          {
            "name": "OUTLET_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OUTLET_WID"
          },
          {
            "name": "SALES_FORCE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SALES_FORCE_WID"
          },
          {
            "name": "SALES_TERRITORY_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SALES_TERRITORY_WID"
          },
          {
            "name": "Baseline Date",
            "dataType": "dateTime",
            "sourceColumn": "Baseline Date"
          },
          {
            "name": "Reference Number",
            "dataType": "string",
            "sourceColumn": "Reference Number"
          },
          {
            "name": "Route",
            "dataType": "string",
            "sourceColumn": "Route"
          },
          {
            "name": "Visit Date",
            "dataType": "dateTime",
            "sourceColumn": "Visit Date"
          },
          {
            "name": "Visit Order",
            "dataType": "string",
            "sourceColumn": "Visit Order"
          },
          {
            "name": "CHANNEL_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CHANNEL_WID"
          },
          {
            "name": "Distributor ID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Distributor ID"
          },
          {
            "name": "Outlet ID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Outlet ID"
          },
          {
            "name": "Call Plan ID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Call Plan ID"
          },
          {
            "name": "DISTRIBUTOR_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DISTRIBUTOR_WID"
          },
          {
            "name": "ROUTE_TYPE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ROUTE_TYPE_WID"
          }
        ],
        "partitions": [
          {
            "name": "Part202101",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20210101 and [DATE_WID] < 20210201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20210101 and [DATE_WID] < 20210201)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202102",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20210201 and [DATE_WID] < 20210301)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20210201 and [DATE_WID] < 20210301)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202103",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20210301 and [DATE_WID] < 20210401)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20210301 and [DATE_WID] < 20210401)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202104",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20210401 and [DATE_WID] < 20210501)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20210401 and [DATE_WID] < 20210501)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202105",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20210501 and [DATE_WID] < 20210601)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20210501 and [DATE_WID] < 20210601)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202106",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20210601 and [DATE_WID] < 20210701)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20210601 and [DATE_WID] < 20210701)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202107",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20210701 and [DATE_WID] < 20210801)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20210701 and [DATE_WID] < 20210801)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202108",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20210801 and [DATE_WID] < 20210901)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20210801 and [DATE_WID] < 20210901)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202109",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20210901 and [DATE_WID] < 20211001)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20210901 and [DATE_WID] < 20211001)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202110",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20211001 and [DATE_WID] < 20211101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20211001 and [DATE_WID] < 20211101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202111",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20211101 and [DATE_WID] < 20211201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20211101 and [DATE_WID] < 20211201)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202112",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20211201 and [DATE_WID] < 20220101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_MCP_F = Source{[Schema=\"dbo\",Item=\"VW_MCP_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_MCP_F, each [DATE_WID] >= 20211201 and [DATE_WID] < 20220101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ]
      },
      {
        "name": "Fact - Order Detail",
        "isHidden": true,
        "columns": [
          {
            "name": "DISTRIBUTOR_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DISTRIBUTOR_WID"
          },
          {
            "name": "PRODUCT_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PRODUCT_WID"
          },
          {
            "name": "Distributor Code",
            "dataType": "string",
            "sourceColumn": "Distributor Code"
          },
          {
            "name": "Order Number",
            "dataType": "string",
            "sourceColumn": "Order Number"
          },
          {
            "name": "Product Code",
            "dataType": "string",
            "sourceColumn": "Product Code"
          },
          {
            "name": "Line Number",
            "dataType": "string",
            "sourceColumn": "Line Number"
          },
          {
            "name": "Order Qty",
            "dataType": "double",
            "sourceColumn": "Order Qty"
          },
          {
            "name": "Delivery Qty",
            "dataType": "double",
            "sourceColumn": "Delivery Qty"
          },
          {
            "name": "Shiped Qty",
            "dataType": "double",
            "sourceColumn": "Shiped Qty"
          },
          {
            "name": "Unit Price",
            "dataType": "double",
            "sourceColumn": "Unit Price"
          },
          {
            "name": "Unit Per Case",
            "dataType": "double",
            "sourceColumn": "Unit Per Case"
          },
          {
            "name": "Free Item",
            "dataType": "string",
            "sourceColumn": "Free Item"
          },
          {
            "name": "Promotion Code",
            "dataType": "string",
            "sourceColumn": "Promotion Code"
          },
          {
            "name": "Discount Amt",
            "dataType": "double",
            "sourceColumn": "Discount Amt"
          },
          {
            "name": "CHANNEL_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CHANNEL_WID"
          },
          {
            "name": "OUTLET_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OUTLET_WID"
          },
          {
            "name": "SALES_TERRITORY_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SALES_TERRITORY_WID"
          },
          {
            "name": "Route",
            "dataType": "string",
            "sourceColumn": "Route"
          },
          {
            "name": "Order Type",
            "dataType": "string",
            "sourceColumn": "Order Type"
          },
          {
            "name": "Gross Amt",
            "dataType": "double",
            "sourceColumn": "Gross Amt"
          },
          {
            "name": "Net Amt",
            "dataType": "double",
            "sourceColumn": "Net Amt"
          },
          {
            "name": "SALES_PRICE",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "SALES_PRICE"
          },
          {
            "name": "DATE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DATE_WID"
          },
          {
            "name": "ROUTE_TYPE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ROUTE_TYPE_WID"
          }
        ],
        "partitions": [
          {
            "name": "Part202101",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20210101 and [DATE_WID] < 20210201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20210101 and [DATE_WID] < 20210201)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202102",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20210201 and [DATE_WID] < 20210301)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20210201 and [DATE_WID] < 20210301)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202103",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20210301 and [DATE_WID] < 20210401)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20210301 and [DATE_WID] < 20210401)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202104",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20210401 and [DATE_WID] < 20210501)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20210401 and [DATE_WID] < 20210501)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202105",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20210501 and [DATE_WID] < 20210601)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20210501 and [DATE_WID] < 20210601)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202106",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20210601 and [DATE_WID] < 20210701)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20210601 and [DATE_WID] < 20210701)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202107",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20210701 and [DATE_WID] < 20210801)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20210701 and [DATE_WID] < 20210801)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202108",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20210801 and [DATE_WID] < 20210901)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20210801 and [DATE_WID] < 20210901)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202109",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20210901 and [DATE_WID] < 20211001)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20210901 and [DATE_WID] < 20211001)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202110",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20211001 and [DATE_WID] < 20211101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20211001 and [DATE_WID] < 20211101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202111",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20211101 and [DATE_WID] < 20211201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20211101 and [DATE_WID] < 20211201)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202112",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20211201 and [DATE_WID] < 20220101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20211201 and [DATE_WID] < 20220101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202001",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20200101 and [DATE_WID] < 20200201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20200101 and [DATE_WID] < 20200201)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202002",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20200201 and [DATE_WID] < 20200301)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20200201 and [DATE_WID] < 20200301)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202003",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20200301 and [DATE_WID] < 20200401)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20200301 and [DATE_WID] < 20200401)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202004",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20200401 and [DATE_WID] < 20200501)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20200401 and [DATE_WID] < 20200501)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202005",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20200501 and [DATE_WID] < 20200601)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20200501 and [DATE_WID] < 20200601)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202006",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20200601 and [DATE_WID] < 20200701)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20200601 and [DATE_WID] < 20200701)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202007",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20200701 and [DATE_WID] < 20200801)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20200701 and [DATE_WID] < 20200801)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202008",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20200801 and [DATE_WID] < 20200901)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20200801 and [DATE_WID] < 20200901)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202009",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20200901 and [DATE_WID] < 20201001)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20200901 and [DATE_WID] < 20201001)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202010",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20201001 and [DATE_WID] < 20201101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20201001 and [DATE_WID] < 20201101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202011",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20201101 and [DATE_WID] < 20201201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20201101 and [DATE_WID] < 20201201)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202012",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20201201 and [DATE_WID] < 20210101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20201201 and [DATE_WID] < 20210101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part201901",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20190101 and [DATE_WID] < 20190201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20190101 and [DATE_WID] < 20190201)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part201902",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20190201 and [DATE_WID] < 20190301)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20190201 and [DATE_WID] < 20190301)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part201903",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20190301 and [DATE_WID] < 20190401)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20190301 and [DATE_WID] < 20190401)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part201904",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20190401 and [DATE_WID] < 20190501)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20190401 and [DATE_WID] < 20190501)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part201905",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20190501 and [DATE_WID] < 20190601)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20190501 and [DATE_WID] < 20190601)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part201906",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20190601 and [DATE_WID] < 20190701)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20190601 and [DATE_WID] < 20190701)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part201907",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20190701 and [DATE_WID] < 20190801)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20190701 and [DATE_WID] < 20190801)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part201908",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20190801 and [DATE_WID] < 20190901)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20190801 and [DATE_WID] < 20190901)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part201909",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20190901 and [DATE_WID] < 20191001)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20190901 and [DATE_WID] < 20191001)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part201910",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20191001 and [DATE_WID] < 20191101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20191001 and [DATE_WID] < 20191101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part201911",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20191101 and [DATE_WID] < 20191201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20191101 and [DATE_WID] < 20191201)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part201912",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20191201 and [DATE_WID] < 20200101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_ORDER_DETAIL_F = Source{[Schema=\"dbo\",Item=\"VW_ORDER_DETAIL_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_ORDER_DETAIL_F, each [DATE_WID] >= 20191201 and [DATE_WID] < 20200101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ]
      },
      {
        "name": "Dim - Product",
        "columns": [
          {
            "name": "PRODUCT_WID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PRODUCT_WID"
          },
          {
            "name": "Product Code",
            "dataType": "string",
            "sourceColumn": "Product Code"
          },
          {
            "name": "Product Name",
            "dataType": "string",
            "sourceColumn": "Product Name"
          },
          {
            "name": "Product Short Name",
            "dataType": "string",
            "sourceColumn": "Product Short Name"
          },
          {
            "name": "Product Abbr Name",
            "dataType": "string",
            "sourceColumn": "Product Abbr Name"
          },
          {
            "name": "Category by Storage in VN",
            "dataType": "string",
            "sourceColumn": "Category by Storage in VN"
          },
          {
            "name": "Category by Storage in EN",
            "dataType": "string",
            "sourceColumn": "Category by Storage in EN"
          },
          {
            "name": "Sub Category in VN",
            "dataType": "string",
            "sourceColumn": "Sub Category in VN"
          },
          {
            "name": "Sub Category in EN",
            "dataType": "string",
            "sourceColumn": "Sub Category in EN"
          },
          {
            "name": "Product Type in VN",
            "dataType": "string",
            "sourceColumn": "Product Type in VN"
          },
          {
            "name": "Product Type in EN",
            "dataType": "string",
            "sourceColumn": "Product Type in EN"
          },
          {
            "name": "Flavor in VN",
            "dataType": "string",
            "sourceColumn": "Flavor in VN"
          },
          {
            "name": "Flavor in EN",
            "dataType": "string",
            "sourceColumn": "Flavor in EN"
          },
          {
            "name": "Package Size",
            "dataType": "string",
            "sourceColumn": "Package Size"
          },
          {
            "name": "Packaging",
            "dataType": "string",
            "sourceColumn": "Packaging"
          },
          {
            "name": "Industry in VN",
            "dataType": "string",
            "sourceColumn": "Industry in VN"
          },
          {
            "name": "Industry in EN",
            "dataType": "string",
            "sourceColumn": "Industry in EN"
          },
          {
            "name": "Supplier",
            "dataType": "string",
            "sourceColumn": "Supplier"
          },
          {
            "name": "Attribute Category in VN",
            "dataType": "string",
            "sourceColumn": "Attribute Category in VN"
          },
          {
            "name": "Attribute Category in EN",
            "dataType": "string",
            "sourceColumn": "Attribute Category in EN"
          },
          {
            "name": "Market",
            "dataType": "string",
            "sourceColumn": "Market"
          },
          {
            "name": "Packaging Type in VN",
            "dataType": "string",
            "sourceColumn": "Packaging Type in VN"
          },
          {
            "name": "Packaging Type in EN",
            "dataType": "string",
            "sourceColumn": "Packaging Type in EN"
          },
          {
            "name": "Distributor Category in VN",
            "dataType": "string",
            "sourceColumn": "Distributor Category in VN"
          },
          {
            "name": "Distributor Category in EN",
            "dataType": "string",
            "sourceColumn": "Distributor Category in EN"
          },
          {
            "name": "Category in VN",
            "dataType": "string",
            "sourceColumn": "Category in VN"
          },
          {
            "name": "Category in eN",
            "dataType": "string",
            "sourceColumn": "Category in EN"
          },
          {
            "name": "NPD Date",
            "dataType": "string",
            "sourceColumn": "NPD Date"
          },
          {
            "name": "NPD Number Day",
            "dataType": "int64",
            "sourceColumn": "NPD Number Day",
            "summarizeBy": "none"
          },
          {
            "name": "Is POSM",
            "dataType": "string",
            "sourceColumn": "Is POSM"
          },
          {
            "name": "VAT",
            "dataType": "double",
            "sourceColumn": "VAT",
            "summarizeBy": "none"
          },
          {
            "name": "Is New Product",
            "dataType": "string",
            "sourceColumn": "Is New Product"
          },
          {
            "name": "Convert Rate to Ml",
            "dataType": "double",
            "sourceColumn": "Convert Rate to Ml"
          },
          {
            "name": "Convert Rate to Gram",
            "dataType": "double",
            "sourceColumn": "Convert Rate to Gram"
          },
          {
            "name": "Type",
            "dataType": "string",
            "sourceColumn": "Type"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PRODUCT_D = Source{[Schema=\"dbo\",Item=\"VW_PRODUCT_D\"]}[Data]",
                "in",
                "    dbo_VW_PRODUCT_D"
              ]
            }
          }
        ]
      },
      {
        "name": "Dim - Sales Force",
        "columns": [
          {
            "name": "SALESFORCE_WID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SALESFORCE_WID"
          },
          {
            "name": "Employee Code",
            "dataType": "string",
            "sourceColumn": "Employee Code"
          },
          {
            "name": "SalesMan Name",
            "dataType": "string",
            "sourceColumn": "SalesMan Name"
          },
          {
            "name": "SalesSup Name",
            "dataType": "string",
            "sourceColumn": "SalesSup Name"
          },
          {
            "name": "ASM Name",
            "dataType": "string",
            "sourceColumn": "ASM Name"
          },
          {
            "name": "RSM Name",
            "dataType": "string",
            "sourceColumn": "RSM Name"
          },
          {
            "name": "SM Name",
            "dataType": "string",
            "sourceColumn": "SM Name"
          },
          {
            "name": "NSD Name",
            "dataType": "string",
            "sourceColumn": "NSD Name"
          },
          {
            "name": "Store Manager ID",
            "dataType": "string",
            "sourceColumn": "Store Manager ID"
          },
          {
            "name": "Store Manager Name",
            "dataType": "string",
            "sourceColumn": "Store Manager Name"
          },
          {
            "name": "District Sup Name",
            "dataType": "string",
            "sourceColumn": "District Sup Name"
          },
          {
            "name": "Area Store Name",
            "dataType": "string",
            "sourceColumn": "Area Store Name"
          },
          {
            "name": "National Director Name",
            "dataType": "string",
            "sourceColumn": "National Director Name"
          },
          {
            "name": "Type",
            "dataType": "string",
            "sourceColumn": "Type"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SALE_FORCE_D = Source{[Schema=\"dbo\",Item=\"VW_SALE_FORCE_D\"]}[Data]",
                "in",
                "    dbo_VW_SALE_FORCE_D"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "GT&KA SF",
            "levels": [
              {
                "name": "NSD Name",
                "ordinal": 0,
                "column": "NSD Name"
              },
              {
                "name": "SM Name",
                "ordinal": 1,
                "column": "SM Name"
              },
              {
                "name": "RSM Name",
                "ordinal": 2,
                "column": "RSM Name"
              },
              {
                "name": "ASM Name",
                "ordinal": 3,
                "column": "ASM Name"
              },
              {
                "name": "SalesSup Name",
                "ordinal": 4,
                "column": "SalesSup Name"
              }
            ]
          },
          {
            "name": "THs SF",
            "levels": [
              {
                "name": "National Director Name",
                "ordinal": 0,
                "column": "National Director Name"
              },
              {
                "name": "Area Store Name",
                "ordinal": 1,
                "column": "Area Store Name"
              },
              {
                "name": "District Sup Name",
                "ordinal": 2,
                "column": "District Sup Name"
              },
              {
                "name": "Store Manager Name",
                "ordinal": 3,
                "column": "Store Manager Name"
              }
            ]
          }
        ]
      },
      {
        "name": "Dim - Sales Territory",
        "columns": [
          {
            "name": "SALES_TERRITORY_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SALES_TERRITORY_WID"
          },
          {
            "name": "Location Code",
            "dataType": "string",
            "sourceColumn": "Location Code"
          },
          {
            "name": "Country Name",
            "dataType": "string",
            "sourceColumn": "Country Name"
          },
          {
            "name": "Province Name",
            "dataType": "string",
            "sourceColumn": "Province Name"
          },
          {
            "name": "District Name",
            "dataType": "string",
            "sourceColumn": "District Name"
          },
          {
            "name": "Location Name",
            "dataType": "string",
            "sourceColumn": "Location Name"
          },
          {
            "name": "Region",
            "dataType": "string",
            "sourceColumn": "Region"
          },
          {
            "name": "Area",
            "dataType": "string",
            "sourceColumn": "Area"
          },
          {
            "name": "Sub Area",
            "dataType": "string",
            "sourceColumn": "Sub Area"
          },
          {
            "name": "Distributor/Store Code",
            "dataType": "string",
            "sourceColumn": "Distributor/Store Code"
          },
          {
            "name": "Distributor/Store Short Name",
            "dataType": "string",
            "sourceColumn": "Distributor/Store Short Name"
          },
          {
            "name": "Territory Type",
            "dataType": "string",
            "sourceColumn": "Territory Type"
          },
          {
            "name": "Branch",
            "dataType": "string",
            "sourceColumn": "Branch",
            "sortByColumn": "Branch Code Sort"
          },
          {
            "name": "Branch Code Sort",
            "dataType": "int64",
            "sourceColumn": "Branch Code Sort"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SALES_TERRITORY_HIERARCHY_D = Source{[Schema=\"dbo\",Item=\"VW_SALES_TERRITORY_HIERARCHY_D\"]}[Data]",
                "in",
                "    dbo_VW_SALES_TERRITORY_HIERARCHY_D"
              ]
            }
          }
        ]
      },
      {
        "name": "Dim - Channel",
        "columns": [
          {
            "name": "CHANNEL_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CHANNEL_WID"
          },
          {
            "name": "Channel Name",
            "dataType": "string",
            "sourceColumn": "Channel Name",
            "sortByColumn": "Channel Order"
          },
          {
            "name": "Sub Channel Name",
            "dataType": "string",
            "sourceColumn": "Sub Channel Name"
          },
          {
            "name": "Channel Order",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Channel Order"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_CHANNEL_D = Source{[Schema=\"dbo\",Item=\"VW_CHANNEL_D\"]}[Data]",
                "in",
                "    dbo_VW_CHANNEL_D"
              ]
            }
          }
        ]
      },
      {
        "name": "Fact - DOS Target",
        "columns": [
          {
            "name": "DATE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DATE_WID"
          },
          {
            "name": "DISTRIBUTOR_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DISTRIBUTOR_WID"
          },
          {
            "name": "STORE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "STORE_WID"
          },
          {
            "name": "PRODUCT_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PRODUCT_WID"
          },
          {
            "name": "SALES_TERRITORY_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SALES_TERRITORY_WID"
          },
          {
            "name": "Distributor/STore Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Distributor/STore Code"
          },
          {
            "name": "Product Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product Code"
          },
          {
            "name": "Max DOS",
            "dataType": "double",
            "sourceColumn": "Max DOS"
          },
          {
            "name": "Min DOS",
            "dataType": "double",
            "sourceColumn": "Min DOS"
          },
          {
            "name": "Type",
            "dataType": "string",
            "sourceColumn": "Type"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_DOS_TARGET_F = Source{[Schema=\"dbo\",Item=\"VW_DOS_TARGET_F\"]}[Data]",
                "in",
                "    dbo_VW_DOS_TARGET_F"
              ]
            }
          }
        ]
      },
      {
        "name": "Fact - Target",
        "columns": [
          {
            "name": "DATE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DATE_WID"
          },
          {
            "name": "DISTRIBUTOR_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DISTRIBUTOR_WID"
          },
          {
            "name": "STORE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "STORE_WID"
          },
          {
            "name": "PRODUCT_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PRODUCT_WID"
          },
          {
            "name": "SALES_TERRITORY_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SALES_TERRITORY_WID"
          },
          {
            "name": "Distributor/STore Code",
            "dataType": "string",
            "sourceColumn": "Distributor/STore Code"
          },
          {
            "name": "Product Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product Code"
          },
          {
            "name": "UOM",
            "dataType": "string",
            "sourceColumn": "UOM"
          },
          {
            "name": "Target Type",
            "dataType": "string",
            "sourceColumn": "Target Type"
          },
          {
            "name": "Target Value",
            "dataType": "double",
            "sourceColumn": "Target Value"
          },
          {
            "name": "Type",
            "dataType": "string",
            "sourceColumn": "Type"
          },
          {
            "name": "CHANNEL_WID",
            "dataType": "int64",
            "sourceColumn": "CHANNEL_WID"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_TARGET_F = Source{[Schema=\"dbo\",Item=\"VW_TARGET_F\"]}[Data]",
                "in",
                "    dbo_VW_TARGET_F"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sell Out Qty Target",
            "expression": " CALCULATE(SUM('Fact - Target'[Target Value]), FILTER('Fact - Target', 'Fact - Target'[Target Type] = \"Sales Quantity\"))"
          },
          {
            "name": "Sell Out Amt Target",
            "expression": " CALCULATE(SUM('Fact - Target'[Target Value]),FILTER('Fact - Target', 'Fact - Target'[Target Type] = \"Sales Amt\"))",
            "displayFolder": "Sell Out"
          },
          {
            "name": "Sell Out Qty Target MTD",
            "expression": " TOTALMTD([Sell Out Qty Target], 'Dim - Date'[Date])"
          },
          {
            "name": "Sell Out Qty Target YTD",
            "expression": " TOTALYTD([Sell Out Qty Target], 'Dim - Date'[Date])"
          },
          {
            "name": "Sell Out Qty Target MTD LM",
            "expression": " CALCULATE([Sell Out Qty Target MTD], PREVIOUSMONTH('Dim - Date'[Date]))"
          },
          {
            "name": "Sell Out Qty Target YTD LY",
            "expression": " CALCULATE([Sell Out Qty Target YTD], SAMEPERIODLASTYEAR('Dim - Date'[Date]))"
          },
          {
            "name": "Sell Out Amt Target MTD",
            "expression": " TOTALMTD([Sell Out Amt Target], 'Dim - Date'[Date])"
          },
          {
            "name": "Sell Out Amt Target YTD",
            "expression": " TOTALYTD([Sell Out Amt Target], 'Dim - Date'[Date])"
          },
          {
            "name": "Sell Out Amt Target MTD LM",
            "expression": " CALCULATE([Sell Out Amt Target MTD], PREVIOUSMONTH('Dim - Date'[Date]))"
          },
          {
            "name": "Sell Out Amt Target YTD LY",
            "expression": " CALCULATE([Sell Out Amt Target YTD], SAMEPERIODLASTYEAR('Dim - Date'[Date]))"
          },
          {
            "name": "Sell Out Amt Remaining vs Target",
            "expression": [
              " [Sell Out Amt Target] - [Sell Out Amt]",
              ""
            ]
          },
          {
            "name": "Sell Out Qty Remaining vs Target",
            "expression": " [Sell Out Qty Target] - [Sell Out Qty]"
          },
          {
            "name": "Sell Out Amt YTD LY",
            "expression": " CALCULATE([Sell Out Amt YTD], SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
            "formatString": "0"
          }
        ]
      },
      {
        "name": "Fact - AOP",
        "columns": [
          {
            "name": "DATE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DATE_WID"
          },
          {
            "name": "DISTRIBUTOR_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DISTRIBUTOR_WID"
          },
          {
            "name": "STORE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "STORE_WID"
          },
          {
            "name": "PRODUCT_WID",
            "dataType": "int64",
            "sourceColumn": "PRODUCT_WID"
          },
          {
            "name": "SALES_TERRITORY_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SALES_TERRITORY_WID"
          },
          {
            "name": "Distributor/STore Code",
            "dataType": "string",
            "sourceColumn": "Distributor/STore Code"
          },
          {
            "name": "Product Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product Code"
          },
          {
            "name": "UOM",
            "dataType": "string",
            "sourceColumn": "UOM"
          },
          {
            "name": "AOP Version",
            "dataType": "string",
            "sourceColumn": "AOP Version"
          },
          {
            "name": "AOP Type",
            "dataType": "string",
            "sourceColumn": "AOP Type"
          },
          {
            "name": "AOP Value",
            "dataType": "double",
            "sourceColumn": "AOP Value"
          },
          {
            "name": "Type",
            "dataType": "string",
            "sourceColumn": "Type"
          },
          {
            "name": "CHANNEL_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CHANNEL_WID"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_AOP_F = Source{[Schema=\"dbo\",Item=\"VW_AOP_F\"]}[Data]",
                "in",
                "    dbo_VW_AOP_F"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sell Out Qty AOP",
            "expression": " CALCULATE(SUM('Fact - AOP'[AOP Value]),'Fact - AOP'[AOP Type] = \"Quantity\")"
          },
          {
            "name": "Sell Out Amt AOP",
            "expression": " CALCULATE(SUM('Fact - AOP'[AOP Value]), 'Fact - AOP'[AOP Type] = \"Amt\")"
          },
          {
            "name": "Sell Out Qty AOP FY",
            "expression": " CALCULATE([Sell Out Qty AOP], REMOVEFILTERS( 'Dim - Date'[Date], 'Dim - Date'[Month]))"
          },
          {
            "name": "Sell Out Amt AOP FY",
            "expression": " CALCULATE([Sell Out Amt AOP], REMOVEFILTERS( 'Dim - Date'[Date], 'Dim - Date'[Month]))"
          },
          {
            "name": "Sell Out Amt AOP Revised",
            "expression": " CALCULATE([Sell Out amt AOP], 'Fact - AOP'[AOP Version] = \"Revised\")"
          },
          {
            "name": "Sell Out Qty AOP Revised",
            "expression": " CALCULATE([Sell Out qty AOP], 'Fact - AOP'[AOP Version] = \"Revised\")"
          }
        ]
      },
      {
        "name": "Dim - Tender",
        "columns": [
          {
            "name": "TENDER_TYPE_WID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "TENDER_TYPE_WID"
          },
          {
            "name": "Tender Type Code",
            "dataType": "string",
            "sourceColumn": "Tender Type Code"
          },
          {
            "name": "Tender Type Name",
            "dataType": "string",
            "sourceColumn": "Tender Type Name"
          },
          {
            "name": "Account Name",
            "dataType": "string",
            "sourceColumn": "Account Name"
          },
          {
            "name": "Account Number",
            "dataType": "string",
            "sourceColumn": "Account Number"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_TENDER_D = Source{[Schema=\"dbo\",Item=\"VW_TENDER_D\"]}[Data]",
                "in",
                "    dbo_VW_TENDER_D"
              ]
            }
          }
        ]
      },
      {
        "name": "Fact - Inventory Ths",
        "columns": [
          {
            "name": "DATE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DATE_WID"
          },
          {
            "name": "STORE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "STORE_WID"
          },
          {
            "name": "PRODUCT_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PRODUCT_WID"
          },
          {
            "name": "STORE_TERRITORY_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "STORE_TERRITORY_WID"
          },
          {
            "name": "Store Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Store Code"
          },
          {
            "name": "Product Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product Code"
          },
          {
            "name": "Lot Serial Number",
            "dataType": "string",
            "sourceColumn": "Lot Serial Number"
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "sourceColumn": "Posting Date"
          },
          {
            "name": "Expired Date",
            "dataType": "dateTime",
            "sourceColumn": "Expired Date"
          },
          {
            "name": "In Qty",
            "dataType": "double",
            "sourceColumn": "In Qty"
          },
          {
            "name": "Other Out Qty",
            "dataType": "double",
            "sourceColumn": "Other Out Qty"
          },
          {
            "name": "Sold Qty",
            "dataType": "double",
            "sourceColumn": "Sold Qty"
          },
          {
            "name": "Returned Qty",
            "dataType": "double",
            "sourceColumn": "Returned Qty"
          },
          {
            "name": "Adjust In Qty",
            "dataType": "double",
            "sourceColumn": "Adjust In Qty"
          },
          {
            "name": "Adjust Out Qty",
            "dataType": "double",
            "sourceColumn": "Adjust Out Qty"
          },
          {
            "name": "THs Transport In Qty",
            "dataType": "double",
            "sourceColumn": "THs Transport In Qty"
          },
          {
            "name": "Ths Transport Out Qty",
            "dataType": "double",
            "sourceColumn": "Ths Transport Out Qty"
          },
          {
            "name": "Internal Transport In Qty",
            "dataType": "double",
            "sourceColumn": "Internal Transport In Qty"
          },
          {
            "name": "Internal Transport Out Qty",
            "dataType": "double",
            "sourceColumn": "Internal Transport Out Qty"
          },
          {
            "name": "Total In Qty",
            "dataType": "double",
            "sourceColumn": "Total In Qty"
          },
          {
            "name": "Total Out Qty",
            "dataType": "double",
            "sourceColumn": "Total Out Qty"
          },
          {
            "name": "Intrans Qty",
            "dataType": "double",
            "sourceColumn": "Intrans Qty"
          },
          {
            "name": "Shelf life Days",
            "dataType": "int64",
            "sourceColumn": "Shelf life Days"
          },
          {
            "name": "Total Shelf life Days",
            "dataType": "double",
            "sourceColumn": "Total Shelf life Days"
          },
          {
            "name": "SHELFLIFE_WID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SHELFLIFE_WID"
          },
          {
            "name": "Manufacturing Date",
            "dataType": "dateTime",
            "sourceColumn": "Manufacturing Date"
          },
          {
            "name": "Year Expired Date",
            "dataType": "int64",
            "sourceColumn": "Year Expired Date"
          },
          {
            "name": "Month Expired Date",
            "dataType": "int64",
            "sourceColumn": "Month Expired Date"
          }
        ],
        "partitions": [
          {
            "name": "Part202101",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20210101 and [DATE_WID] < 20210201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20210101 and [DATE_WID] < 20210201)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202102",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20210201 and [DATE_WID] < 20210301)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20210201 and [DATE_WID] < 20210301)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202012",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20201201 and [DATE_WID] < 20210101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20201201 and [DATE_WID] < 20210101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202103",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20210301 and [DATE_WID] < 20210401)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20210301 and [DATE_WID] < 20210401)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202104",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20210401 and [DATE_WID] < 20210501)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20210401 and [DATE_WID] < 20210501)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202105",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20210501 and [DATE_WID] < 20210601)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20210501 and [DATE_WID] < 20210601)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202106",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20210601 and [DATE_WID] < 20210701)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20210601 and [DATE_WID] < 20210701)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202107",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20210701 and [DATE_WID] < 20210801)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20210701 and [DATE_WID] < 20210801)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202108",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20210801 and [DATE_WID] < 20210901)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20210801 and [DATE_WID] < 20210901)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202109",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20210901 and [DATE_WID] < 20211001)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20210901 and [DATE_WID] < 20211001)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202110",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20211001 and [DATE_WID] < 20211101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20211001 and [DATE_WID] < 20211101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202111",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20211101 and [DATE_WID] < 20211201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20211101 and [DATE_WID] < 20211201)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202112",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20211201 and [DATE_WID] < 20220101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_INVENTORY_LS_F = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_LS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_INVENTORY_LS_F, each [DATE_WID] >= 20211201 and [DATE_WID] < 20220101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "THs Stock In Qty",
            "expression": [
              " ",
              "var tem = SUM('Fact - Inventory Ths'[Total In Qty])",
              "return if(tem=0,BLANK(),tem)"
            ],
            "formatString": "#,0"
          },
          {
            "name": "THs Stock Out Qty",
            "expression": [
              " ",
              "var tem = SUM('Fact - Inventory Ths'[Total Out Qty])",
              "return if(tem=0,BLANK(),tem)"
            ],
            "formatString": "#,0"
          },
          {
            "name": "THs Closing Stock Qty",
            "expression": [
              " ",
              "var tem = [THs Opening Stock Qty] + [THs Stock In Qty] + [THs Stock Out Qty] + [THs Stock Intrans Qty]",
              "RETURN if(tem = 0, BLANK(),tem)"
            ],
            "formatString": "#,0"
          },
          {
            "name": "THs Opening Stock Qty",
            "expression": [
              " ",
              "VAR MINDAY = MIN('Dim - Date'[Date])",
              "var tem = ",
              "CALCULATE(SUMX('Fact - Inventory Ths', 'Fact - Inventory Ths'[Total In Qty] + 'Fact - Inventory Ths'[Total Out Qty] +  'Fact - Inventory Ths'[Intrans Qty]), FILTER(ALL('Dim - Date'),  'Dim - Date'[Date]<MINDAY)) ",
              "return if(tem=0,BLANK(),tem)",
              ""
            ],
            "formatString": "#,0"
          },
          {
            "name": "THs DOS",
            "expression": " DIVIDE([THs Closing Stock Qty], [THs AVG 30 Daily Sales])",
            "formatString": "#,0.00"
          },
          {
            "name": "THs Closing Stock Qty - Chill",
            "expression": " CALCULATE([THs Closing Stock Qty] , 'Dim - Product'[Category by Storage in EN] = \"Chill\")",
            "formatString": "#,0.00"
          },
          {
            "name": "THs Closing Stock Qty - Ambient",
            "expression": " CALCULATE([THs Closing Stock Qty] , 'Dim - Product'[Category by Storage in EN] = \"Ambient\")",
            "formatString": "#,0.00"
          },
          {
            "name": "THs Closing Stock Qty - Frozen",
            "expression": " CALCULATE([THs Closing Stock Qty] , 'Dim - Product'[Category by Storage in EN] = \"Frozen\")",
            "formatString": "#,0.00"
          },
          {
            "name": "THs Closing Stock Qty   other",
            "expression": " [THs Closing Stock Qty] - ([THs Closing Stock Qty - Ambient] + [THs Closing Stock Qty - Chill] + [THs Closing Stock Qty - Frozen])",
            "formatString": "#,0.00"
          },
          {
            "name": "# of Unique SKUs in Stock",
            "expression": " DISTINCTCOUNT('Fact - Inventory Ths'[Product Code])",
            "formatString": "#,0"
          },
          {
            "name": "THs Stock Intrans Qty",
            "expression": " SUM('Fact - Inventory Ths'[Intrans Qty])",
            "formatString": "#,0.00"
          },
          {
            "name": "# of THs Remaining Shelf life Days",
            "expression": [
              " /*SUM('Fact - Inventory'[Shelf life Days])*/",
              "VAR maxdate =",
              "    MAX ( 'Dim - Date'[Date] )",
              "VAR expireddate =",
              "    VAR temdate =",
              "        MAX ( 'Fact - Inventory Ths'[Expired Date] )",
              "    VAR expireddatewhenblank =",
              "        CALCULATE (",
              "            MAX ( 'Fact - Inventory Ths'[Expired Date] ),",
              "            ALLEXCEPT ( 'Fact - Inventory Ths', 'Fact - Inventory Ths'[Lot Serial Number] )",
              "        )",
              "    RETURN",
              "        IF ( ISBLANK ( temdate ), expireddatewhenblank, temdate )",
              "VAR temresult =",
              "    DATEDIFF ( maxdate, expireddate, DAY )",
              "VAR result =",
              "    IF (",
              "        ISINSCOPE ( 'Fact - Inventory Ths'[Lot Serial Number] ),",
              "        temresult,",
              "        \"Not in Lot Serial Number Level\"",
              "    )",
              "VAR stockblank =",
              "    ISBLANK ( [THs Opening Stock Qty] ) && ISBLANK ( [THs Stock In Qty] )",
              "        && ISBLANK ( [THs Stock Out Qty] )",
              "        && ISBLANK ( [THs Closing Stock Qty] )",
              "RETURN",
              "    IF ( stockblank, BLANK (), result )"
            ],
            "formatString": "#,0"
          },
          {
            "name": "THs Shelf life Days",
            "expression": " SUM('Fact - Inventory Ths'[Total Shelf life Days])",
            "formatString": "#,0"
          },
          {
            "name": "# of Unique SKUs Cleared in Stock",
            "expression": [
              " ",
              "var _AllStock = ADDCOLUMNS(SUMMARIZE('Fact - Inventory Ths', [Product Code], 'Fact - Inventory Ths'[DATE_WID]), \"_qty\", [THs Closing Stock Qty])",
              "var _ClearStock = FILTER(_AllStock, [_qty] = 0)",
              "return ",
              "COUNTROWS(_ClearStock)"
            ],
            "formatString": "#,0"
          }
        ]
      },
      {
        "name": "Dim - Promotion",
        "columns": [
          {
            "name": "PROMOTION_WID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PROMOTION_WID"
          },
          {
            "name": "Promotion Code",
            "dataType": "string",
            "sourceColumn": "Promotion Code"
          },
          {
            "name": "Discount Type",
            "dataType": "string",
            "sourceColumn": "Discount Type"
          },
          {
            "name": "Is Sellin",
            "dataType": "string",
            "sourceColumn": "Is Sellin"
          },
          {
            "name": "Apply For",
            "dataType": "string",
            "sourceColumn": "Apply For"
          },
          {
            "name": "Scheme",
            "dataType": "string",
            "sourceColumn": "Scheme"
          },
          {
            "name": "Deal",
            "dataType": "string",
            "sourceColumn": "Deal"
          },
          {
            "name": "Discount By",
            "dataType": "string",
            "sourceColumn": "Discount By"
          },
          {
            "name": "Discount By Free",
            "dataType": "string",
            "sourceColumn": "Discount By Free"
          },
          {
            "name": "Effective Date",
            "dataType": "dateTime",
            "sourceColumn": "Effective Date"
          },
          {
            "name": "End Date",
            "dataType": "dateTime",
            "sourceColumn": "End Date"
          },
          {
            "name": "Is Budget",
            "dataType": "string",
            "sourceColumn": "Is Budget"
          },
          {
            "name": "Promotion Desc",
            "dataType": "string",
            "sourceColumn": "Promotion Desc"
          },
          {
            "name": "Promotion Rate",
            "dataType": "string",
            "sourceColumn": "Promotion Rate"
          },
          {
            "name": "Multi Type",
            "dataType": "string",
            "sourceColumn": "Multi Type"
          },
          {
            "name": "Priority",
            "dataType": "int64",
            "sourceColumn": "Priority",
            "summarizeBy": "none"
          },
          {
            "name": "Exclude",
            "dataType": "string",
            "sourceColumn": "Exclude"
          },
          {
            "name": "Compound",
            "dataType": "string",
            "sourceColumn": "Compound"
          },
          {
            "name": "Is Ho Discount",
            "dataType": "string",
            "sourceColumn": "Is Ho Discount"
          },
          {
            "name": "Active",
            "dataType": "string",
            "sourceColumn": "Active"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status"
          },
          {
            "name": "Applicable To",
            "dataType": "string",
            "sourceColumn": "Applicable To"
          },
          {
            "name": "Apply To",
            "dataType": "string",
            "sourceColumn": "Apply To"
          },
          {
            "name": "Close Date",
            "dataType": "dateTime",
            "sourceColumn": "Close Date"
          },
          {
            "name": "Is Condition",
            "dataType": "string",
            "sourceColumn": "Is Condition"
          },
          {
            "name": "IO Code",
            "dataType": "string",
            "sourceColumn": "IO Code"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_D = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_D\"]}[Data]",
                "in",
                "    dbo_VW_PROMOTION_D"
              ]
            }
          }
        ]
      },
      {
        "name": "Dim - Promotion Ths",
        "columns": [
          {
            "name": "PROMOTION_WID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PROMOTION_WID"
          },
          {
            "name": "Promotion Code",
            "dataType": "string",
            "sourceColumn": "Promotion Code"
          },
          {
            "name": "Promotion Name",
            "dataType": "string",
            "sourceColumn": "Promotion Name"
          },
          {
            "name": "Promotion Status",
            "dataType": "string",
            "sourceColumn": "Promotion Status"
          },
          {
            "name": "Promotion Type",
            "dataType": "string",
            "sourceColumn": "Promotion Type"
          },
          {
            "name": "Price Group",
            "dataType": "string",
            "sourceColumn": "Price Group"
          },
          {
            "name": "Offer Type",
            "dataType": "string",
            "sourceColumn": "Offer Type"
          },
          {
            "name": "No Series",
            "dataType": "string",
            "sourceColumn": "No Series"
          },
          {
            "name": "Priority",
            "dataType": "string",
            "sourceColumn": "Priority"
          },
          {
            "name": "Pop Up Line",
            "dataType": "string",
            "sourceColumn": "Pop Up Line"
          },
          {
            "name": "Coupon Code",
            "dataType": "string",
            "sourceColumn": "Coupon Code"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_D = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_D\"]}[Data]",
                "in",
                "    dbo_VW_PROMOTION_LS_D"
              ]
            }
          }
        ]
      },
      {
        "name": "Fact - Promotion Ths",
        "columns": [
          {
            "name": "DATE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DATE_WID"
          },
          {
            "name": "STORE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "STORE_WID"
          },
          {
            "name": "PRODUCT_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PRODUCT_WID"
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "sourceColumn": "Posting Date"
          },
          {
            "name": "Store Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Store Code"
          },
          {
            "name": "Transaction Number",
            "dataType": "string",
            "sourceColumn": "Transaction Number"
          },
          {
            "name": "Receipt Number",
            "dataType": "string",
            "sourceColumn": "Receipt Number"
          },
          {
            "name": "Product Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product Code"
          },
          {
            "name": "Discount Amt",
            "dataType": "double",
            "sourceColumn": "Discount Amt"
          },
          {
            "name": "Discount Quantity",
            "dataType": "double",
            "sourceColumn": "Discount Quantity"
          },
          {
            "name": "PROMOTION_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PROMOTION_WID"
          },
          {
            "name": "Pos Code",
            "dataType": "string",
            "sourceColumn": "Pos Code"
          },
          {
            "name": "Promotion Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Promotion Code"
          },
          {
            "name": "CHANNEL_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CHANNEL_WID"
          },
          {
            "name": "STORE_TERRITORY_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "STORE_TERRITORY_WID"
          },
          {
            "name": "SALE_FORCE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SALE_FORCE_WID"
          },
          {
            "name": "SALE_TYPE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SALE_TYPE_WID"
          },
          {
            "name": "Estimated Amt",
            "dataType": "double",
            "sourceColumn": "Estimated Amt"
          },
          {
            "name": "Net Price",
            "dataType": "double",
            "sourceColumn": "Net Price"
          },
          {
            "name": "Original Quantity",
            "dataType": "double",
            "sourceColumn": "Original Quantity"
          },
          {
            "name": "Original Net Amt",
            "dataType": "double",
            "sourceColumn": "Original Net Amt"
          },
          {
            "name": "VAT Amt",
            "dataType": "double",
            "sourceColumn": "VAT Amt"
          },
          {
            "name": "Is Return Order",
            "dataType": "string",
            "sourceColumn": "Is Return Order"
          },
          {
            "name": "Order Type",
            "dataType": "string",
            "sourceColumn": "Order Type"
          },
          {
            "name": "Discount Net Amt",
            "dataType": "double",
            "sourceColumn": "Discount Net Amt"
          }
        ],
        "partitions": [
          {
            "name": "Part202101",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20210101 and [DATE_WID] < 20210201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20210101 and [DATE_WID] < 20210201)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202102",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20210201 and [DATE_WID] < 20210301)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20210201 and [DATE_WID] < 20210301)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202103",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20210301 and [DATE_WID] < 20210401)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20210301 and [DATE_WID] < 20210401)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202104",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20210401 and [DATE_WID] < 20210501)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202105",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20210501 and [DATE_WID] < 20210601)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202106",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20210601 and [DATE_WID] < 20210701)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202107",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20210701 and [DATE_WID] < 20210801)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202108",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20210801 and [DATE_WID] < 20210901)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202109",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20210901 and [DATE_WID] < 20211001)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202110",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20211001 and [DATE_WID] < 20211101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202111",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20211101 and [DATE_WID] < 20211201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202112",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20211201 and [DATE_WID] < 20220101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201901",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20190101 and [DATE_WID] < 20190201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201902",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20190201 and [DATE_WID] < 20190301)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201903",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20190301 and [DATE_WID] < 20190401)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201904",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20190401 and [DATE_WID] < 20190501)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201905",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20190501 and [DATE_WID] < 20190601)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201906",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20190601 and [DATE_WID] < 20190701)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201907",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20190701 and [DATE_WID] < 20190801)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201908",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20190801 and [DATE_WID] < 20190901)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201909",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20190901 and [DATE_WID] < 20191001)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201910",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20191001 and [DATE_WID] < 20191101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201911",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20191101 and [DATE_WID] < 20191201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part201912",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20191201 and [DATE_WID] < 20200101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202001",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20200101 and [DATE_WID] < 20200201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202002",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20200201 and [DATE_WID] < 20200301)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202003",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20200301 and [DATE_WID] < 20200401)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202004",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20200401 and [DATE_WID] < 20200501)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202005",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20200501 and [DATE_WID] < 20200601)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202006",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20200601 and [DATE_WID] < 20200701)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202007",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20200701 and [DATE_WID] < 20200801)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202008",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20200801 and [DATE_WID] < 20200901)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202009",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20200901 and [DATE_WID] < 20201001)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202010",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20201001 and [DATE_WID] < 20201101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202011",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20201101 and [DATE_WID] < 20201201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          },
          {
            "name": "Part202012",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_PROMOTION_LS_F = Source{[Schema=\"dbo\",Item=\"VW_PROMOTION_LS_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_PROMOTION_LS_F, each [DATE_WID] >= 20201201 and [DATE_WID] < 20210101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Promotion Qty",
            "expression": " SUM('Fact - Promotion Ths'[Discount Quantity])",
            "formatString": "#,0.00"
          },
          {
            "name": "Ths Promotion Estimated Amt",
            "expression": " SUM('Fact - Promotion Ths'[Estimated Amt])",
            "formatString": "#,0.00"
          },
          {
            "name": "Total THs Promotion Amt",
            "expression": " [THs Discount Amt] + [Ths Promotion Estimated Amt]",
            "formatString": "#,0.00"
          },
          {
            "name": "Promotion Sell Out Net Amt",
            "expression": [
              " sum('Fact - Promotion Ths'[Original Net Amt])",
              "/* SUMX(",
              "FILTER(ADDCOLUMNS( SUMMARIZE('Fact - Promotion Ths', 'Fact - Promotion Ths'[Transaction Number], 'Fact - Promotion Ths'[Promotion Code], 'Fact - Promotion Ths'[Is Return Order]), \"_Amt\",  sum('Fact - Promotion Ths'[Original Net Amt])), 'Fact - Promotion Ths'[Is Return Order] = \"N\")",
              ", [_Amt]) */"
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "Promotion Sell Out Qty",
            "expression": " sum('Fact - Promotion Ths'[Original Quantity])",
            "formatString": "#,0.00"
          },
          {
            "name": "Promotion Sell Out Net Amt Test",
            "expression": " CALCULATE([Sell Out Net Amt], ALL('Dim - Promotion Ths'))"
          },
          {
            "name": "THs Discount Amt",
            "expression": " SUM('Fact - Promotion Ths'[Discount Net Amt])",
            "formatString": "#,0.00"
          }
        ]
      },
      {
        "name": "Dim - Store",
        "columns": [
          {
            "name": "STORE_WID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "STORE_WID"
          },
          {
            "name": "Store Code",
            "dataType": "string",
            "sourceColumn": "Store Code"
          },
          {
            "name": "Store Name",
            "dataType": "string",
            "sourceColumn": "Store Name"
          },
          {
            "name": "Adress",
            "dataType": "string",
            "sourceColumn": "Adress"
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City"
          },
          {
            "name": "Post Code",
            "dataType": "string",
            "sourceColumn": "Post Code"
          },
          {
            "name": "Location Code",
            "dataType": "string",
            "sourceColumn": "Location Code"
          },
          {
            "name": "Store Manager",
            "dataType": "string",
            "sourceColumn": "Store Manager"
          },
          {
            "name": "Store Type",
            "dataType": "string",
            "sourceColumn": "Store Type"
          },
          {
            "name": "Latitude",
            "dataType": "string",
            "sourceColumn": "Latitude"
          },
          {
            "name": "Longtitude",
            "dataType": "string",
            "sourceColumn": "Longtitude"
          },
          {
            "name": "Store Status",
            "dataType": "string",
            "sourceColumn": "Store Status"
          },
          {
            "name": "First Order Date",
            "dataType": "dateTime",
            "sourceColumn": "First Order Date"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_STORE_D = Source{[Schema=\"dbo\",Item=\"VW_STORE_D\"]}[Data]",
                "in",
                "    dbo_VW_STORE_D"
              ]
            }
          }
        ]
      },
      {
        "name": "Dim - Member Ths",
        "columns": [
          {
            "name": "MEMBER_WID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MEMBER_WID"
          },
          {
            "name": "Member Card Code",
            "dataType": "string",
            "sourceColumn": "Member Card Code"
          },
          {
            "name": "Club Code",
            "dataType": "string",
            "sourceColumn": "Club Code"
          },
          {
            "name": "Club Name",
            "dataType": "string",
            "sourceColumn": "Club Name"
          },
          {
            "name": "Scheme Code",
            "dataType": "string",
            "sourceColumn": "Scheme Code"
          },
          {
            "name": "Scheme Name",
            "dataType": "string",
            "sourceColumn": "Scheme Name"
          },
          {
            "name": "Scheme Update Sequence",
            "dataType": "string",
            "sourceColumn": "Scheme Update Sequence"
          },
          {
            "name": "Scheme Point For Update",
            "dataType": "string",
            "sourceColumn": "Scheme Point For Update"
          },
          {
            "name": "Next Scheme",
            "dataType": "string",
            "sourceColumn": "Next Scheme"
          },
          {
            "name": "Member Account Code",
            "dataType": "string",
            "sourceColumn": "Member Account Code"
          },
          {
            "name": "Member Account Name",
            "dataType": "string",
            "sourceColumn": "Member Account Name"
          },
          {
            "name": "Member Account Status",
            "dataType": "string",
            "sourceColumn": "Member Account Status"
          },
          {
            "name": "Member Account Type",
            "dataType": "string",
            "sourceColumn": "Member Account Type"
          },
          {
            "name": "Member Contact Number",
            "dataType": "string",
            "sourceColumn": "Member Contact Number"
          },
          {
            "name": "Member Contact Name",
            "dataType": "string",
            "sourceColumn": "Member Contact Name"
          },
          {
            "name": "Member Contact Search Name",
            "dataType": "string",
            "sourceColumn": "Member Contact Search Name"
          },
          {
            "name": "Member Contact Address",
            "dataType": "string",
            "sourceColumn": "Member Contact Address"
          },
          {
            "name": "Member Contact Address 2",
            "dataType": "string",
            "sourceColumn": "Member Contact Address 2"
          },
          {
            "name": "Member Contact City",
            "dataType": "string",
            "sourceColumn": "Member Contact City"
          },
          {
            "name": "Member Contact Country",
            "dataType": "string",
            "sourceColumn": "Member Contact Country"
          },
          {
            "name": "Member Contact Post Code",
            "dataType": "string",
            "sourceColumn": "Member Contact Post Code"
          },
          {
            "name": "Member Contact Email",
            "dataType": "string",
            "sourceColumn": "Member Contact Email"
          },
          {
            "name": "Member Contact Phone",
            "dataType": "string",
            "sourceColumn": "Member Contact Phone"
          },
          {
            "name": "Member Contact Gender",
            "dataType": "string",
            "sourceColumn": "Member Contact Gender"
          },
          {
            "name": "Member Contact Birthday",
            "dataType": "dateTime",
            "sourceColumn": "Member Contact Birthday"
          },
          {
            "name": "Card Status",
            "dataType": "string",
            "sourceColumn": "Card Status"
          },
          {
            "name": "Card Linked To Account",
            "dataType": "string",
            "sourceColumn": "Card Linked To Account"
          },
          {
            "name": "Card Number Series",
            "dataType": "string",
            "sourceColumn": "Card Number Series"
          },
          {
            "name": "Points",
            "dataType": "string",
            "sourceColumn": "Points"
          },
          {
            "name": "First Order Date",
            "dataType": "dateTime",
            "sourceColumn": "First Order Date"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_MEMBER_LS_D = Source{[Schema=\"dbo\",Item=\"VW_MEMBER_LS_D\"]}[Data]",
                "in",
                "    dbo_VW_MEMBER_LS_D"
              ]
            }
          }
        ]
      },
      {
        "name": "Selection Amt Qty",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Abb",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Value"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Value",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value2]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "{(\"Amt (+VAT)\",\"1\"),(\"Amt (-VAT)\",\"2\"),(\"Qty - Carton\",\"3\"),(\"Qty - Kg\",\"4\")}"
            }
          }
        ]
      },
      {
        "name": "Selection AOP Target",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Value",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "{\"AOP\",\"AOP Rev\",\"Target\"}"
            }
          }
        ]
      },
      {
        "name": "Fact - Club Program",
        "columns": [
          {
            "name": "DATE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DATE_WID"
          },
          {
            "name": "DISTRIBUTOR_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DISTRIBUTOR_WID"
          },
          {
            "name": "OUTLET_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OUTLET_WID"
          },
          {
            "name": "PRODUCT_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PRODUCT_WID"
          },
          {
            "name": "SALESFORCE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SALESFORCE_WID"
          },
          {
            "name": "SALES_TERRITORY_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SALES_TERRITORY_WID"
          },
          {
            "name": "CHANNEL_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CHANNEL_WID"
          },
          {
            "name": "Distributor Id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Distributor Id"
          },
          {
            "name": "Outlet Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Outlet Code"
          },
          {
            "name": "Customer Location Id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Customer Location Id"
          },
          {
            "name": "Product Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product Code"
          },
          {
            "name": "Register Date",
            "dataType": "dateTime",
            "sourceColumn": "Register Date"
          },
          {
            "name": "Order Qty",
            "dataType": "double",
            "sourceColumn": "Order Qty"
          },
          {
            "name": "Gross Amt",
            "dataType": "double",
            "sourceColumn": "Gross Amt"
          },
          {
            "name": "Net Amt",
            "dataType": "double",
            "sourceColumn": "Net Amt"
          },
          {
            "name": "CLUB_PROGRAM_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CLUB_PROGRAM_WID"
          },
          {
            "name": "Program Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Program Code"
          },
          {
            "name": "Freeze Assigned Date",
            "dataType": "int64",
            "sourceColumn": "Freeze Assigned Date"
          },
          {
            "name": "Cooler Assigned Date",
            "dataType": "int64",
            "sourceColumn": "Cooler Assigned Date"
          },
          {
            "name": "PRODUCT_CODE",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PRODUCT_CODE"
          },
          {
            "name": "PRODUCT_NAME",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PRODUCT_NAME"
          },
          {
            "name": "Is Pass Club Program",
            "dataType": "string",
            "sourceColumn": "Is Pass Club Program"
          }
        ],
        "partitions": [
          {
            "name": "Part202103",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20210301 and [DATE_WID] < 20210401)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data]",
                  "in",
                  "    dbo_VW_CLUB_PROGRAM_REGISTER_F</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202101",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20210101 and [DATE_WID] < 20210201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20210101 and [DATE_WID] < 20210201)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202102",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20210201 and [DATE_WID] < 20210301)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20210201 and [DATE_WID] < 20210301)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202104",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20210401 and [DATE_WID] < 20210501)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20210401 and [DATE_WID] < 20210501)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202105",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20210501 and [DATE_WID] < 20210601)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20210501 and [DATE_WID] < 20210601)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202106",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20210601 and [DATE_WID] < 20210701)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20210601 and [DATE_WID] < 20210701)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202107",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20210701 and [DATE_WID] < 20210801)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20210701 and [DATE_WID] < 20210801)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202108",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20210801 and [DATE_WID] < 20210901)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20210801 and [DATE_WID] < 20210901)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202109",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20210901 and [DATE_WID] < 20211001)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20210901 and [DATE_WID] < 20211001)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202110",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20211001 and [DATE_WID] < 20211101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20211001 and [DATE_WID] < 20211101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202111",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20211101 and [DATE_WID] < 20211201)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20211101 and [DATE_WID] < 20211201)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202112",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20211201 and [DATE_WID] < 20220101)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_CLUB_PROGRAM_REGISTER_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_PROGRAM_REGISTER_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_CLUB_PROGRAM_REGISTER_F, each [DATE_WID] >= 20211201 and [DATE_WID] < 20220101)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "# of Club ASO Buy",
            "expression": [
              "",
              "var _ClubPef = FILTER(ADDCOLUMNS(SUMMARIZE('Fact - Club Program', 'Fact - Club Program'[Distributor Id], 'Fact - Club Program'[Outlet Code]), \"_amt\", sum('Fact - Club Program'[Gross Amt])), [_amt] > 0)",
              "return ",
              "COUNTROWS(_ClubPef)"
            ],
            "formatString": "#,0"
          },
          {
            "name": "# of Club ASO not Buy",
            "expression": [
              " ",
              "var _ClubPef = FILTER(ADDCOLUMNS(SUMMARIZE('Fact - Club Program', 'Fact - Club Program'[Distributor Id], 'Fact - Club Program'[Outlet Code]), \"_amt\", sum('Fact - Club Program'[Gross Amt])), [_amt] = 0)",
              "return ",
              "COUNTROWS(_ClubPef)"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Club Sell Out Amt",
            "expression": [
              " SUM('Fact - Club Program'[Gross Amt])/*var _ClubPerf =  ADDCOLUMNS(SUMMARIZE('Fact - Club Program', 'Fact - Club Program'[Distributor Id], 'Fact - Club Program'[Outlet Code], 'Fact - Club Program'[DATE_WID]),\"_amt\", max( 'Fact - Club Program'[Gross Amt]))",
              "return",
              "SUMX(_ClubPerf, [_amt]) */"
            ],
            "formatString": "#,0"
          },
          {
            "name": "Club Sell Out Qty",
            "expression": [
              " SUM('Fact - Club Program'[Order Qty])",
              "/*var _ClubPerf =  ADDCOLUMNS(SUMMARIZE('Fact - Club Program', 'Fact - Club Program'[Distributor Id], 'Fact - Club Program'[Outlet Code], 'Fact - Club Program'[DATE_WID]),\"_qty\", max( 'Fact - Club Program'[Order Qty]))",
              "return",
              "SUMX(_ClubPerf, [_qty]) */"
            ],
            "formatString": "#,0"
          },
          {
            "name": "# of Club ASO Active",
            "expression": [
              " ",
              "var _Club = SUMMARIZE('Fact - Club Program', 'Fact - Club Program'[Distributor Id], 'Fact - Club Program'[Outlet Code])",
              "return ",
              "COUNTROWS(_Club)"
            ],
            "formatString": "#,0"
          },
          {
            "name": "% Club ASO Buy vs Active",
            "expression": " DIVIDE([# of Club ASO Buy], [# of Club ASO Active])",
            "formatString": "#,0.0%;-#,0.0%;#,0.0%"
          },
          {
            "name": "% ASO not buy/ ASO active",
            "expression": " DIVIDE([# of Club ASO not Buy], [# of Club ASO Active])",
            "formatString": "#,0.00%;-#,0.00%;#,0.00%"
          },
          {
            "name": "Target Club Sell out",
            "expression": " SUM('Fact - Club Target'[Amt])",
            "formatString": "#,0"
          },
          {
            "name": "# of Club ASO of Cooler",
            "expression": " CALCULATE([# of Club ASO Active], FILTER('Fact - Club Program', 'Fact - Club Program'[DATE_WID] >= 'Fact - Club Program'[Cooler Assigned Date] && 'Fact - Club Program'[Cooler Assigned Date] <> 0))",
            "formatString": "#,0"
          },
          {
            "name": "# of Club ASO of Freeze",
            "expression": " CALCULATE([# of Club ASO Active], FILTER('Fact - Club Program', 'Fact - Club Program'[DATE_WID] >= 'Fact - Club Program'[Freeze Assigned Date] && 'Fact - Club Program'[Freeze Assigned Date] <> 0))",
            "formatString": "#,0"
          },
          {
            "name": "# of Club SKUs Buy",
            "expression": " COUNT('Fact - Club Program'[Product Code])",
            "formatString": "#,0"
          },
          {
            "name": "Avg Club SKUs per ASO",
            "expression": " DIVIDE([# of Club SKUs Buy], [# of Club ASO Buy])",
            "formatString": "#,0.0"
          },
          {
            "name": "Avg Club sell out/ Cooler",
            "expression": [
              "",
              "VAR ClubSellOutAmtCooler =",
              "    CALCULATE (",
              "        [Club Sell Out Amt],",
              "        FILTER (",
              "            'Fact - Club Program',",
              "            'Fact - Club Program'[DATE_WID] >= 'Fact - Club Program'[Cooler Assigned Date]",
              "                && 'Fact - Club Program'[Cooler Assigned Date] <> 0",
              "        )",
              "    )",
              "RETURN",
              "    DIVIDE ( ClubSellOutAmtCooler, [# of Club ASO of Cooler], BLANK () )"
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "Avg Club sell out/ Freeze",
            "expression": [
              "",
              "VAR ClubSellOutAmtFreeze =",
              "    CALCULATE (",
              "        [Club Sell Out Amt],",
              "        FILTER (",
              "            'Fact - Club Program',",
              "            'Fact - Club Program'[DATE_WID] >= 'Fact - Club Program'[Freeze Assigned Date]",
              "                && 'Fact - Club Program'[Freeze Assigned Date] <> 0",
              "        )",
              "    )",
              "RETURN",
              "    DIVIDE ( ClubSellOutAmtFreeze, [# of Club ASO of Freeze], BLANK () )"
            ],
            "formatString": "#,0.00"
          },
          {
            "name": "Club Sell Out vs Target",
            "expression": " DIVIDE([Club Sell Out Amt], [Target Club Sell out],0)",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Club Sell Out Amt LM",
            "expression": " CALCULATE([Club Sell Out Amt],DATEADD('Dim - Date'[Date],-1,MONTH))"
          },
          {
            "name": "Club Sell Out Qty LM",
            "expression": " CALCULATE([Club Sell Out Qty],DATEADD('Dim - Date'[Date],-1,MONTH))"
          },
          {
            "name": "# of Club ASO Active LM",
            "expression": " CALCULATE([# of Club ASO Active],DATEADD('Dim - Date'[Date],-1,MONTH))",
            "formatString": "#,0"
          },
          {
            "name": "Club Sell Out Amt LY",
            "expression": " CALCULATE([Club Sell Out Amt],SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
            "formatString": "#,0"
          },
          {
            "name": "# of Club ASO Active LY",
            "expression": " CALCULATE([# of Club ASO Active],SAMEPERIODLASTYEAR('Dim - Date'[Date]))",
            "formatString": "#,0"
          },
          {
            "name": "Club Sell Out Amt L2M",
            "expression": " CALCULATE([Club Sell Out Amt],DATEADD('Dim - Date'[Date],-2,MONTH))",
            "formatString": "#,0"
          },
          {
            "name": "Club Sell Out / Total Sell Out",
            "expression": " DIVIDE([Club Sell Out Amt],[Sell Out Amt],0)",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Club Sell Out / Total Sell Out LM",
            "expression": " CALCULATE( [Club Sell Out / Total Sell Out],DATEADD('Dim - Date'[Date],-1,MONTH))",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "Club Sell Out / Total Sell Out L2M",
            "expression": " CALCULATE( [Club Sell Out / Total Sell Out],DATEADD('Dim - Date'[Date],-2,MONTH))",
            "formatString": "0.0%;-0.0%;0.0%"
          },
          {
            "name": "# of Club SKUs of Cooler",
            "expression": " CALCULATE([# of Club SKUs Buy], FILTER('Fact - Club Program', 'Fact - Club Program'[DATE_WID] >= 'Fact - Club Program'[Cooler Assigned Date] && 'Fact - Club Program'[Cooler Assigned Date] <> 0))",
            "formatString": "#,0"
          },
          {
            "name": "# of Club  SKUs of Freeze",
            "expression": " CALCULATE([# of Club SKUs Buy], FILTER('Fact - Club Program', 'Fact - Club Program'[DATE_WID] >= 'Fact - Club Program'[Freeze Assigned Date] && 'Fact - Club Program'[Freeze Assigned Date] <> 0))",
            "formatString": "#,0"
          },
          {
            "name": "# of Club SKUs Buy LM",
            "expression": " CALCULATE([# of Club SKUs Buy],DATEADD('Dim - Date'[Date],-1,MONTH))",
            "formatString": "#,0"
          },
          {
            "name": "Avg Club SKUs per ASO LM",
            "expression": " CALCULATE([Avg Club SKUs per ASO],DATEADD('Dim - Date'[Date],-1,MONTH))",
            "formatString": "0.0"
          }
        ]
      },
      {
        "name": "Fact - Club Target",
        "columns": [
          {
            "name": "DATE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DATE_WID"
          },
          {
            "name": "CLUB_PROGRAM_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CLUB_PROGRAM_WID"
          },
          {
            "name": "SALES_TERRITORY_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SALES_TERRITORY_WID"
          },
          {
            "name": "Program Code",
            "dataType": "string",
            "sourceColumn": "Program Code"
          },
          {
            "name": "Program Level",
            "dataType": "string",
            "sourceColumn": "Program Level"
          },
          {
            "name": "No Of Customer",
            "dataType": "double",
            "sourceColumn": "No Of Customer"
          },
          {
            "name": "No Of Skus",
            "dataType": "double",
            "sourceColumn": "No Of Skus"
          },
          {
            "name": "Amt",
            "dataType": "double",
            "sourceColumn": "Amt"
          },
          {
            "name": "Qty",
            "dataType": "double",
            "sourceColumn": "Qty"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_CLUB_TARGET_F = Source{[Schema=\"dbo\",Item=\"VW_CLUB_TARGET_F\"]}[Data]",
                "in",
                "    dbo_VW_CLUB_TARGET_F"
              ]
            }
          }
        ]
      },
      {
        "name": "Dim - Sales Type",
        "columns": [
          {
            "name": "SALE_TYPE_WID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SALE_TYPE_WID"
          },
          {
            "name": "Sale Type Code",
            "dataType": "string",
            "sourceColumn": "Sale Type Code"
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SALE_TYPE_LS_D = Source{[Schema=\"dbo\",Item=\"VW_SALE_TYPE_LS_D\"]}[Data]",
                "in",
                "    dbo_VW_SALE_TYPE_LS_D"
              ]
            }
          }
        ]
      },
      {
        "name": "Dim - Time",
        "columns": [
          {
            "name": "time_wid",
            "dataType": "int64",
            "sourceColumn": "time_wid"
          },
          {
            "name": "Hour",
            "dataType": "int64",
            "sourceColumn": "Hour"
          },
          {
            "name": "Hour 12",
            "dataType": "int64",
            "sourceColumn": "Hour 12"
          },
          {
            "name": "TT",
            "dataType": "string",
            "sourceColumn": "TT"
          },
          {
            "name": "Minute",
            "dataType": "int64",
            "sourceColumn": "Minute"
          },
          {
            "name": "Time Group",
            "dataType": "string",
            "sourceColumn": "Time Group",
            "sortByColumn": "Time Group Sort"
          },
          {
            "name": "Time Group Sort",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Time Group Sort"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_TIME_D = Source{[Schema=\"dbo\",Item=\"VW_TIME_D\"]}[Data]",
                "in",
                "    dbo_VW_TIME_D"
              ]
            }
          }
        ]
      },
      {
        "name": "Fact - POSM Assignment",
        "columns": [
          {
            "name": "PRODUCT_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PRODUCT_WID"
          },
          {
            "name": "OUTLET_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OUTLET_WID"
          },
          {
            "name": "Serial Number",
            "dataType": "string",
            "sourceColumn": "Serial Number"
          },
          {
            "name": "Asset Code",
            "dataType": "string",
            "sourceColumn": "Asset Code"
          },
          {
            "name": "DATE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DATE_WID"
          },
          {
            "name": "DISTRIBUTOR_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DISTRIBUTOR_WID"
          },
          {
            "name": "SALESFORCE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SALESFORCE_WID"
          },
          {
            "name": "SALES_TERRITORY_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SALES_TERRITORY_WID"
          },
          {
            "name": "CHANNEL_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CHANNEL_WID"
          },
          {
            "name": "Distributor Id",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Distributor Id"
          },
          {
            "name": "OUTLET_CODE",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "OUTLET_CODE"
          },
          {
            "name": "Product ID",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product ID"
          },
          {
            "name": "Asset Type",
            "dataType": "string",
            "sourceColumn": "Asset Type"
          },
          {
            "name": "Asset Type Name",
            "dataType": "string",
            "sourceColumn": "Asset Type Name"
          },
          {
            "name": "ORDER_QTY",
            "dataType": "double",
            "sourceColumn": "ORDER_QTY"
          },
          {
            "name": "GROSS_AMT",
            "dataType": "double",
            "sourceColumn": "GROSS_AMT"
          },
          {
            "name": "NET_AMT",
            "dataType": "double",
            "sourceColumn": "NET_AMT"
          }
        ],
        "partitions": [
          {
            "name": "Part202109",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_POSM_ASSIGNMENT_F = Source{[Schema=\"dbo\",Item=\"VW_POSM_ASSIGNMENT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_POSM_ASSIGNMENT_F, each [DATE_WID] = 20210901)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_POSM_ASSIGNMENT_F = Source{[Schema=\"dbo\",Item=\"VW_POSM_ASSIGNMENT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_POSM_ASSIGNMENT_F, each [DATE_WID] = 20210901)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          },
          {
            "name": "Part202110",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_POSM_ASSIGNMENT_F = Source{[Schema=\"dbo\",Item=\"VW_POSM_ASSIGNMENT_F\"]}[Data],",
                "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_POSM_ASSIGNMENT_F, each [DATE_WID] = 20211001)",
                "in",
                "    #\"Filtered Rows\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                  "    dbo_VW_POSM_ASSIGNMENT_F = Source{[Schema=\"dbo\",Item=\"VW_POSM_ASSIGNMENT_F\"]}[Data],",
                  "    #\"Filtered Rows\" = Table.SelectRows(dbo_VW_POSM_ASSIGNMENT_F, each [DATE_WID] = 20211001)",
                  "in",
                  "    #\"Filtered Rows\"</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ]
      },
      {
        "name": "Dim - Shelf Life",
        "columns": [
          {
            "name": "SHELFLIFE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SHELFLIFE_WID"
          },
          {
            "name": "Shelf Life Code",
            "dataType": "string",
            "sourceColumn": "Shelf Life Code",
            "sortByColumn": "SHELFLIFE_WID"
          },
          {
            "name": "Shelf Life Name",
            "dataType": "string",
            "sourceColumn": "Shelf Life Name"
          },
          {
            "name": "Shelf Life Group",
            "dataType": "string",
            "sourceColumn": "Shelf Life Group",
            "sortByColumn": "Shelf Life Group Order"
          },
          {
            "name": "Shelf Life From",
            "dataType": "int64",
            "sourceColumn": "Shelf Life From"
          },
          {
            "name": "Shelf Life To",
            "dataType": "int64",
            "sourceColumn": "Shelf Life To"
          },
          {
            "name": "Shelf Life Group Order",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Shelf Life Group Order"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_SHELFLIFE_D = Source{[Schema=\"dbo\",Item=\"VW_SHELFLIFE_D\"]}[Data]",
                "in",
                "    dbo_VW_SHELFLIFE_D"
              ]
            }
          }
        ]
      },
      {
        "name": "Selection Members",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Value",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "{\"# of Members\",",
                "\"# of Active Members\",",
                "\"# of New Members\",",
                "\"# of Repurchased Members\",",
                "\"# of Repeated Members\",",
                "\"# of Inactive Members\"}"
              ]
            }
          }
        ]
      },
      {
        "name": "Dim - Route Type",
        "columns": [
          {
            "name": "ROUTE_TYPE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ROUTE_TYPE_WID"
          },
          {
            "name": "Route Type Code",
            "dataType": "string",
            "sourceColumn": "Route Type Code"
          },
          {
            "name": "Route Type Name",
            "dataType": "string",
            "sourceColumn": "Route Type Name"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_ROUTE_TYPE_D = Source{[Schema=\"dbo\",Item=\"VW_ROUTE_TYPE_D\"]}[Data]",
                "in",
                "    dbo_VW_ROUTE_TYPE_D"
              ]
            }
          }
        ]
      },
      {
        "name": "Amt Range",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Value",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "  GENERATESERIES(0,500000000,1000000)"
            }
          }
        ]
      },
      {
        "name": "Dim - In Location",
        "columns": [
          {
            "name": "INLOCATION_WID",
            "dataType": "string",
            "sourceColumn": "INLOCATION_WID"
          },
          {
            "name": "Location Id",
            "dataType": "string",
            "sourceColumn": "Location Id"
          },
          {
            "name": "Location Code",
            "dataType": "string",
            "sourceColumn": "Location Code"
          },
          {
            "name": "Location Name",
            "dataType": "string",
            "sourceColumn": "Location Name"
          },
          {
            "name": "Is Active",
            "dataType": "string",
            "sourceColumn": "Is Active"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_INLOCATION_D = Source{[Schema=\"dbo\",Item=\"VW_INLOCATION_D\"]}[Data]",
                "in",
                "    dbo_VW_INLOCATION_D"
              ]
            }
          }
        ]
      },
      {
        "name": "Distributor Views",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Value1",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]",
            "sortByColumn": "Value2"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Value2",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value2]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "{",
                "(\"# Route\",1),",
                "(\"AVG Sell out by Month\",2),",
                "(\"AVG Sell out by Route\",3),",
                "(\"ASO\",4),",
                "(\"ASO/Route\",5),",
                "(\"ASO/MCP\",6),",
                "(\"ASO_DONG LANH\",7),",
                "(\"ASO_KHO\",8),",
                "(\"ASO_LANH\",9),",
                "(\"ASO_ON\",10),",
                "(\"ASO_OFF\",11),",
                "(\"VPO\",12),",
                "(\"Strike rate\",13),",
                "(\"Dropsize\",14),",
                "(\"SKUs/DH\",15),",
                "(\"Call/Route/day- Act\",16)",
                "}"
              ]
            }
          }
        ]
      },
      {
        "name": "Selection ASO VPO",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Rank",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Value",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value2]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "{(1,\"# of ASO\"),",
                "(2,\"VPO\"),",
                "(3,\"# of New ASO\"),",
                "(4,\"# of Repeated ASO\"),",
                "(5,\"VPO of Repeated ASO\"),",
                "(6,\"# of Repurchase ASO\"),",
                "(7,\"VPO of Repurchase ASO\")",
                "}",
                "",
                ""
              ]
            }
          }
        ]
      },
      {
        "name": "Fact - Forecast",
        "columns": [
          {
            "name": "DATE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DATE_WID"
          },
          {
            "name": "DISTRIBUTOR_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DISTRIBUTOR_WID"
          },
          {
            "name": "STORE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "STORE_WID"
          },
          {
            "name": "PRODUCT_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PRODUCT_WID"
          },
          {
            "name": "SALES_TERRITORY_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SALES_TERRITORY_WID"
          },
          {
            "name": "Distributor Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Distributor Code"
          },
          {
            "name": "Product Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product Code"
          },
          {
            "name": "UOM",
            "dataType": "string",
            "sourceColumn": "UOM"
          },
          {
            "name": "Forecat Type",
            "dataType": "string",
            "sourceColumn": "Forecat Type"
          },
          {
            "name": "Forecat Value",
            "dataType": "double",
            "sourceColumn": "Forecat Value"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_FORECAT_F = Source{[Schema=\"dbo\",Item=\"VW_FORECAT_F\"]}[Data]",
                "in",
                "    dbo_VW_FORECAT_F"
              ]
            }
          }
        ]
      },
      {
        "name": "Dim - Order Amt Range",
        "columns": [
          {
            "name": "RANGE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "RANGE_WID"
          },
          {
            "name": "From Value",
            "dataType": "int64",
            "sourceColumn": "From Value"
          },
          {
            "name": "To Value",
            "dataType": "int64",
            "sourceColumn": "To Value"
          },
          {
            "name": "Group Name",
            "dataType": "string",
            "sourceColumn": "Group Name"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_AMT_RANGE_ORDER_D = Source{[Schema=\"dbo\",Item=\"VW_AMT_RANGE_ORDER_D\"]}[Data]",
                "in",
                "    dbo_VW_AMT_RANGE_ORDER_D"
              ]
            }
          }
        ]
      },
      {
        "name": "Dim - Store Amt Range",
        "columns": [
          {
            "name": "RANGE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "RANGE_WID"
          },
          {
            "name": "From Value",
            "dataType": "int64",
            "sourceColumn": "From Value"
          },
          {
            "name": "To Value",
            "dataType": "int64",
            "sourceColumn": "To Value"
          },
          {
            "name": "Group Name",
            "dataType": "string",
            "sourceColumn": "Group Name",
            "sortByColumn": "Group Name Sort"
          },
          {
            "name": "Group Name Sort",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Group Name Sort"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_AMT_RANGE_STORE_D = Source{[Schema=\"dbo\",Item=\"VW_AMT_RANGE_STORE_D\"]}[Data]",
                "in",
                "    dbo_VW_AMT_RANGE_STORE_D"
              ]
            }
          }
        ]
      },
      {
        "name": "Dim - Store Aging",
        "columns": [
          {
            "name": "No of Day",
            "dataType": "int64",
            "sourceColumn": "No of Day"
          },
          {
            "name": "No of Year",
            "dataType": "int64",
            "sourceColumn": "No of Year"
          },
          {
            "name": "Group",
            "dataType": "string",
            "sourceColumn": "Group",
            "sortByColumn": "Group Sort"
          },
          {
            "name": "Group Sort",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Group Sort"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_STORE_AGING_D = Source{[Schema=\"dbo\",Item=\"VW_STORE_AGING_D\"]}[Data]",
                "in",
                "    dbo_VW_STORE_AGING_D"
              ]
            }
          }
        ]
      },
      {
        "name": "Dim - Trailing Date",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "DATE_WID",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "DATE_WID"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "Date"
          },
          {
            "name": "Date Number",
            "dataType": "int64",
            "sourceColumn": "Date Number"
          },
          {
            "name": "Date Name",
            "dataType": "string",
            "sourceColumn": "Date Name"
          },
          {
            "name": "Week Of Month",
            "dataType": "int64",
            "sourceColumn": "Week Of Month"
          },
          {
            "name": "Week Of Year",
            "dataType": "string",
            "sourceColumn": "Week Of Year"
          },
          {
            "name": "Week Number",
            "dataType": "int64",
            "sourceColumn": "Week Number"
          },
          {
            "name": "Week Name",
            "dataType": "string",
            "sourceColumn": "Week Name"
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "sortByColumn": "Month Number"
          },
          {
            "name": "Month Number",
            "dataType": "int64",
            "sourceColumn": "Month Number"
          },
          {
            "name": "Month Name",
            "dataType": "string",
            "sourceColumn": "Month Name"
          },
          {
            "name": "Quarter",
            "dataType": "string",
            "sourceColumn": "Quarter"
          },
          {
            "name": "Quarter Number",
            "dataType": "int64",
            "sourceColumn": "Quarter Number"
          },
          {
            "name": "Quarter Name",
            "dataType": "string",
            "sourceColumn": "Quarter Name"
          },
          {
            "name": "Year",
            "dataType": "int64",
            "sourceColumn": "Year"
          },
          {
            "name": "Is Holiday",
            "dataType": "string",
            "sourceColumn": "Is Holiday"
          },
          {
            "name": "Is Holiday NPP",
            "dataType": "string",
            "sourceColumn": "Is Holiday NPP"
          },
          {
            "name": "Is Holiday THS",
            "dataType": "string",
            "sourceColumn": "Is Holiday THS"
          },
          {
            "name": "Holiday",
            "dataType": "string",
            "sourceColumn": "Holiday"
          },
          {
            "name": "Day Of Week VN",
            "dataType": "string",
            "sourceColumn": "Day Of Week VN"
          },
          {
            "name": "Period Type",
            "dataType": "string",
            "sourceColumn": "Period Type"
          },
          {
            "name": "Period Type Order",
            "dataType": "int64",
            "sourceColumn": "Period Type Order"
          },
          {
            "name": "Closing Flag",
            "dataType": "string",
            "sourceColumn": "Closing Flag"
          },
          {
            "name": "Date Type",
            "dataType": "string",
            "sourceColumn": "Date Type"
          },
          {
            "name": "Back 30 Working Day",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Back 30 Working Day"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    dbo_VW_CALENDAR_D = Source{[Schema=\"dbo\",Item=\"VW_CALENDAR_D\"]}[Data]",
                "in",
                "    dbo_VW_CALENDAR_D"
              ]
            }
          }
        ]
      },
      {
        "name": "RLS - Channel",
        "isHidden": true,
        "columns": [
          {
            "name": "CHANNEL_WID",
            "dataType": "int64",
            "sourceColumn": "CHANNEL_WID"
          },
          {
            "name": "User ID",
            "dataType": "string",
            "sourceColumn": "User ID"
          },
          {
            "name": "User Name",
            "dataType": "string",
            "sourceColumn": "User Name"
          },
          {
            "name": "Dimension Name",
            "dataType": "string",
            "sourceColumn": "Dimension Name"
          },
          {
            "name": "Field Name",
            "dataType": "string",
            "sourceColumn": "Field Name"
          },
          {
            "name": "Field Value",
            "dataType": "string",
            "sourceColumn": "Field Value"
          },
          {
            "name": "Notes",
            "dataType": "string",
            "sourceColumn": "Notes"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    DWH_VW_RLS_CHANNEL_D = Source{[Schema=\"DWH\",Item=\"VW_RLS_CHANNEL_D\"]}[Data]",
                "in",
                "    DWH_VW_RLS_CHANNEL_D"
              ]
            }
          }
        ]
      },
      {
        "name": "RLS - Sales Territory",
        "isHidden": true,
        "columns": [
          {
            "name": "SALES_TERRITORY_WID",
            "dataType": "int64",
            "sourceColumn": "SALES_TERRITORY_WID"
          },
          {
            "name": "User ID",
            "dataType": "string",
            "sourceColumn": "User ID"
          },
          {
            "name": "User Name",
            "dataType": "string",
            "sourceColumn": "User Name"
          },
          {
            "name": "Dimension Name",
            "dataType": "string",
            "sourceColumn": "Dimension Name"
          },
          {
            "name": "Field Name",
            "dataType": "string",
            "sourceColumn": "Field Name"
          },
          {
            "name": "Field Value",
            "dataType": "string",
            "sourceColumn": "Field Value"
          },
          {
            "name": "Notes",
            "dataType": "string",
            "sourceColumn": "Notes"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/thfssynapsedev sql azuresynapse net;dwhdev\",",
                "    DWH_VW_RLS_SALES_TERRITORY_D = Source{[Schema=\"DWH\",Item=\"VW_RLS_SALES_TERRITORY_D\"]}[Data]",
                "in",
                "    DWH_VW_RLS_SALES_TERRITORY_D"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "245b1863-9af8-47f2-8b5d-7e75c6fe7552",
        "fromTable": "Fact - Sell Out",
        "fromColumn": "OUTLET_WID",
        "toTable": "Dim - Outlet",
        "toColumn": "OUTLET_WID"
      },
      {
        "name": "93acf8a2-a609-49a3-b415-7c3a53e3cc9d",
        "fromTable": "Fact - Sell Out",
        "fromColumn": "DISTRIBUTOR_WID",
        "toTable": "Dim - Distributor",
        "toColumn": "DISTRIBUTOR_WID"
      },
      {
        "name": "d256313b-e689-44a3-a0e1-25a64866e026",
        "fromTable": "Fact - Sell Out",
        "fromColumn": "DATE_WID",
        "toTable": "Dim - Date",
        "toColumn": "DATE_WID"
      },
      {
        "name": "3ebe6b99-ba43-416c-8fe3-f8c4ddf61f3d",
        "fromTable": "Fact - Sell Out",
        "fromColumn": "PRODUCT_WID",
        "toTable": "Dim - Product",
        "toColumn": "PRODUCT_WID"
      },
      {
        "name": "753dd0af-a016-4c81-b7ee-912b6825a0b6",
        "fromTable": "Fact - Sell Out",
        "fromColumn": "SALESFORCE_WID",
        "toTable": "Dim - Sales Force",
        "toColumn": "SALESFORCE_WID"
      },
      {
        "name": "42388ebf-d4ef-4c8a-b4bf-1bf93c0c75c5",
        "fromTable": "Fact - MCP",
        "fromColumn": "DATE_WID",
        "toTable": "Dim - Date",
        "toColumn": "DATE_WID"
      },
      {
        "name": "f312d1c3-2654-423b-9df6-5a1e74ab9011",
        "fromTable": "Fact - MCP",
        "fromColumn": "OUTLET_WID",
        "toTable": "Dim - Outlet",
        "toColumn": "OUTLET_WID"
      },
      {
        "name": "0c072440-4a1f-4967-8857-2be71a822ce0",
        "fromTable": "Fact - MCP",
        "fromColumn": "SALES_FORCE_WID",
        "toTable": "Dim - Sales Force",
        "toColumn": "SALESFORCE_WID"
      },
      {
        "name": "a91bfa7e-c3c8-40eb-b117-30a953408b4e",
        "fromTable": "Fact - Inventory",
        "fromColumn": "DATE_WID",
        "toTable": "Dim - Date",
        "toColumn": "DATE_WID"
      },
      {
        "name": "5bc2ccc1-e844-4e4d-9b4d-880c85e6c1e4",
        "fromTable": "Fact - Inventory",
        "fromColumn": "PRODUCT_WID",
        "toTable": "Dim - Product",
        "toColumn": "PRODUCT_WID"
      },
      {
        "name": "6c0b9025-c144-4ce5-9f07-c3e5f096dc8d",
        "fromTable": "Fact - Sell Out",
        "fromColumn": "CHANNEL_WID",
        "toTable": "Dim - Channel",
        "toColumn": "CHANNEL_WID"
      },
      {
        "name": "30ed4164-81f0-4a43-87f8-376a745a0f8a",
        "fromTable": "Fact - MCP",
        "fromColumn": "CHANNEL_WID",
        "toTable": "Dim - Channel",
        "toColumn": "CHANNEL_WID"
      },
      {
        "name": "4c0d90c4-062c-43d1-8871-90884086f4c6",
        "fromTable": "Fact - Inventory",
        "fromColumn": "CHANNEL_WID",
        "toTable": "Dim - Channel",
        "toColumn": "CHANNEL_WID"
      },
      {
        "name": "532e80dd-0d91-4706-a565-5fd887a2d919",
        "fromTable": "Fact - Actual Visit",
        "fromColumn": "DATE_WID",
        "toTable": "Dim - Date",
        "toColumn": "DATE_WID"
      },
      {
        "name": "6c231531-1fde-418d-8dd8-d22d897452fd",
        "fromTable": "Fact - Actual Visit",
        "fromColumn": "DISTRIBUTOR_WID",
        "toTable": "Dim - Distributor",
        "toColumn": "DISTRIBUTOR_WID"
      },
      {
        "name": "cc7e3069-cff1-4a9f-9e80-d8a92b6ede22",
        "fromTable": "Fact - Actual Visit",
        "fromColumn": "OUTLET_WID",
        "toTable": "Dim - Outlet",
        "toColumn": "OUTLET_WID"
      },
      {
        "name": "45fdf74a-ba5a-4dd8-9883-7b09058bb32f",
        "fromTable": "Fact - Actual Visit",
        "fromColumn": "SALES_FORCE_WID",
        "toTable": "Dim - Sales Force",
        "toColumn": "SALESFORCE_WID"
      },
      {
        "name": "7ca958ef-07f5-4343-b179-026185951410",
        "fromTable": "Fact - AOP",
        "fromColumn": "DATE_WID",
        "toTable": "Dim - Date",
        "toColumn": "DATE_WID"
      },
      {
        "name": "f9b4ef8e-cfa3-436b-93fc-755441c29ded",
        "fromTable": "Fact - AOP",
        "fromColumn": "DISTRIBUTOR_WID",
        "toTable": "Dim - Distributor",
        "toColumn": "DISTRIBUTOR_WID"
      },
      {
        "name": "5d4ae944-ab59-479e-bc95-de95c704ca87",
        "fromTable": "Fact - AOP",
        "fromColumn": "SALES_TERRITORY_WID",
        "toTable": "Dim - Sales Territory",
        "toColumn": "SALES_TERRITORY_WID"
      },
      {
        "name": "44c76025-feaf-4b49-99f1-6c1bf30e96ea",
        "fromTable": "Fact - AOP",
        "fromColumn": "PRODUCT_WID",
        "toTable": "Dim - Product",
        "toColumn": "PRODUCT_WID"
      },
      {
        "name": "c5a094c0-04c9-464b-bbcb-b6612d7a7c66",
        "fromTable": "Fact - Target",
        "fromColumn": "DATE_WID",
        "toTable": "Dim - Date",
        "toColumn": "DATE_WID"
      },
      {
        "name": "d0dfa59e-131c-46f0-9652-5e9c9c958226",
        "fromTable": "Fact - Target",
        "fromColumn": "PRODUCT_WID",
        "toTable": "Dim - Product",
        "toColumn": "PRODUCT_WID"
      },
      {
        "name": "903f6747-15f7-4ead-a79b-bee4825a5d00",
        "fromTable": "Fact - Target",
        "fromColumn": "SALES_TERRITORY_WID",
        "toTable": "Dim - Sales Territory",
        "toColumn": "SALES_TERRITORY_WID"
      },
      {
        "name": "6c5372ee-d539-4c11-8a9c-342c6e3f921b",
        "fromTable": "Fact - DOS Target",
        "fromColumn": "DATE_WID",
        "toTable": "Dim - Date",
        "toColumn": "DATE_WID"
      },
      {
        "name": "c9598d91-78dd-4eb8-9e5c-4ca5f9536ed6",
        "fromTable": "Fact - DOS Target",
        "fromColumn": "DISTRIBUTOR_WID",
        "toTable": "Dim - Distributor",
        "toColumn": "DISTRIBUTOR_WID"
      },
      {
        "name": "9b57ffd4-71cc-41c5-8f6f-7e158ffaec2c",
        "fromTable": "Fact - DOS Target",
        "fromColumn": "SALES_TERRITORY_WID",
        "toTable": "Dim - Sales Territory",
        "toColumn": "SALES_TERRITORY_WID"
      },
      {
        "name": "2d4d4a10-20cf-436d-af5f-f4ea77d6328a",
        "fromTable": "Fact - Sell Out",
        "fromColumn": "TENDER_WID",
        "toTable": "Dim - Tender",
        "toColumn": "TENDER_TYPE_WID"
      },
      {
        "name": "15bfcaaa-8ef0-426a-be7c-e87cdfc1a11a",
        "fromTable": "Fact - Actual Visit",
        "fromColumn": "CHANNEL_WID",
        "toTable": "Dim - Channel",
        "toColumn": "CHANNEL_WID"
      },
      {
        "name": "28371d54-cded-40a8-baec-2307df5e0967",
        "fromTable": "Fact - Sell Out",
        "fromColumn": "STORE_WID",
        "toTable": "Dim - Store",
        "toColumn": "STORE_WID"
      },
      {
        "name": "249c0b17-b677-4749-a11f-7018999baa76",
        "fromTable": "Fact - Sell Out",
        "fromColumn": "PROMOTION_WID",
        "toTable": "Dim - Promotion",
        "toColumn": "PROMOTION_WID"
      },
      {
        "name": "e1fb98e0-37f8-44e9-9caa-d66dcfe5c5c9",
        "fromTable": "Fact - Promotion Ths",
        "fromColumn": "DATE_WID",
        "toTable": "Dim - Date",
        "toColumn": "DATE_WID"
      },
      {
        "name": "98eac97c-a9ea-4809-8ad1-5e8888934444",
        "fromTable": "Fact - Promotion Ths",
        "fromColumn": "PRODUCT_WID",
        "toTable": "Dim - Product",
        "toColumn": "PRODUCT_WID"
      },
      {
        "name": "e3eed661-9e1d-4b05-9063-efd8ffa48dcf",
        "fromTable": "Fact - Sell Out",
        "fromColumn": "MEMBER_WID",
        "toTable": "Dim - Member Ths",
        "toColumn": "MEMBER_WID"
      },
      {
        "name": "c38c3df8-d61b-412c-a15c-408e2a6303fa",
        "fromTable": "Fact - Forecast",
        "fromColumn": "DATE_WID",
        "toTable": "Dim - Date",
        "toColumn": "DATE_WID"
      },
      {
        "name": "62aa87fd-f7d1-4cdf-ad56-dee0f4e69ba8",
        "fromTable": "Fact - Forecast",
        "fromColumn": "PRODUCT_WID",
        "toTable": "Dim - Product",
        "toColumn": "PRODUCT_WID"
      },
      {
        "name": "1ff7c29b-67e2-4b6d-9412-8d5bfce54b18",
        "fromTable": "Fact - Forecast",
        "fromColumn": "SALES_TERRITORY_WID",
        "toTable": "Dim - Sales Territory",
        "toColumn": "SALES_TERRITORY_WID"
      },
      {
        "name": "d6cb13d8-ae28-4e91-a584-990dd4f28a2c",
        "fromTable": "Fact - Forecast",
        "fromColumn": "STORE_WID",
        "toTable": "Dim - Store",
        "toColumn": "STORE_WID"
      },
      {
        "name": "ba527c22-6bc2-435d-a02f-7b83e225df4c",
        "fromTable": "Fact - Forecast",
        "fromColumn": "DISTRIBUTOR_WID",
        "toTable": "Dim - Distributor",
        "toColumn": "DISTRIBUTOR_WID"
      },
      {
        "name": "3cd39da4-32b9-4ce4-bf22-b870e9973d7e",
        "fromTable": "Fact - Order Detail",
        "fromColumn": "CHANNEL_WID",
        "toTable": "Dim - Channel",
        "toColumn": "CHANNEL_WID"
      },
      {
        "name": "cbf73236-c23e-4985-9a2a-e83cdc8a84d8",
        "fromTable": "Fact - Order Detail",
        "fromColumn": "DATE_WID",
        "toTable": "Dim - Date",
        "toColumn": "DATE_WID"
      },
      {
        "name": "ac90871b-023e-4490-b0a8-96af56fac78b",
        "fromTable": "Fact - Order Detail",
        "fromColumn": "DISTRIBUTOR_WID",
        "toTable": "Dim - Distributor",
        "toColumn": "DISTRIBUTOR_WID"
      },
      {
        "name": "58300c35-d7f0-4371-b2b3-1233fa81b687",
        "fromTable": "Fact - Order Detail",
        "fromColumn": "OUTLET_WID",
        "toTable": "Dim - Outlet",
        "toColumn": "OUTLET_WID"
      },
      {
        "name": "33da03dc-6da3-46d8-bfd4-9b8d919ddaba",
        "fromTable": "Fact - Order Detail",
        "fromColumn": "PRODUCT_WID",
        "toTable": "Dim - Product",
        "toColumn": "PRODUCT_WID"
      },
      {
        "name": "d8f9b1ba-7a9b-4074-a3ca-f8b35397b38a",
        "fromTable": "Fact - Target",
        "fromColumn": "DISTRIBUTOR_WID",
        "toTable": "Dim - Distributor",
        "toColumn": "DISTRIBUTOR_WID"
      },
      {
        "name": "200f8b08-5217-409f-9f47-76a60dc3db7d",
        "fromTable": "Fact - Club Program",
        "fromColumn": "CHANNEL_WID",
        "toTable": "Dim - Channel",
        "toColumn": "CHANNEL_WID"
      },
      {
        "name": "16240709-455b-4e6f-bd14-89493707e42e",
        "fromTable": "Fact - Club Program",
        "fromColumn": "DATE_WID",
        "toTable": "Dim - Date",
        "toColumn": "DATE_WID"
      },
      {
        "name": "727d58ce-7442-4732-a9d0-7ac9c02005da",
        "fromTable": "Fact - Club Program",
        "fromColumn": "DISTRIBUTOR_WID",
        "toTable": "Dim - Distributor",
        "toColumn": "DISTRIBUTOR_WID"
      },
      {
        "name": "e92a7c13-2369-4afd-a9fa-e79345a98f10",
        "fromTable": "Fact - Club Program",
        "fromColumn": "OUTLET_WID",
        "toTable": "Dim - Outlet",
        "toColumn": "OUTLET_WID"
      },
      {
        "name": "bc1a970d-f328-47d6-a184-8718e67ec543",
        "fromTable": "Fact - Club Program",
        "fromColumn": "SALESFORCE_WID",
        "toTable": "Dim - Sales Force",
        "toColumn": "SALESFORCE_WID"
      },
      {
        "name": "464340f2-a78b-4b43-87d5-03681bbafdb5",
        "fromTable": "Fact - Club Program",
        "fromColumn": "CLUB_PROGRAM_WID",
        "toTable": "Dim - Club Program",
        "toColumn": "CLUB_PROGRAM_WID"
      },
      {
        "name": "a175a903-b946-42d3-86ec-1e47244e7582",
        "fromTable": "Fact - Inventory Ths",
        "fromColumn": "DATE_WID",
        "toTable": "Dim - Date",
        "toColumn": "DATE_WID"
      },
      {
        "name": "702304a4-435c-4959-8d72-bb9c2b02f9cf",
        "fromTable": "Fact - Inventory Ths",
        "fromColumn": "PRODUCT_WID",
        "toTable": "Dim - Product",
        "toColumn": "PRODUCT_WID"
      },
      {
        "name": "711d8bf0-b04b-4e36-a9ec-aa7aec1f6a58",
        "fromTable": "Fact - Inventory Ths",
        "fromColumn": "STORE_TERRITORY_WID",
        "toTable": "Dim - Sales Territory",
        "toColumn": "SALES_TERRITORY_WID"
      },
      {
        "name": "6ebee99e-c1b5-4c1d-9bfe-3ac0034c14e6",
        "fromTable": "Fact - Inventory Ths",
        "fromColumn": "STORE_WID",
        "toTable": "Dim - Store",
        "toColumn": "STORE_WID"
      },
      {
        "name": "14d401f6-e220-4067-9f5e-abee4438da07",
        "fromTable": "Fact - Club Program",
        "fromColumn": "PRODUCT_WID",
        "toTable": "Dim - Product",
        "toColumn": "PRODUCT_WID"
      },
      {
        "name": "3a160933-78dc-4f9d-882d-88ed2eaa57dd",
        "fromTable": "Fact - Club Target",
        "fromColumn": "DATE_WID",
        "toTable": "Dim - Date",
        "toColumn": "DATE_WID"
      },
      {
        "name": "d8c4f5ca-ebc0-4813-a545-7a493e361752",
        "fromTable": "Fact - Club Target",
        "fromColumn": "CLUB_PROGRAM_WID",
        "toTable": "Dim - Club Program",
        "toColumn": "CLUB_PROGRAM_WID"
      },
      {
        "name": "e5d0a33e-4a4c-41fb-bd4e-cacb754e2e96",
        "fromTable": "Fact - Club Target",
        "fromColumn": "SALES_TERRITORY_WID",
        "toTable": "Dim - Sales Territory",
        "toColumn": "SALES_TERRITORY_WID"
      },
      {
        "name": "780dfabb-457f-43b7-9eb7-026f97fd71f1",
        "fromTable": "Fact - Sell Out",
        "fromColumn": "SALE_TYPE_WID",
        "toTable": "Dim - Sales Type",
        "toColumn": "SALE_TYPE_WID"
      },
      {
        "name": "9db7e70e-7074-449a-85dc-f4c66403ab97",
        "fromTable": "Fact - Sell Out",
        "fromColumn": "TIME_WID",
        "toTable": "Dim - Time",
        "toColumn": "time_wid"
      },
      {
        "name": "818d9d95-2a8d-400c-941c-058761011a35",
        "fromTable": "Fact - POSM Assignment",
        "fromColumn": "OUTLET_WID",
        "toTable": "Dim - Outlet",
        "toColumn": "OUTLET_WID"
      },
      {
        "name": "0566fda1-2259-42d0-8aea-fb4b070c598a",
        "fromTable": "Fact - Promotion Ths",
        "fromColumn": "PROMOTION_WID",
        "toTable": "Dim - Promotion Ths",
        "toColumn": "PROMOTION_WID"
      },
      {
        "name": "95b51963-fc5d-4459-9a42-ae78afb51635",
        "fromTable": "Fact - Promotion Ths",
        "fromColumn": "STORE_WID",
        "toTable": "Dim - Store",
        "toColumn": "STORE_WID"
      },
      {
        "name": "0d250ee7-b155-4747-b4ac-92570513e77b",
        "fromTable": "Fact - Sell Out",
        "fromColumn": "PROMOTION_WID",
        "toTable": "Dim - Promotion Ths",
        "toColumn": "PROMOTION_WID"
      },
      {
        "name": "43775140-3a42-43a8-8eea-49a708385f1d",
        "fromTable": "Fact - Inventory",
        "fromColumn": "SHELFLIFE_WID",
        "toTable": "Dim - Shelf Life",
        "toColumn": "SHELFLIFE_WID"
      },
      {
        "name": "1c92f223-d1b1-4ed3-bd7b-99b27330be74",
        "fromTable": "Fact - Inventory Ths",
        "fromColumn": "SHELFLIFE_WID",
        "toTable": "Dim - Shelf Life",
        "toColumn": "SHELFLIFE_WID"
      },
      {
        "name": "47984c65-8fa7-48da-9c31-ff3b3f7a569a",
        "fromTable": "Fact - Sell Out",
        "fromColumn": "ROUTE_TYPE_WID",
        "toTable": "Dim - Route Type",
        "toColumn": "ROUTE_TYPE_WID"
      },
      {
        "name": "437aab7a-bc4c-4e15-a220-19d3ab430a90",
        "fromTable": "Fact - Actual Visit",
        "fromColumn": "ROUTE_TYPE_WID",
        "toTable": "Dim - Route Type",
        "toColumn": "ROUTE_TYPE_WID"
      },
      {
        "name": "d88b557b-c5c4-4c57-b5bd-86c15084fcf4",
        "fromTable": "Fact - MCP",
        "fromColumn": "ROUTE_TYPE_WID",
        "toTable": "Dim - Route Type",
        "toColumn": "ROUTE_TYPE_WID"
      },
      {
        "name": "0b59e01e-5f14-437a-a087-332ffeecf566",
        "fromTable": "Fact - Order Detail",
        "fromColumn": "ROUTE_TYPE_WID",
        "toTable": "Dim - Route Type",
        "toColumn": "ROUTE_TYPE_WID"
      },
      {
        "name": "e443cb54-a28a-43a0-b623-d69a8e4d9b60",
        "fromTable": "Fact - MCP",
        "fromColumn": "DISTRIBUTOR_WID",
        "toTable": "Dim - Distributor",
        "toColumn": "DISTRIBUTOR_WID"
      },
      {
        "name": "8c06d0bc-0ee8-4937-befe-e5a63acbd52f",
        "fromTable": "Fact - Sell Out",
        "fromColumn": "SALES_TERRITORY_WID",
        "toTable": "Dim - Sales Territory",
        "toColumn": "SALES_TERRITORY_WID"
      },
      {
        "name": "89948f90-fb32-4055-9da9-f6a442732a2f",
        "fromTable": "Fact - Promotion Ths",
        "fromColumn": "CHANNEL_WID",
        "toTable": "Dim - Channel",
        "toColumn": "CHANNEL_WID"
      },
      {
        "name": "a0cc71d6-4ee4-4ab1-becc-f999b694758d",
        "fromTable": "Fact - Promotion Ths",
        "fromColumn": "SALE_TYPE_WID",
        "toTable": "Dim - Sales Type",
        "toColumn": "SALE_TYPE_WID"
      },
      {
        "name": "83b01345-a121-4d78-a229-75b10371d89f",
        "fromTable": "Fact - Promotion Ths",
        "fromColumn": "SALE_FORCE_WID",
        "toTable": "Dim - Sales Force",
        "toColumn": "SALESFORCE_WID"
      },
      {
        "name": "77403142-a0f6-49a8-953e-1550ae88a50d",
        "fromTable": "Fact - Promotion Ths",
        "fromColumn": "STORE_TERRITORY_WID",
        "toTable": "Dim - Sales Territory",
        "toColumn": "SALES_TERRITORY_WID"
      },
      {
        "name": "5e0a4136-3de0-47f5-b063-51a8a484375a",
        "fromTable": "Fact - DOS Target",
        "fromColumn": "PRODUCT_WID",
        "toTable": "Dim - Product",
        "toColumn": "PRODUCT_WID"
      },
      {
        "name": "6660c5a7-6f33-4398-ba5c-7ffb00c1db07",
        "fromTable": "Fact - DOS Target",
        "fromColumn": "STORE_WID",
        "toTable": "Dim - Store",
        "toColumn": "STORE_WID"
      },
      {
        "name": "6847d030-f183-4ead-bfb8-74a7abc34cf9",
        "fromTable": "Fact - Actual Visit",
        "fromColumn": "TIME_WID",
        "toTable": "Dim - Time",
        "toColumn": "time_wid"
      },
      {
        "name": "63bdba6a-a286-45a0-a9f7-53bfa399edbb",
        "fromTable": "Fact - Inventory",
        "fromColumn": "INLOCATION_WID",
        "toTable": "Dim - In Location",
        "toColumn": "INLOCATION_WID"
      },
      {
        "name": "9d12138b-ae94-4f9d-8f41-b8c99d17ea2f",
        "fromTable": "Fact - Sell Out",
        "fromColumn": "ORDER_AMT_RANGE_WID",
        "toTable": "Dim - Order Amt Range",
        "toColumn": "RANGE_WID"
      },
      {
        "name": "18cb8be8-978c-4038-8e01-3519668a0a8a",
        "fromTable": "Fact - Sell Out",
        "fromColumn": "Store Aging",
        "toTable": "Dim - Store Aging",
        "toColumn": "No of Day"
      },
      {
        "name": "e10ecfb8-2dd9-4134-9c14-756d9064aec4",
        "fromTable": "Fact - AOP",
        "fromColumn": "CHANNEL_WID",
        "toTable": "Dim - Channel",
        "toColumn": "CHANNEL_WID"
      },
      {
        "name": "3e0467ad-0f56-464e-93d1-1e28253f1592",
        "fromTable": "Fact - Sell Out",
        "fromColumn": "DATE_WID",
        "toTable": "Dim - Trailing Date",
        "toColumn": "DATE_WID"
      },
      {
        "name": "2e11bf81-3ef6-4ad8-bd9d-e0f76104b2e2",
        "fromTable": "Fact - Club Program",
        "fromColumn": "SALES_TERRITORY_WID",
        "toTable": "Dim - Sales Territory",
        "toColumn": "SALES_TERRITORY_WID"
      },
      {
        "name": "0ed6606b-4ad4-4f3b-b367-ce89780e0bd4",
        "fromTable": "Fact - Actual Visit",
        "fromColumn": "SALES_TERRITORY_WID",
        "toTable": "Dim - Sales Territory",
        "toColumn": "SALES_TERRITORY_WID"
      },
      {
        "name": "12bffff0-7f23-4c90-bd05-b3dcee255bf1",
        "fromTable": "Fact - MCP",
        "fromColumn": "SALES_TERRITORY_WID",
        "toTable": "Dim - Sales Territory",
        "toColumn": "SALES_TERRITORY_WID"
      },
      {
        "name": "b6fd8743-7b8d-4ba1-b6ad-6ccd6b9bfe92",
        "fromTable": "Fact - Order Detail",
        "fromColumn": "SALES_TERRITORY_WID",
        "toTable": "Dim - Sales Territory",
        "toColumn": "SALES_TERRITORY_WID"
      },
      {
        "name": "ce4b330c-04de-40cc-86d7-5ed17b18682b",
        "fromTable": "Fact - Inventory",
        "fromColumn": "SALES_TERRITORY_WID",
        "toTable": "Dim - Sales Territory",
        "toColumn": "SALES_TERRITORY_WID"
      },
      {
        "name": "9c224ced-012b-4bf4-8e72-bb376387d3b9",
        "fromTable": "Fact - Inventory",
        "fromColumn": "DISTRIBUTOR_WID",
        "toTable": "Dim - Distributor",
        "toColumn": "DISTRIBUTOR_WID"
      },
      {
        "name": "7a7b0049-3e1f-485d-bd8f-a3b0f445116a",
        "fromTable": "Fact - POSM Assignment",
        "fromColumn": "CHANNEL_WID",
        "toTable": "Dim - Channel",
        "toColumn": "CHANNEL_WID"
      },
      {
        "name": "11709e8c-2974-4916-b436-d576613b82a0",
        "fromTable": "Fact - POSM Assignment",
        "fromColumn": "DISTRIBUTOR_WID",
        "toTable": "Dim - Distributor",
        "toColumn": "DISTRIBUTOR_WID"
      },
      {
        "name": "8f48ea8a-ca24-429c-b7ae-f6f78dcdf70a",
        "fromTable": "Fact - POSM Assignment",
        "fromColumn": "DATE_WID",
        "toTable": "Dim - Date",
        "toColumn": "DATE_WID"
      },
      {
        "name": "7a1e6bc5-eaca-44b8-a491-441b711f3b58",
        "fromTable": "Fact - POSM Assignment",
        "fromColumn": "SALES_TERRITORY_WID",
        "toTable": "Dim - Sales Territory",
        "toColumn": "SALES_TERRITORY_WID"
      },
      {
        "name": "17defb37-e772-477b-93c2-d1b0c6588ef5",
        "fromTable": "Fact - POSM Assignment",
        "fromColumn": "SALESFORCE_WID",
        "toTable": "Dim - Sales Force",
        "toColumn": "SALESFORCE_WID"
      },
      {
        "name": "c56d40cd-d53e-4ba9-a806-454d63d60a31",
        "fromTable": "Fact - POSM Assignment",
        "fromColumn": "PRODUCT_WID",
        "toTable": "Dim - Product",
        "toColumn": "PRODUCT_WID"
      },
      {
        "name": "ef8c7663-68fd-4d9a-b9aa-416760d1ceb2",
        "fromTable": "Fact - Target",
        "fromColumn": "STORE_WID",
        "toTable": "Dim - Store",
        "toColumn": "STORE_WID"
      },
      {
        "name": "3be97d3d-9e38-4dfb-bddc-e4ed40df72e7",
        "fromTable": "Fact - AOP",
        "fromColumn": "STORE_WID",
        "toTable": "Dim - Store",
        "toColumn": "STORE_WID"
      },
      {
        "name": "14b3867e-52a6-4fe1-a2a9-62f5e35ba9c3",
        "fromTable": "Fact - Sell Out",
        "fromColumn": "STORE_AMT_RANGE_WID",
        "toTable": "Dim - Store Amt Range",
        "toColumn": "RANGE_WID",
        "isActive": false
      },
      {
        "name": "a4d03d9b-f5d2-4fe5-8762-e38bf2523a8b",
        "fromTable": "Fact - Target",
        "fromColumn": "CHANNEL_WID",
        "toTable": "Dim - Channel",
        "toColumn": "CHANNEL_WID"
      }
    ],
    "perspectives": [
      {
        "name": "THS",
        "tables": [
          {
            "name": "Dim - Channel",
            "columns": [
              {
                "name": "Channel Name"
              },
              {
                "name": "Channel Order"
              },
              {
                "name": "CHANNEL_WID"
              },
              {
                "name": "Sub Channel Name"
              }
            ]
          },
          {
            "name": "Dim - Date",
            "columns": [
              {
                "name": "Back 30 Working Day"
              },
              {
                "name": "Closing Flag"
              },
              {
                "name": "Date"
              },
              {
                "name": "Date Name"
              },
              {
                "name": "Date Number"
              },
              {
                "name": "Date Type"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "Day Of Week VN"
              },
              {
                "name": "Holiday"
              },
              {
                "name": "Is Holiday"
              },
              {
                "name": "Month"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Month Number"
              },
              {
                "name": "Period Type"
              },
              {
                "name": "Period Type Order"
              },
              {
                "name": "Quarter"
              },
              {
                "name": "Quarter Name"
              },
              {
                "name": "Quarter Number"
              },
              {
                "name": "Week Name"
              },
              {
                "name": "Week Number"
              },
              {
                "name": "Week Of Month"
              },
              {
                "name": "Week Of Year"
              },
              {
                "name": "Year"
              },
              {
                "name": "Is Holiday THS"
              }
            ],
            "measures": [
              {
                "name": "% Days Left"
              },
              {
                "name": "Passing Months"
              },
              {
                "name": "Total Non - Working Day THS"
              },
              {
                "name": "Total Working Day THS"
              },
              {
                "name": "% Passing Days THS"
              },
              {
                "name": "Days Left THS"
              },
              {
                "name": "Passing Days THS"
              },
              {
                "name": "vs Time Gone THS"
              },
              {
                "name": "ADS THS"
              },
              {
                "name": "Date Selected"
              },
              {
                "name": "Month Selected"
              },
              {
                "name": "Year Selected"
              },
              {
                "name": "Time Gone THS"
              },
              {
                "name": "% Passing Days"
              },
              {
                "name": "Months Left"
              },
              {
                "name": "Passing Days"
              },
              {
                "name": "Total Non - Working Day"
              }
            ]
          },
          {
            "name": "Dim - Member Ths",
            "columns": [
              {
                "name": "Card Linked To Account"
              },
              {
                "name": "Card Number Series"
              },
              {
                "name": "Card Status"
              },
              {
                "name": "Club Code"
              },
              {
                "name": "Club Name"
              },
              {
                "name": "Member Account Code"
              },
              {
                "name": "Member Account Name"
              },
              {
                "name": "Member Account Status"
              },
              {
                "name": "Member Account Type"
              },
              {
                "name": "Member Card Code"
              },
              {
                "name": "Member Contact Address"
              },
              {
                "name": "Member Contact Address 2"
              },
              {
                "name": "Member Contact Birthday"
              },
              {
                "name": "Member Contact City"
              },
              {
                "name": "Member Contact Country"
              },
              {
                "name": "Member Contact Email"
              },
              {
                "name": "Member Contact Gender"
              },
              {
                "name": "Member Contact Name"
              },
              {
                "name": "Member Contact Number"
              },
              {
                "name": "Member Contact Phone"
              },
              {
                "name": "Member Contact Post Code"
              },
              {
                "name": "Member Contact Search Name"
              },
              {
                "name": "MEMBER_WID"
              },
              {
                "name": "Next Scheme"
              },
              {
                "name": "Points"
              },
              {
                "name": "Scheme Code"
              },
              {
                "name": "Scheme Name"
              },
              {
                "name": "Scheme Point For Update"
              },
              {
                "name": "Scheme Update Sequence"
              },
              {
                "name": "First Order Date"
              }
            ]
          },
          {
            "name": "Dim - Product",
            "columns": [
              {
                "name": "Attribute Category in EN"
              },
              {
                "name": "Attribute Category in VN"
              },
              {
                "name": "Category by Storage in EN"
              },
              {
                "name": "Category by Storage in VN"
              },
              {
                "name": "Category in eN"
              },
              {
                "name": "Category in VN"
              },
              {
                "name": "Distributor Category in EN"
              },
              {
                "name": "Distributor Category in VN"
              },
              {
                "name": "Flavor in EN"
              },
              {
                "name": "Flavor in VN"
              },
              {
                "name": "Industry in EN"
              },
              {
                "name": "Industry in VN"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Is POSM"
              },
              {
                "name": "Market"
              },
              {
                "name": "NPD Date"
              },
              {
                "name": "NPD Number Day"
              },
              {
                "name": "Package Size"
              },
              {
                "name": "Packaging"
              },
              {
                "name": "Packaging Type in EN"
              },
              {
                "name": "Packaging Type in VN"
              },
              {
                "name": "Product Abbr Name"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "Product Name"
              },
              {
                "name": "Product Short Name"
              },
              {
                "name": "Product Type in EN"
              },
              {
                "name": "Product Type in VN"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "Sub Category in EN"
              },
              {
                "name": "Sub Category in VN"
              },
              {
                "name": "Supplier"
              },
              {
                "name": "VAT"
              },
              {
                "name": "Convert Rate to Ml"
              },
              {
                "name": "Convert Rate to Gram"
              },
              {
                "name": "Type"
              }
            ]
          },
          {
            "name": "Dim - Promotion Ths",
            "columns": [
              {
                "name": "Coupon Code"
              },
              {
                "name": "No Series"
              },
              {
                "name": "Offer Type"
              },
              {
                "name": "Pop Up Line"
              },
              {
                "name": "Price Group"
              },
              {
                "name": "Priority"
              },
              {
                "name": "Promotion Code"
              },
              {
                "name": "Promotion Name"
              },
              {
                "name": "Promotion Status"
              },
              {
                "name": "Promotion Type"
              },
              {
                "name": "PROMOTION_WID"
              }
            ]
          },
          {
            "name": "Dim - Sales Force",
            "columns": [
              {
                "name": "Area Store Name"
              },
              {
                "name": "ASM Name"
              },
              {
                "name": "District Sup Name"
              },
              {
                "name": "Employee Code"
              },
              {
                "name": "National Director Name"
              },
              {
                "name": "NSD Name"
              },
              {
                "name": "RSM Name"
              },
              {
                "name": "SALESFORCE_WID"
              },
              {
                "name": "SalesMan Name"
              },
              {
                "name": "SalesSup Name"
              },
              {
                "name": "SM Name"
              },
              {
                "name": "Store Manager ID"
              },
              {
                "name": "Store Manager Name"
              },
              {
                "name": "Type"
              }
            ],
            "hierarchies": [
              {
                "name": "GT&KA SF"
              },
              {
                "name": "THs SF"
              }
            ]
          },
          {
            "name": "Dim - Sales Territory",
            "columns": [
              {
                "name": "Area"
              },
              {
                "name": "Branch"
              },
              {
                "name": "Country Name"
              },
              {
                "name": "Distributor/Store Code"
              },
              {
                "name": "Distributor/Store Short Name"
              },
              {
                "name": "District Name"
              },
              {
                "name": "Location Code"
              },
              {
                "name": "Location Name"
              },
              {
                "name": "Province Name"
              },
              {
                "name": "Region"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "Sub Area"
              },
              {
                "name": "Territory Type"
              },
              {
                "name": "Branch Code Sort"
              }
            ]
          },
          {
            "name": "Dim - Sales Type",
            "columns": [
              {
                "name": "Name"
              },
              {
                "name": "Sale Type Code"
              },
              {
                "name": "SALE_TYPE_WID"
              }
            ]
          },
          {
            "name": "Dim - Shelf Life",
            "columns": [
              {
                "name": "Shelf Life Code"
              },
              {
                "name": "Shelf Life From"
              },
              {
                "name": "Shelf Life Group"
              },
              {
                "name": "Shelf Life Group Order"
              },
              {
                "name": "Shelf Life Name"
              },
              {
                "name": "Shelf Life To"
              },
              {
                "name": "SHELFLIFE_WID"
              }
            ]
          },
          {
            "name": "Dim - Store",
            "columns": [
              {
                "name": "Adress"
              },
              {
                "name": "City"
              },
              {
                "name": "First Order Date"
              },
              {
                "name": "Latitude"
              },
              {
                "name": "Location Code"
              },
              {
                "name": "Longtitude"
              },
              {
                "name": "Post Code"
              },
              {
                "name": "Store Code"
              },
              {
                "name": "Store Manager"
              },
              {
                "name": "Store Name"
              },
              {
                "name": "Store Status"
              },
              {
                "name": "Store Type"
              },
              {
                "name": "STORE_WID"
              }
            ]
          },
          {
            "name": "Dim - Tender",
            "columns": [
              {
                "name": "Account Name"
              },
              {
                "name": "Account Number"
              },
              {
                "name": "Tender Type Code"
              },
              {
                "name": "Tender Type Name"
              },
              {
                "name": "TENDER_TYPE_WID"
              }
            ]
          },
          {
            "name": "Dim - Time",
            "columns": [
              {
                "name": "Hour"
              },
              {
                "name": "Hour 12"
              },
              {
                "name": "Minute"
              },
              {
                "name": "time_wid"
              },
              {
                "name": "TT"
              },
              {
                "name": "Time Group"
              },
              {
                "name": "Time Group Sort"
              }
            ]
          },
          {
            "name": "Fact - AOP",
            "columns": [
              {
                "name": "AOP Type"
              },
              {
                "name": "AOP Value"
              },
              {
                "name": "AOP Version"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "Distributor/STore Code"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "STORE_WID"
              },
              {
                "name": "UOM"
              },
              {
                "name": "Type"
              },
              {
                "name": "CHANNEL_WID"
              }
            ],
            "measures": [
              {
                "name": "Sell Out Amt AOP"
              },
              {
                "name": "Sell Out Amt AOP FY"
              },
              {
                "name": "Sell Out Qty AOP"
              },
              {
                "name": "Sell Out Qty AOP FY"
              },
              {
                "name": "Sell Out Amt AOP Revised"
              },
              {
                "name": "Sell Out Qty AOP Revised"
              }
            ]
          },
          {
            "name": "Fact - DOS Target",
            "columns": [
              {
                "name": "DATE_WID"
              },
              {
                "name": "Distributor/STore Code"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Max DOS"
              },
              {
                "name": "Min DOS"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "STORE_WID"
              },
              {
                "name": "Type"
              }
            ]
          },
          {
            "name": "Fact - Inventory Ths",
            "columns": [
              {
                "name": "Adjust In Qty"
              },
              {
                "name": "Adjust Out Qty"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "Expired Date"
              },
              {
                "name": "In Qty"
              },
              {
                "name": "Internal Transport In Qty"
              },
              {
                "name": "Internal Transport Out Qty"
              },
              {
                "name": "Intrans Qty"
              },
              {
                "name": "Lot Serial Number"
              },
              {
                "name": "Manufacturing Date"
              },
              {
                "name": "Other Out Qty"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "Returned Qty"
              },
              {
                "name": "Shelf life Days"
              },
              {
                "name": "SHELFLIFE_WID"
              },
              {
                "name": "Sold Qty"
              },
              {
                "name": "Store Code"
              },
              {
                "name": "STORE_TERRITORY_WID"
              },
              {
                "name": "STORE_WID"
              },
              {
                "name": "THs Transport In Qty"
              },
              {
                "name": "Ths Transport Out Qty"
              },
              {
                "name": "Total In Qty"
              },
              {
                "name": "Total Out Qty"
              },
              {
                "name": "Total Shelf life Days"
              },
              {
                "name": "Year Expired Date"
              },
              {
                "name": "Month Expired Date"
              }
            ],
            "measures": [
              {
                "name": "# of THs Remaining Shelf life Days"
              },
              {
                "name": "# of Unique SKUs Cleared in Stock"
              },
              {
                "name": "# of Unique SKUs in Stock"
              },
              {
                "name": "THs Closing Stock Qty"
              },
              {
                "name": "THs Closing Stock Qty   other"
              },
              {
                "name": "THs Closing Stock Qty - Ambient"
              },
              {
                "name": "THs Closing Stock Qty - Chill"
              },
              {
                "name": "THs Closing Stock Qty - Frozen"
              },
              {
                "name": "THs DOS"
              },
              {
                "name": "THs Opening Stock Qty"
              },
              {
                "name": "THs Shelf life Days"
              },
              {
                "name": "THs Stock In Qty"
              },
              {
                "name": "THs Stock Intrans Qty"
              },
              {
                "name": "THs Stock Out Qty"
              }
            ]
          },
          {
            "name": "Fact - Promotion Ths",
            "columns": [
              {
                "name": "DATE_WID"
              },
              {
                "name": "Discount Amt"
              },
              {
                "name": "Discount Quantity"
              },
              {
                "name": "Pos Code"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "Promotion Code"
              },
              {
                "name": "PROMOTION_WID"
              },
              {
                "name": "Receipt Number"
              },
              {
                "name": "Store Code"
              },
              {
                "name": "STORE_WID"
              },
              {
                "name": "Transaction Number"
              },
              {
                "name": "CHANNEL_WID"
              },
              {
                "name": "STORE_TERRITORY_WID"
              },
              {
                "name": "SALE_FORCE_WID"
              },
              {
                "name": "SALE_TYPE_WID"
              },
              {
                "name": "Estimated Amt"
              },
              {
                "name": "Net Price"
              },
              {
                "name": "Original Quantity"
              },
              {
                "name": "Original Net Amt"
              },
              {
                "name": "VAT Amt"
              },
              {
                "name": "Is Return Order"
              },
              {
                "name": "Order Type"
              },
              {
                "name": "Discount Net Amt"
              }
            ],
            "measures": [
              {
                "name": "Promotion Qty"
              },
              {
                "name": "Ths Promotion Estimated Amt"
              },
              {
                "name": "Total THs Promotion Amt"
              },
              {
                "name": "THs Discount Amt"
              },
              {
                "name": "Promotion Sell Out Qty"
              },
              {
                "name": "Promotion Sell Out Net Amt Test"
              },
              {
                "name": "Promotion Sell Out Net Amt"
              }
            ]
          },
          {
            "name": "Fact - Sell Out",
            "columns": [
              {
                "name": "CHANNEL_WID"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "Discount Amt"
              },
              {
                "name": "Distributor ID"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Estimated Amt"
              },
              {
                "name": "Gross Amt"
              },
              {
                "name": "Invoice Date"
              },
              {
                "name": "Invoice Number"
              },
              {
                "name": "Invoice Split Number"
              },
              {
                "name": "Is Free"
              },
              {
                "name": "Is Return Order Flg"
              },
              {
                "name": "MEMBER_WID"
              },
              {
                "name": "Net Amt"
              },
              {
                "name": "Order Line Number"
              },
              {
                "name": "Order Number"
              },
              {
                "name": "Order Qty"
              },
              {
                "name": "Order Type"
              },
              {
                "name": "Outlet ID/Member Code"
              },
              {
                "name": "OUTLET_WID"
              },
              {
                "name": "Product ID/Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "Route"
              },
              {
                "name": "Route Type Code"
              },
              {
                "name": "SALE_TYPE_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "SALESFORCE_WID"
              },
              {
                "name": "Shipped Qty"
              },
              {
                "name": "Store Code"
              },
              {
                "name": "STORE_WID"
              },
              {
                "name": "TENDER_WID"
              },
              {
                "name": "TIME_WID"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "UOM"
              },
              {
                "name": "Vat Amt"
              },
              {
                "name": "Convert Rate to Ml"
              },
              {
                "name": "Convert Rate to Gram"
              },
              {
                "name": "Source Type"
              },
              {
                "name": "Carton Shipped Qty"
              },
              {
                "name": "ORDER_AMT_RANGE_WID"
              },
              {
                "name": "STORE_AMT_RANGE_WID"
              },
              {
                "name": "Store Aging"
              },
              {
                "name": "Order Date"
              }
            ],
            "measures": [
              {
                "name": "# of Active Members"
              },
              {
                "name": "# of Active Stores"
              },
              {
                "name": "# of Bills by Amt Range"
              },
              {
                "name": "# of Bills of Members"
              },
              {
                "name": "# of Bills per Member"
              },
              {
                "name": "# of Inactive Members"
              },
              {
                "name": "# of invoices"
              },
              {
                "name": "# of New Members"
              },
              {
                "name": "# of New Stores"
              },
              {
                "name": "# of Orders"
              },
              {
                "name": "# of Repeated Members"
              },
              {
                "name": "# of Repurchased Members"
              },
              {
                "name": "# of SKU per Bill"
              },
              {
                "name": "# of SKUs"
              },
              {
                "name": "# of SKUs per ASO"
              },
              {
                "name": "# of SKUs per Member"
              },
              {
                "name": "# of SKUs per Successful Order"
              },
              {
                "name": "# of Store LM"
              },
              {
                "name": "# of Store LY"
              },
              {
                "name": "# of Stores"
              },
              {
                "name": "# of Stores MTD"
              },
              {
                "name": "# of Stores MTD LM"
              },
              {
                "name": "# of Stores YTD"
              },
              {
                "name": "# of Stores YTD LY"
              },
              {
                "name": "# of Unique SKUs"
              },
              {
                "name": "AVG Daily Sell Out Amt"
              },
              {
                "name": "AVG Daily Sell Out Qty"
              },
              {
                "name": "AVG Sell Out per Bill"
              },
              {
                "name": "AVG Sell Out per day/ Store"
              },
              {
                "name": "AVG Sell Out per Store"
              },
              {
                "name": "Sell Out Amt"
              },
              {
                "name": "Sell Out Amt % vs AOP"
              },
              {
                "name": "Sell Out Amt % vs AOP FY"
              },
              {
                "name": "Sell Out Amt % vs Target"
              },
              {
                "name": "Sell Out Amt Excl Voucher"
              },
              {
                "name": "Sell Out Amt Growth % vs LM"
              },
              {
                "name": "Sell Out Amt Growth % vs LY"
              },
              {
                "name": "Sell Out Amt LM"
              },
              {
                "name": "Sell Out Amt LY"
              },
              {
                "name": "Sell Out Amt MTD"
              },
              {
                "name": "Sell Out Amt MTD LM"
              },
              {
                "name": "Sell Out Amt MTD LY"
              },
              {
                "name": "Sell Out Amt Projection"
              },
              {
                "name": "Sell Out Amt Projection % vs AOP"
              },
              {
                "name": "Sell Out Amt Projection % vs Target"
              },
              {
                "name": "Sell Out Amt Remaining vs AOP"
              },
              {
                "name": "Sell Out Amt Remaining vs AOP FY"
              },
              {
                "name": "Sell Out Amt Voucher"
              },
              {
                "name": "Sell Out Amt YTD"
              },
              {
                "name": "Sell Out Net Amt"
              },
              {
                "name": "Sell Out Net Amt Excl Voucher"
              },
              {
                "name": "Sell Out Qty"
              },
              {
                "name": "Sell Out Qty % vs AOP"
              },
              {
                "name": "Sell Out Qty % vs AOP FY"
              },
              {
                "name": "Sell Out Qty % vs Target"
              },
              {
                "name": "Sell Out Qty Excl Voucher"
              },
              {
                "name": "Sell Out Qty Growth % vs LM"
              },
              {
                "name": "Sell Out Qty Growth % vs LY"
              },
              {
                "name": "Sell Out Qty LM"
              },
              {
                "name": "Sell Out Qty LY"
              },
              {
                "name": "Sell Out Qty MTD"
              },
              {
                "name": "Sell Out Qty MTD LM"
              },
              {
                "name": "Sell Out Qty MTD LY"
              },
              {
                "name": "Sell Out Qty Projection"
              },
              {
                "name": "Sell Out Qty Projection % vs AOP"
              },
              {
                "name": "Sell Out Qty Projection % vs Target"
              },
              {
                "name": "Sell Out Qty Remaining vs AOP"
              },
              {
                "name": "Sell Out Qty YTD"
              },
              {
                "name": "Sell Out THs tnh thng"
              },
              {
                "name": "Sell Out THs tnh thng LM"
              },
              {
                "name": "Sell Out THs tnh thng MTD"
              },
              {
                "name": "Sell Out THs tnh thng MTD LM"
              },
              {
                "name": "Sell Out THs tnh thng YTD"
              },
              {
                "name": "Sell Out THs tnh thng YTD LY"
              },
              {
                "name": "Sell Out True Mart Amt"
              },
              {
                "name": "Sell Out True Mart Amt LM"
              },
              {
                "name": "Sell Out True Mart Amt MTD"
              },
              {
                "name": "Sell Out True Mart Amt MTD LM"
              },
              {
                "name": "Sell Out True Mart Amt YTD"
              },
              {
                "name": "Sell Out True Mart Amt YTD LY"
              },
              {
                "name": "Sell Out True Mart Net Amt"
              },
              {
                "name": "Sell Out True Mart Qty"
              },
              {
                "name": "Store Growth % vs LM"
              },
              {
                "name": "Store Growth % vs LY"
              },
              {
                "name": "% THs Provide Standard Stock  - Chill"
              },
              {
                "name": "# of Unique SKUs YTD"
              },
              {
                "name": "# of SKUs YTD"
              },
              {
                "name": "# of SKUs per Successful Order YTD"
              },
              {
                "name": "# of SKUs per ASO YTD"
              },
              {
                "name": "# of Orders YTD"
              },
              {
                "name": "# of invoices YTD"
              },
              {
                "name": "Icon for Sell Out Amt vs LM"
              },
              {
                "name": "Icon for Sell Out Amt vs LY"
              },
              {
                "name": "Icon for Sell Out Qty vs LM"
              },
              {
                "name": "Icon for Sell Out Qty vs LY"
              },
              {
                "name": "Icon for SO vs AOP/Target"
              },
              {
                "name": "Invoices per Route per day"
              },
              {
                "name": "Refreshed Date"
              },
              {
                "name": "Sell Out % vs AOP/Target"
              },
              {
                "name": "Sell Out Amt/Qty"
              },
              {
                "name": "Sell Out AOP/Target"
              },
              {
                "name": "Sell out Qty 3D- Chill"
              },
              {
                "name": "Sell Out Qty Voucher"
              },
              {
                "name": "Sell Out THs tnh thng QTY"
              },
              {
                "name": "Sell Out True Mart Net Amt % vs AOP"
              },
              {
                "name": "Sell Out True Mart Net Amt % vs Target"
              },
              {
                "name": "Sell Out True Mart Qty % vs AOP"
              },
              {
                "name": "Sell Out True Mart Qty % vs Target"
              },
              {
                "name": "Today"
              },
              {
                "name": "Sell Out Gross Amt"
              },
              {
                "name": "Icon for Sell Out Amt/Qty vs LM"
              },
              {
                "name": "Icon for Sell Out Amt/Qty vs LY"
              },
              {
                "name": "Sell Out Amt/Qty Growth % vs LM"
              },
              {
                "name": "Sell Out Amt/Qty Growth % vs LY"
              },
              {
                "name": "Sell Out Amt/Qty LM"
              },
              {
                "name": "Sell Out Amt/Qty LY"
              },
              {
                "name": "Sell Out Amt/Qty MTD"
              },
              {
                "name": "Sell Out Amt/Qty MTD LM"
              },
              {
                "name": "Sell Out Amt/Qty YTD"
              },
              {
                "name": "Sell Out Amt/Qty YTD LY"
              },
              {
                "name": "AVG Sell Out by Route"
              },
              {
                "name": "AVG Sell Out by Month"
              },
              {
                "name": "AVG Sell Out Rolling n-month"
              },
              {
                "name": "Sell Out Amt Growth % vs LM Rolling n-month"
              },
              {
                "name": "Sell Out Amt Rolling n-month"
              },
              {
                "name": "# Members Show Report"
              },
              {
                "name": "Bills/Days/Store"
              },
              {
                "name": "% New Stores / Stores"
              },
              {
                "name": "Icon for Stores vs LM"
              },
              {
                "name": "Icon for Stores vs LY"
              },
              {
                "name": "Product Invoices/ Total Invoices"
              },
              {
                "name": "Icon for Sell Out Amt/Qty vs YTD LM"
              },
              {
                "name": "Icon for Sell Out Amt/Qty vs YTD LY"
              },
              {
                "name": "Sell Out Amt/Qty YTD Growth % vs LM YTD"
              },
              {
                "name": "Sell Out AOP/Target YTD"
              },
              {
                "name": "# of New Stores YTD"
              },
              {
                "name": "# Store YTD Growth % vs LM YTD"
              },
              {
                "name": "% New Stores / Stores YTD"
              },
              {
                "name": "Icon for # of Stores Growth % vs YTD LM"
              },
              {
                "name": "Icon for # of Stores Growth % vs YTD LY"
              },
              {
                "name": "# of Active Members YTD"
              },
              {
                "name": "# of Stores YTD LM"
              },
              {
                "name": "AVG Sell Out per Store YTD"
              },
              {
                "name": "Bills/Days/Store YTD"
              },
              {
                "name": "SKU Per Bill YTD"
              },
              {
                "name": "AVG Invoices"
              },
              {
                "name": "AVG Sell Out Amt/Qty"
              },
              {
                "name": "Icon for SO vs AOP/Target YTD"
              },
              {
                "name": "Sell Out % vs AOP/Target YTD"
              },
              {
                "name": "Sell Out Amt MTD Growth % vs MTD LM"
              },
              {
                "name": "Sell Out Amt YTD Growth % vs YTD LY"
              },
              {
                "name": "# Store YTD Growth % vs YTD LY"
              },
              {
                "name": "Icon for Sell Out Amt/Qty vs MTD LM"
              },
              {
                "name": "Icon for Sell Out Amt/Qty vs MTD LY"
              },
              {
                "name": "Sell Out Amt/Qty MTD Growth % vs MTD LY"
              },
              {
                "name": "Sell Out AOP/Target MTD"
              },
              {
                "name": "Sell Out Amt/Qty MTD Growth % vs LM MTD"
              },
              {
                "name": "Sell Out Amt/Qty YTD Growth % vs LY YTD"
              },
              {
                "name": "Icon for SO vs AOP/Target MTD"
              },
              {
                "name": "Sell Out % vs AOP/Target MTD"
              },
              {
                "name": "# of New Stores MTD"
              },
              {
                "name": "# of Stores MTD LY"
              },
              {
                "name": "# Store MTD Growth % vs MTD LM"
              },
              {
                "name": "# Store MTD Growth % vs MTD LY"
              },
              {
                "name": "% New Stores / Stores MTD"
              },
              {
                "name": "Icon for # of Stores Growth % vs MTD LM"
              },
              {
                "name": "Icon for # of Stores Growth % vs MTD LY"
              },
              {
                "name": "# of Active Stores by AMT Range"
              },
              {
                "name": "# of Store with AVG Amt Less Than BE Point"
              },
              {
                "name": "AVG Sell Out /Store/ Month"
              }
            ]
          },
          {
            "name": "Fact - Target",
            "columns": [
              {
                "name": "DATE_WID"
              },
              {
                "name": "Distributor/STore Code"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "STORE_WID"
              },
              {
                "name": "Target Type"
              },
              {
                "name": "Target Value"
              },
              {
                "name": "UOM"
              },
              {
                "name": "Type"
              },
              {
                "name": "CHANNEL_WID"
              }
            ],
            "measures": [
              {
                "name": "Sell Out Amt Remaining vs Target"
              },
              {
                "name": "Sell Out Amt Target"
              },
              {
                "name": "Sell Out Amt Target MTD"
              },
              {
                "name": "Sell Out Amt Target MTD LM"
              },
              {
                "name": "Sell Out Amt Target YTD"
              },
              {
                "name": "Sell Out Amt Target YTD LY"
              },
              {
                "name": "Sell Out Amt YTD LY"
              },
              {
                "name": "Sell Out Qty Remaining vs Target"
              },
              {
                "name": "Sell Out Qty Target"
              },
              {
                "name": "Sell Out Qty Target MTD"
              },
              {
                "name": "Sell Out Qty Target MTD LM"
              },
              {
                "name": "Sell Out Qty Target YTD"
              },
              {
                "name": "Sell Out Qty Target YTD LY"
              }
            ]
          },
          {
            "name": "Selection Amt Qty",
            "columns": [
              {
                "name": "Abb"
              },
              {
                "name": "Value"
              }
            ]
          },
          {
            "name": "Selection AOP Target",
            "columns": [
              {
                "name": "Value"
              }
            ]
          },
          {
            "name": "Selection Members",
            "columns": [
              {
                "name": "Value"
              }
            ]
          },
          {
            "name": "Fact - Forecast",
            "columns": [
              {
                "name": "DATE_WID"
              },
              {
                "name": "Distributor Code"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Forecat Type"
              },
              {
                "name": "Forecat Value"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "STORE_WID"
              },
              {
                "name": "UOM"
              }
            ]
          },
          {
            "name": "Dim - Order Amt Range",
            "columns": [
              {
                "name": "From Value"
              },
              {
                "name": "Group Name"
              },
              {
                "name": "RANGE_WID"
              },
              {
                "name": "To Value"
              }
            ]
          },
          {
            "name": "Dim - Store Amt Range",
            "columns": [
              {
                "name": "From Value"
              },
              {
                "name": "Group Name"
              },
              {
                "name": "Group Name Sort"
              },
              {
                "name": "RANGE_WID"
              },
              {
                "name": "To Value"
              }
            ]
          },
          {
            "name": "Dim - Store Aging",
            "columns": [
              {
                "name": "Group"
              },
              {
                "name": "Group Sort"
              },
              {
                "name": "No of Day"
              },
              {
                "name": "No of Year"
              }
            ]
          },
          {
            "name": "Dim - Trailing Date",
            "columns": [
              {
                "name": "Back 30 Working Day"
              },
              {
                "name": "Closing Flag"
              },
              {
                "name": "Date"
              },
              {
                "name": "Date Name"
              },
              {
                "name": "Date Number"
              },
              {
                "name": "Date Type"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "Day Of Week VN"
              },
              {
                "name": "Holiday"
              },
              {
                "name": "Is Holiday"
              },
              {
                "name": "Is Holiday NPP"
              },
              {
                "name": "Is Holiday THS"
              },
              {
                "name": "Month"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Month Number"
              },
              {
                "name": "Period Type"
              },
              {
                "name": "Period Type Order"
              },
              {
                "name": "Quarter"
              },
              {
                "name": "Quarter Name"
              },
              {
                "name": "Quarter Number"
              },
              {
                "name": "Week Name"
              },
              {
                "name": "Week Number"
              },
              {
                "name": "Week Of Month"
              },
              {
                "name": "Week Of Year"
              },
              {
                "name": "Year"
              }
            ]
          }
        ]
      },
      {
        "name": "DMS",
        "tables": [
          {
            "name": "Dim - Channel",
            "columns": [
              {
                "name": "Channel Name"
              },
              {
                "name": "Channel Order"
              },
              {
                "name": "CHANNEL_WID"
              },
              {
                "name": "Sub Channel Name"
              }
            ]
          },
          {
            "name": "Dim - Club Program",
            "columns": [
              {
                "name": "Accumulate By"
              },
              {
                "name": "CLUB_PROGRAM_WID"
              },
              {
                "name": "End Execution Date"
              },
              {
                "name": "End Register Date"
              },
              {
                "name": "Is Accumulate"
              },
              {
                "name": "Is Active"
              },
              {
                "name": "Is Ratio"
              },
              {
                "name": "Product Name"
              },
              {
                "name": "Program Code"
              },
              {
                "name": "Program Desc"
              },
              {
                "name": "Program Type"
              },
              {
                "name": "SAP Program Code"
              },
              {
                "name": "SAP Program Name"
              },
              {
                "name": "Start Execution Date"
              },
              {
                "name": "Start Register Date"
              },
              {
                "name": "Status"
              },
              {
                "name": "Program Level"
              },
              {
                "name": "Revenue Target"
              },
              {
                "name": "Quantity Target"
              },
              {
                "name": "Product Code"
              }
            ]
          },
          {
            "name": "Dim - Date",
            "columns": [
              {
                "name": "Back 30 Working Day"
              },
              {
                "name": "Closing Flag"
              },
              {
                "name": "Date"
              },
              {
                "name": "Date Name"
              },
              {
                "name": "Date Number"
              },
              {
                "name": "Date Type"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "Day Of Week VN"
              },
              {
                "name": "Holiday"
              },
              {
                "name": "Is Holiday"
              },
              {
                "name": "Month"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Month Number"
              },
              {
                "name": "Period Type"
              },
              {
                "name": "Period Type Order"
              },
              {
                "name": "Quarter"
              },
              {
                "name": "Quarter Name"
              },
              {
                "name": "Quarter Number"
              },
              {
                "name": "Week Name"
              },
              {
                "name": "Week Number"
              },
              {
                "name": "Week Of Month"
              },
              {
                "name": "Week Of Year"
              },
              {
                "name": "Year"
              },
              {
                "name": "Is Holiday NPP"
              }
            ],
            "measures": [
              {
                "name": "% Days Left"
              },
              {
                "name": "Passing Months"
              },
              {
                "name": "Total Non - Working Day NPP"
              },
              {
                "name": "Total Working Day NPP"
              },
              {
                "name": "% Passing Days NPP"
              },
              {
                "name": "Days Left NPP"
              },
              {
                "name": "Passing Days NPP"
              },
              {
                "name": "vs Time Gone NPP"
              },
              {
                "name": "ADS NPP"
              },
              {
                "name": "Date Selected"
              },
              {
                "name": "Month Selected"
              },
              {
                "name": "Year Selected"
              },
              {
                "name": "Time Gone NPP"
              }
            ]
          },
          {
            "name": "Dim - Distributor",
            "columns": [
              {
                "name": "Address Level 1"
              },
              {
                "name": "Address Level 2"
              },
              {
                "name": "Address Level 3"
              },
              {
                "name": "Distributor Code"
              },
              {
                "name": "Distributor Name"
              },
              {
                "name": "Distributor Short Name"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "District Code"
              },
              {
                "name": "District Name"
              },
              {
                "name": "Email"
              },
              {
                "name": "Fax"
              },
              {
                "name": "First Order Date"
              },
              {
                "name": "Is Main Office"
              },
              {
                "name": "Linked Distributor Code"
              },
              {
                "name": "Linked Vendor Code"
              },
              {
                "name": "Phone No 1"
              },
              {
                "name": "Phone No 2"
              },
              {
                "name": "Province Code"
              },
              {
                "name": "Province Name"
              },
              {
                "name": "Region Code"
              },
              {
                "name": "Region Name"
              },
              {
                "name": "Role"
              },
              {
                "name": "Type"
              }
            ]
          },
          {
            "name": "Dim - Outlet",
            "columns": [
              {
                "name": "Address Detail"
              },
              {
                "name": "Baseline Date"
              },
              {
                "name": "Channel"
              },
              {
                "name": "Display Class"
              },
              {
                "name": "Distributor Channel"
              },
              {
                "name": "Email"
              },
              {
                "name": "First Order Date"
              },
              {
                "name": "Loyalty Class"
              },
              {
                "name": "Outlet Code"
              },
              {
                "name": "Outlet Name"
              },
              {
                "name": "Outlet Type"
              },
              {
                "name": "OUTLET_WID"
              },
              {
                "name": "Phone No 1"
              },
              {
                "name": "Phone No 2"
              },
              {
                "name": "Sales Level"
              },
              {
                "name": "Salutation"
              },
              {
                "name": "Shop Area"
              },
              {
                "name": "Shop Format"
              },
              {
                "name": "Shop Location"
              },
              {
                "name": "Shop Model"
              },
              {
                "name": "Sub Channel"
              },
              {
                "name": "Ward Name"
              },
              {
                "name": "Website"
              }
            ]
          },
          {
            "name": "Dim - Product",
            "columns": [
              {
                "name": "Attribute Category in EN"
              },
              {
                "name": "Attribute Category in VN"
              },
              {
                "name": "Category by Storage in EN"
              },
              {
                "name": "Category by Storage in VN"
              },
              {
                "name": "Category in eN"
              },
              {
                "name": "Category in VN"
              },
              {
                "name": "Distributor Category in EN"
              },
              {
                "name": "Distributor Category in VN"
              },
              {
                "name": "Flavor in EN"
              },
              {
                "name": "Flavor in VN"
              },
              {
                "name": "Industry in EN"
              },
              {
                "name": "Industry in VN"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Is POSM"
              },
              {
                "name": "Market"
              },
              {
                "name": "NPD Date"
              },
              {
                "name": "NPD Number Day"
              },
              {
                "name": "Package Size"
              },
              {
                "name": "Packaging"
              },
              {
                "name": "Packaging Type in EN"
              },
              {
                "name": "Packaging Type in VN"
              },
              {
                "name": "Product Abbr Name"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "Product Name"
              },
              {
                "name": "Product Short Name"
              },
              {
                "name": "Product Type in EN"
              },
              {
                "name": "Product Type in VN"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "Sub Category in EN"
              },
              {
                "name": "Sub Category in VN"
              },
              {
                "name": "Supplier"
              },
              {
                "name": "VAT"
              },
              {
                "name": "Convert Rate to Ml"
              },
              {
                "name": "Convert Rate to Gram"
              },
              {
                "name": "Type"
              }
            ]
          },
          {
            "name": "Dim - Promotion",
            "columns": [
              {
                "name": "Active"
              },
              {
                "name": "Applicable To"
              },
              {
                "name": "Apply For"
              },
              {
                "name": "Apply To"
              },
              {
                "name": "Close Date"
              },
              {
                "name": "Compound"
              },
              {
                "name": "Deal"
              },
              {
                "name": "Discount By"
              },
              {
                "name": "Discount By Free"
              },
              {
                "name": "Discount Type"
              },
              {
                "name": "Effective Date"
              },
              {
                "name": "End Date"
              },
              {
                "name": "Exclude"
              },
              {
                "name": "IO Code"
              },
              {
                "name": "Is Budget"
              },
              {
                "name": "Is Condition"
              },
              {
                "name": "Is Ho Discount"
              },
              {
                "name": "Is Sellin"
              },
              {
                "name": "Multi Type"
              },
              {
                "name": "Priority"
              },
              {
                "name": "Promotion Code"
              },
              {
                "name": "Promotion Desc"
              },
              {
                "name": "Promotion Rate"
              },
              {
                "name": "PROMOTION_WID"
              },
              {
                "name": "Scheme"
              },
              {
                "name": "Status"
              }
            ]
          },
          {
            "name": "Dim - Sales Force",
            "columns": [
              {
                "name": "Area Store Name"
              },
              {
                "name": "ASM Name"
              },
              {
                "name": "District Sup Name"
              },
              {
                "name": "Employee Code"
              },
              {
                "name": "National Director Name"
              },
              {
                "name": "NSD Name"
              },
              {
                "name": "RSM Name"
              },
              {
                "name": "SALESFORCE_WID"
              },
              {
                "name": "SalesMan Name"
              },
              {
                "name": "SalesSup Name"
              },
              {
                "name": "SM Name"
              },
              {
                "name": "Store Manager ID"
              },
              {
                "name": "Store Manager Name"
              },
              {
                "name": "Type"
              }
            ],
            "hierarchies": [
              {
                "name": "GT&KA SF"
              },
              {
                "name": "THs SF"
              }
            ]
          },
          {
            "name": "Dim - Sales Territory",
            "columns": [
              {
                "name": "Area"
              },
              {
                "name": "Branch"
              },
              {
                "name": "Country Name"
              },
              {
                "name": "Distributor/Store Code"
              },
              {
                "name": "Distributor/Store Short Name"
              },
              {
                "name": "District Name"
              },
              {
                "name": "Location Code"
              },
              {
                "name": "Location Name"
              },
              {
                "name": "Province Name"
              },
              {
                "name": "Region"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "Sub Area"
              },
              {
                "name": "Territory Type"
              },
              {
                "name": "Branch Code Sort"
              }
            ]
          },
          {
            "name": "Dim - Shelf Life",
            "columns": [
              {
                "name": "Shelf Life Code"
              },
              {
                "name": "Shelf Life From"
              },
              {
                "name": "Shelf Life Group"
              },
              {
                "name": "Shelf Life Group Order"
              },
              {
                "name": "Shelf Life Name"
              },
              {
                "name": "Shelf Life To"
              },
              {
                "name": "SHELFLIFE_WID"
              }
            ]
          },
          {
            "name": "Dim - Time",
            "columns": [
              {
                "name": "Hour"
              },
              {
                "name": "Hour 12"
              },
              {
                "name": "Minute"
              },
              {
                "name": "time_wid"
              },
              {
                "name": "TT"
              },
              {
                "name": "Time Group"
              },
              {
                "name": "Time Group Sort"
              }
            ]
          },
          {
            "name": "Fact - Actual Visit",
            "columns": [
              {
                "name": "CHANNEL_WID"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "Distributor Code"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "End Time"
              },
              {
                "name": "Is Mcp"
              },
              {
                "name": "Order Number"
              },
              {
                "name": "Outlet Code"
              },
              {
                "name": "OUTLET_WID"
              },
              {
                "name": "REASON"
              },
              {
                "name": "Route Code"
              },
              {
                "name": "ROUTE_TYPE_WID"
              },
              {
                "name": "Sales Man"
              },
              {
                "name": "SALES_FORCE_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "Start Time"
              },
              {
                "name": "STATUS"
              },
              {
                "name": "Visit Date"
              },
              {
                "name": "Visited Duration Time"
              },
              {
                "name": "Visited Plan ID"
              },
              {
                "name": "Working Time in Route"
              },
              {
                "name": "TIME_WID"
              }
            ],
            "measures": [
              {
                "name": "# of SalesMan"
              },
              {
                "name": "First Visit Time in Day"
              },
              {
                "name": "Last Visit Time in Day"
              },
              {
                "name": "Visit Duration Time"
              },
              {
                "name": "WorkingTime on Route"
              },
              {
                "name": "Visited Call out Route"
              },
              {
                "name": "Visited Call in Route YTD"
              },
              {
                "name": "Visited Call in Route"
              },
              {
                "name": "Visit Duration Time (mins)"
              },
              {
                "name": "Plan Call/ Route/ Working Day"
              },
              {
                "name": "Actual Call/ Route/ Working Day"
              },
              {
                "name": "# of ASO_Lnh"
              },
              {
                "name": "# of ASO_Kh"
              },
              {
                "name": "# of ASO_ng_Lnh"
              },
              {
                "name": "Visited Call out Route YTD"
              },
              {
                "name": "Working Time on Route (mins)"
              },
              {
                "name": "canhnguyen"
              }
            ]
          },
          {
            "name": "Fact - AOP",
            "columns": [
              {
                "name": "AOP Type"
              },
              {
                "name": "AOP Value"
              },
              {
                "name": "AOP Version"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "Distributor/STore Code"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "STORE_WID"
              },
              {
                "name": "UOM"
              },
              {
                "name": "Type"
              },
              {
                "name": "CHANNEL_WID"
              }
            ],
            "measures": [
              {
                "name": "Sell Out Amt AOP"
              },
              {
                "name": "Sell Out Amt AOP FY"
              },
              {
                "name": "Sell Out Qty AOP"
              },
              {
                "name": "Sell Out Qty AOP FY"
              },
              {
                "name": "Sell Out Amt AOP Revised"
              },
              {
                "name": "Sell Out Qty AOP Revised"
              }
            ]
          },
          {
            "name": "Fact - Club Program",
            "columns": [
              {
                "name": "CHANNEL_WID"
              },
              {
                "name": "CLUB_PROGRAM_WID"
              },
              {
                "name": "Cooler Assigned Date"
              },
              {
                "name": "Customer Location Id"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "Distributor Id"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Freeze Assigned Date"
              },
              {
                "name": "Gross Amt"
              },
              {
                "name": "Net Amt"
              },
              {
                "name": "Order Qty"
              },
              {
                "name": "Outlet Code"
              },
              {
                "name": "OUTLET_WID"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "Program Code"
              },
              {
                "name": "Register Date"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "SALESFORCE_WID"
              },
              {
                "name": "PRODUCT_CODE"
              },
              {
                "name": "PRODUCT_NAME"
              },
              {
                "name": "Is Pass Club Program"
              }
            ],
            "measures": [
              {
                "name": "# of Club ASO Active"
              },
              {
                "name": "# of Club ASO Buy"
              },
              {
                "name": "# of Club ASO not Buy"
              },
              {
                "name": "# of Club ASO of Cooler"
              },
              {
                "name": "# of Club ASO of Freeze"
              },
              {
                "name": "# of Club SKUs Buy"
              },
              {
                "name": "% ASO not buy/ ASO active"
              },
              {
                "name": "% Club ASO Buy vs Active"
              },
              {
                "name": "Avg Club SKUs per ASO"
              },
              {
                "name": "Club Sell Out Amt"
              },
              {
                "name": "Club Sell Out Qty"
              },
              {
                "name": "Target Club Sell out"
              },
              {
                "name": "# of Club  SKUs of Freeze"
              },
              {
                "name": "# of Club ASO Active LM"
              },
              {
                "name": "# of Club ASO Active LY"
              },
              {
                "name": "# of Club SKUs Buy LM"
              },
              {
                "name": "# of Club SKUs of Cooler"
              },
              {
                "name": "Avg Club sell out/ Cooler"
              },
              {
                "name": "Avg Club sell out/ Freeze"
              },
              {
                "name": "Avg Club SKUs per ASO LM"
              },
              {
                "name": "Club Sell Out / Total Sell Out"
              },
              {
                "name": "Club Sell Out / Total Sell Out L2M"
              },
              {
                "name": "Club Sell Out / Total Sell Out LM"
              },
              {
                "name": "Club Sell Out Amt L2M"
              },
              {
                "name": "Club Sell Out Amt LM"
              },
              {
                "name": "Club Sell Out Amt LY"
              },
              {
                "name": "Club Sell Out Qty LM"
              },
              {
                "name": "Club Sell Out vs Target"
              }
            ]
          },
          {
            "name": "Fact - Club Target",
            "columns": [
              {
                "name": "Amt"
              },
              {
                "name": "CLUB_PROGRAM_WID"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "No Of Customer"
              },
              {
                "name": "No Of Skus"
              },
              {
                "name": "Program Code"
              },
              {
                "name": "Program Level"
              },
              {
                "name": "Qty"
              },
              {
                "name": "SALES_TERRITORY_WID"
              }
            ]
          },
          {
            "name": "Fact - DOS Target",
            "columns": [
              {
                "name": "DATE_WID"
              },
              {
                "name": "Distributor/STore Code"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Max DOS"
              },
              {
                "name": "Min DOS"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "STORE_WID"
              },
              {
                "name": "Type"
              }
            ]
          },
          {
            "name": "Fact - Inventory",
            "columns": [
              {
                "name": "CHANNEL_WID"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Expired Date"
              },
              {
                "name": "Lot Serial Number"
              },
              {
                "name": "Manufacturing Date"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "SHELFLIFE_WID"
              },
              {
                "name": "Total Shelf Life Days"
              },
              {
                "name": "Transaction Date"
              },
              {
                "name": "INLOCATION_WID"
              },
              {
                "name": "DISTRIBUTOR_ID"
              },
              {
                "name": "PRODUCT_ID"
              },
              {
                "name": "LOCATION_ID"
              },
              {
                "name": "Buy Promotion_In"
              },
              {
                "name": "Other_In"
              },
              {
                "name": "Customer Return In"
              },
              {
                "name": "Promotion Return In"
              },
              {
                "name": "Transfer In"
              },
              {
                "name": "Upper Adj In"
              },
              {
                "name": "Return In"
              },
              {
                "name": "Total In"
              },
              {
                "name": "Other Out"
              },
              {
                "name": "Transfer Out"
              },
              {
                "name": "Lower Adj Out"
              },
              {
                "name": "Debit Out"
              },
              {
                "name": "Sell Out"
              },
              {
                "name": "Promotion Out"
              },
              {
                "name": "Reward Out"
              },
              {
                "name": "Total Out"
              },
              {
                "name": "Is Free"
              },
              {
                "name": "Supplier Return Out"
              },
              {
                "name": "Year Expired Date"
              },
              {
                "name": "Month Expired Date"
              }
            ],
            "measures": [
              {
                "name": "# of Distributor Remaining Shelf life Days"
              },
              {
                "name": "# of Distributor Shelf life Days"
              },
              {
                "name": "%  Distributor Shelf life"
              },
              {
                "name": "AVG Daily Sales by day range"
              },
              {
                "name": "Distributor Actual DOS"
              },
              {
                "name": "Distributor Actual DOS by day range"
              },
              {
                "name": "Distributor Closing Stock Qty"
              },
              {
                "name": "Distributor Opening Stock Qty"
              },
              {
                "name": "Distributor Stock In Qty"
              },
              {
                "name": "Distributor Stock Out Qty"
              },
              {
                "name": "Distributor Target DOS"
              },
              {
                "name": "NPP/THs Min DOS"
              },
              {
                "name": "THs AVG 30 Daily Sales"
              },
              {
                "name": "Distributor AVG 30 Daily Sales"
              },
              {
                "name": "NPP/THs Max DOS"
              },
              {
                "name": "SKUs w Actual < Target DOS"
              }
            ]
          },
          {
            "name": "Fact - MCP",
            "columns": [
              {
                "name": "Baseline Date"
              },
              {
                "name": "Call Plan ID"
              },
              {
                "name": "CHANNEL_WID"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "Distributor ID"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Outlet ID"
              },
              {
                "name": "OUTLET_WID"
              },
              {
                "name": "Reference Number"
              },
              {
                "name": "Route"
              },
              {
                "name": "ROUTE_TYPE_WID"
              },
              {
                "name": "SALES_FORCE_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "Visit Date"
              },
              {
                "name": "Visit Order"
              }
            ]
          },
          {
            "name": "Fact - Order Detail",
            "columns": [
              {
                "name": "CHANNEL_WID"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "Delivery Qty"
              },
              {
                "name": "Discount Amt"
              },
              {
                "name": "Distributor Code"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Free Item"
              },
              {
                "name": "Gross Amt"
              },
              {
                "name": "Line Number"
              },
              {
                "name": "Net Amt"
              },
              {
                "name": "Order Number"
              },
              {
                "name": "Order Qty"
              },
              {
                "name": "Order Type"
              },
              {
                "name": "OUTLET_WID"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "Promotion Code"
              },
              {
                "name": "Route"
              },
              {
                "name": "ROUTE_TYPE_WID"
              },
              {
                "name": "SALES_PRICE"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "Shiped Qty"
              },
              {
                "name": "Unit Per Case"
              },
              {
                "name": "Unit Price"
              }
            ]
          },
          {
            "name": "Fact - POSM Assignment",
            "columns": [
              {
                "name": "Asset Code"
              },
              {
                "name": "OUTLET_WID"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "Serial Number"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "SALESFORCE_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "CHANNEL_WID"
              },
              {
                "name": "Distributor Id"
              },
              {
                "name": "OUTLET_CODE"
              },
              {
                "name": "Product ID"
              },
              {
                "name": "Asset Type"
              },
              {
                "name": "Asset Type Name"
              },
              {
                "name": "ORDER_QTY"
              },
              {
                "name": "GROSS_AMT"
              },
              {
                "name": "NET_AMT"
              }
            ]
          },
          {
            "name": "Fact - Sell Out",
            "columns": [
              {
                "name": "CHANNEL_WID"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "Discount Amt"
              },
              {
                "name": "Distributor ID"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Estimated Amt"
              },
              {
                "name": "Gross Amt"
              },
              {
                "name": "Invoice Date"
              },
              {
                "name": "Invoice Number"
              },
              {
                "name": "Invoice Split Number"
              },
              {
                "name": "Is Free"
              },
              {
                "name": "Is Return Order Flg"
              },
              {
                "name": "Net Amt"
              },
              {
                "name": "Order Line Number"
              },
              {
                "name": "Order Number"
              },
              {
                "name": "Order Qty"
              },
              {
                "name": "Order Type"
              },
              {
                "name": "Outlet ID/Member Code"
              },
              {
                "name": "OUTLET_WID"
              },
              {
                "name": "Product ID/Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "PROMOTION_WID"
              },
              {
                "name": "Route"
              },
              {
                "name": "Route Type Code"
              },
              {
                "name": "ROUTE_TYPE_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "SALESFORCE_WID"
              },
              {
                "name": "Shipped Qty"
              },
              {
                "name": "Store Code"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "UOM"
              },
              {
                "name": "Vat Amt"
              },
              {
                "name": "Convert Rate to Ml"
              },
              {
                "name": "Convert Rate to Gram"
              },
              {
                "name": "Source Type"
              },
              {
                "name": "Carton Shipped Qty"
              },
              {
                "name": "Store Aging"
              },
              {
                "name": "Order Date"
              }
            ],
            "measures": [
              {
                "name": "# of Active Distributor"
              },
              {
                "name": "# of ASO"
              },
              {
                "name": "# of ASO by Amt Range"
              },
              {
                "name": "# of ASO by Qty Range"
              },
              {
                "name": "# of ASO LM"
              },
              {
                "name": "# of ASO LY"
              },
              {
                "name": "# of ASO MTD"
              },
              {
                "name": "# of ASO MTD LM"
              },
              {
                "name": "# of ASO YTD"
              },
              {
                "name": "# of ASO YTD LY"
              },
              {
                "name": "# of AVG Calls Plan per Day"
              },
              {
                "name": "# of Calls Plan"
              },
              {
                "name": "# of Daily ASO"
              },
              {
                "name": "# of Distributor by Amt Range"
              },
              {
                "name": "# of Invoiced Route"
              },
              {
                "name": "# of invoices"
              },
              {
                "name": "# of MCP"
              },
              {
                "name": "# of MCP Route"
              },
              {
                "name": "# of New ASO"
              },
              {
                "name": "# of New ASO by Date Range"
              },
              {
                "name": "# of New ASO LY"
              },
              {
                "name": "# of New ASO MTD"
              },
              {
                "name": "# of New ASO MTD LM"
              },
              {
                "name": "# of New ASO YTD"
              },
              {
                "name": "# of New ASO YTD LY"
              },
              {
                "name": "# of New Distributor"
              },
              {
                "name": "# of Order by Qty Range"
              },
              {
                "name": "# of Orders"
              },
              {
                "name": "# of Repeated ASO"
              },
              {
                "name": "# of Repurchased ASO"
              },
              {
                "name": "# of Repurchased ASO LM"
              },
              {
                "name": "# of Repurchased ASO LY"
              },
              {
                "name": "# of Repurchased ASO MTD"
              },
              {
                "name": "# of Repurchased ASO MTD LM"
              },
              {
                "name": "# of Repurchased ASO YTD"
              },
              {
                "name": "# of Repurchased ASO YTD LY"
              },
              {
                "name": "# of SKU per Bill"
              },
              {
                "name": "# of SKUs"
              },
              {
                "name": "# of SKUs per ASO"
              },
              {
                "name": "# of SKUs per Successful Order"
              },
              {
                "name": "# of Successful Calls"
              },
              {
                "name": "# of Successful Orders"
              },
              {
                "name": "# of Unique SKUs"
              },
              {
                "name": "# of Visited Route"
              },
              {
                "name": "% Strike Rate"
              },
              {
                "name": "ASO Growth % vs LM"
              },
              {
                "name": "ASO Growth % vs LY"
              },
              {
                "name": "ASO MTD Growth % vs LM"
              },
              {
                "name": "ASO YTD Growth % vs LM"
              },
              {
                "name": "ASO/ MCP"
              },
              {
                "name": "ASO/ Route"
              },
              {
                "name": "AVG Daily Sell Out Amt"
              },
              {
                "name": "AVG Daily Sell Out Qty"
              },
              {
                "name": "AVG Sell Out per Bill"
              },
              {
                "name": "AVG Sell Out per day/ Store"
              },
              {
                "name": "AVG Sell Out per Store"
              },
              {
                "name": "DropSize"
              },
              {
                "name": "Monthly Frequency ASO"
              },
              {
                "name": "Promotion Estimated Amt"
              },
              {
                "name": "Sell Out Amt"
              },
              {
                "name": "Sell Out Amt % vs AOP"
              },
              {
                "name": "Sell Out Amt % vs AOP FY"
              },
              {
                "name": "Sell Out Amt % vs Target"
              },
              {
                "name": "Sell Out Amt Growth % vs LM"
              },
              {
                "name": "Sell Out Amt Growth % vs LY"
              },
              {
                "name": "Sell Out Amt LM"
              },
              {
                "name": "Sell Out Amt LY"
              },
              {
                "name": "Sell Out Amt MTD"
              },
              {
                "name": "Sell Out Amt MTD LM"
              },
              {
                "name": "Sell Out Amt MTD LY"
              },
              {
                "name": "Sell Out Amt Projection"
              },
              {
                "name": "Sell Out Amt Projection % vs AOP"
              },
              {
                "name": "Sell Out Amt Projection % vs Target"
              },
              {
                "name": "Sell Out Amt Remaining vs AOP"
              },
              {
                "name": "Sell Out Amt Remaining vs AOP FY"
              },
              {
                "name": "Sell Out Amt YTD"
              },
              {
                "name": "Sell Out Discount Amt"
              },
              {
                "name": "Sell Out Net Amt"
              },
              {
                "name": "Sell Out Promotion Qty"
              },
              {
                "name": "Sell Out Qty"
              },
              {
                "name": "Sell Out Qty % vs AOP"
              },
              {
                "name": "Sell Out Qty % vs AOP FY"
              },
              {
                "name": "Sell Out Qty % vs Target"
              },
              {
                "name": "Sell Out Qty Growth % vs LM"
              },
              {
                "name": "Sell Out Qty Growth % vs LY"
              },
              {
                "name": "Sell Out Qty LM"
              },
              {
                "name": "Sell Out Qty LY"
              },
              {
                "name": "Sell Out Qty MTD"
              },
              {
                "name": "Sell Out Qty MTD LM"
              },
              {
                "name": "Sell Out Qty MTD LY"
              },
              {
                "name": "Sell Out Qty Projection"
              },
              {
                "name": "Sell Out Qty Projection % vs AOP"
              },
              {
                "name": "Sell Out Qty Projection % vs Target"
              },
              {
                "name": "Sell Out Qty Remaining vs AOP"
              },
              {
                "name": "Sell Out Qty YTD"
              },
              {
                "name": "Total Promotion Amt"
              },
              {
                "name": "VPO"
              },
              {
                "name": "Max Amt Selected"
              },
              {
                "name": "Min Amt Selected"
              },
              {
                "name": "# of Visited Calls"
              },
              {
                "name": "# of Calls Plan YTD"
              },
              {
                "name": "# of Order by Amt Range"
              },
              {
                "name": "Sell Out Amt Order"
              },
              {
                "name": "# of ASO_OFF"
              },
              {
                "name": "# of ASO_ON"
              },
              {
                "name": "# of AVG Calls Plan per Day YTD"
              },
              {
                "name": "# of Daily ASO YTD"
              },
              {
                "name": "# of Distributor by Amt Range YTD"
              },
              {
                "name": "# of invoices YTD"
              },
              {
                "name": "# of New Distributor YTD"
              },
              {
                "name": "# of Order by Amt Range YTD"
              },
              {
                "name": "# of Order by Qty Range YTD"
              },
              {
                "name": "# of Orders YTD"
              },
              {
                "name": "# of SKUs per ASO YTD"
              },
              {
                "name": "# of SKUs per Successful Order YTD"
              },
              {
                "name": "# of SKUs YTD"
              },
              {
                "name": "# of Successful Order per day"
              },
              {
                "name": "# of Successful Order per day YTD"
              },
              {
                "name": "# of Successful Orders YTD"
              },
              {
                "name": "# of Unique SKUs YTD"
              },
              {
                "name": "# of Visited Calls YTD"
              },
              {
                "name": "#of repeated ASO YTD"
              },
              {
                "name": "#of Successful Calls YTD"
              },
              {
                "name": "% New ASO / ASO"
              },
              {
                "name": "% Promotion Amt / Sell out"
              },
              {
                "name": "% Promotion Amt / Sell out LM"
              },
              {
                "name": "% Promotion Amt / Sell out LY"
              },
              {
                "name": "% Strike Rate YTD"
              },
              {
                "name": "% THs Provide Standard Stock  - Chill"
              },
              {
                "name": "ASO per Route per day"
              },
              {
                "name": "Distributor KPIs View"
              },
              {
                "name": "Distributor KPIs View LM"
              },
              {
                "name": "Distributor KPIs View LY"
              },
              {
                "name": "DropSize YTD"
              },
              {
                "name": "Icon for ASO vs LM"
              },
              {
                "name": "Icon for ASO vs LY"
              },
              {
                "name": "Icon for Sell Out Amt vs LM"
              },
              {
                "name": "Icon for Sell Out Amt vs LY"
              },
              {
                "name": "Icon for Sell Out Qty vs LM"
              },
              {
                "name": "Icon for Sell Out Qty vs LY"
              },
              {
                "name": "Icon for SO vs AOP/Target"
              },
              {
                "name": "Invoices per Route per day"
              },
              {
                "name": "Monthly Frequency ASO YTD"
              },
              {
                "name": "Promotion Estimated Amt LM"
              },
              {
                "name": "Refreshed Date"
              },
              {
                "name": "Sell Out % vs AOP/Target"
              },
              {
                "name": "Sell Out Amt/Qty"
              },
              {
                "name": "Sell Out AOP/Target"
              },
              {
                "name": "Sell Out Discount Amt LM"
              },
              {
                "name": "Sell Out Order Amt/Qty"
              },
              {
                "name": "Sell Out Qty Order"
              },
              {
                "name": "Sell Out Qty per Route per day"
              },
              {
                "name": "Today"
              },
              {
                "name": "Total Promotion Amt LM"
              },
              {
                "name": "VPO # of Repeated ASO"
              },
              {
                "name": "VPO LM"
              },
              {
                "name": "VPO of Repurchased ASO"
              },
              {
                "name": "VPO YTD"
              },
              {
                "name": "Sell Out Gross Amt"
              },
              {
                "name": "Sell Out /Salesman/ Month"
              },
              {
                "name": "Icon for Sell Out Amt/Qty vs LM"
              },
              {
                "name": "Icon for Sell Out Amt/Qty vs LY"
              },
              {
                "name": "Sell Out Amt/Qty Growth % vs LM"
              },
              {
                "name": "Sell Out Amt/Qty Growth % vs LY"
              },
              {
                "name": "Sell Out Amt/Qty LM"
              },
              {
                "name": "Sell Out Amt/Qty LY"
              },
              {
                "name": "Sell Out Amt/Qty MTD"
              },
              {
                "name": "Sell Out Amt/Qty MTD LM"
              },
              {
                "name": "Sell Out Amt/Qty YTD"
              },
              {
                "name": "Sell Out Amt/Qty YTD LY"
              },
              {
                "name": "To Show ASO"
              },
              {
                "name": "To Show VPO"
              },
              {
                "name": "AVG Sell Out by Route"
              },
              {
                "name": "AVG Sell Out by Month"
              },
              {
                "name": "AVG Sell Out Rolling n-month"
              },
              {
                "name": "Call Plan / MCP Route"
              },
              {
                "name": "Successful Calls / Actual Route"
              },
              {
                "name": "Visited Calls / Actual Route"
              },
              {
                "name": "Sell Out Amt Growth % vs LM Rolling n-month"
              },
              {
                "name": "Sell Out Amt Rolling n-month"
              },
              {
                "name": "# Members Show Report"
              },
              {
                "name": "# Total Distributor"
              },
              {
                "name": "Sell Out Net Amt ASO Asset LM"
              },
              {
                "name": "Sell Out Net Amt ASO Asset"
              },
              {
                "name": "Sell Out Net Amt ASO Asset Growth % vs LM"
              },
              {
                "name": "# of ASO Asset"
              },
              {
                "name": "# of ASO Asset LM"
              },
              {
                "name": "# of ASO Asset Growth % vs LM"
              },
              {
                "name": "Sell Out Net Amt ASO Asset / Sell Out Net Amt"
              },
              {
                "name": "SKUs / ASO Asset"
              },
              {
                "name": "Sell Out Net Amt ASO Asset LM/ Sell Out Net Amt LM"
              },
              {
                "name": "# ASO Assets/# ASO"
              },
              {
                "name": "Club Sell Out Growth % vs LM"
              },
              {
                "name": "Club ASO Active Growth % vs LM"
              },
              {
                "name": "Icon for Sell Out Amt/Qty vs YTD LM"
              },
              {
                "name": "Icon for Sell Out Amt/Qty vs YTD LY"
              },
              {
                "name": "Sell Out Amt/Qty YTD Growth % vs LM YTD"
              },
              {
                "name": "Sell Out AOP/Target YTD"
              },
              {
                "name": "AVG Invoices"
              },
              {
                "name": "AVG Sell Out Amt/Qty"
              },
              {
                "name": "Icon for SO vs AOP/Target YTD"
              },
              {
                "name": "Sell Out % vs AOP/Target YTD"
              },
              {
                "name": "Sell Out Amt MTD Growth % vs MTD LM"
              },
              {
                "name": "Sell Out Amt YTD Growth % vs YTD LY"
              },
              {
                "name": "Icon for Sell Out Amt/Qty vs MTD LM"
              },
              {
                "name": "Icon for Sell Out Amt/Qty vs MTD LY"
              },
              {
                "name": "Sell Out Amt/Qty MTD Growth % vs MTD LY"
              },
              {
                "name": "Sell Out AOP/Target MTD"
              },
              {
                "name": "Sell Out Amt/Qty MTD Growth % vs LM MTD"
              },
              {
                "name": "Sell Out Amt/Qty YTD Growth % vs LY YTD"
              },
              {
                "name": "Icon for SO vs AOP/Target MTD"
              },
              {
                "name": "Sell Out % vs AOP/Target MTD"
              },
              {
                "name": "# ASO MTD Growth % vs MTD LM"
              },
              {
                "name": "# ASO MTD Growth % vs MTD LY"
              },
              {
                "name": "# ASO YTD Growth % vs YTD LM"
              },
              {
                "name": "# ASO YTD Growth % vs YTD LY"
              },
              {
                "name": "# of New Distributor MTD"
              },
              {
                "name": "Icon for # of ASO Growth % vs MTD LM"
              },
              {
                "name": "Icon for # of ASO Growth % vs MTD LY"
              },
              {
                "name": "Icon for # of ASO Growth % vs YTD LM"
              },
              {
                "name": "Icon for # of ASO Growth % vs YTD LY"
              },
              {
                "name": "VPO MTD"
              },
              {
                "name": "% New ASO / ASO MTD"
              },
              {
                "name": "% New ASO / ASO YTD"
              }
            ]
          },
          {
            "name": "Fact - Target",
            "columns": [
              {
                "name": "DATE_WID"
              },
              {
                "name": "Distributor/STore Code"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "STORE_WID"
              },
              {
                "name": "Target Type"
              },
              {
                "name": "Target Value"
              },
              {
                "name": "UOM"
              },
              {
                "name": "Type"
              },
              {
                "name": "CHANNEL_WID"
              }
            ],
            "measures": [
              {
                "name": "Sell Out Amt Remaining vs Target"
              },
              {
                "name": "Sell Out Amt Target"
              },
              {
                "name": "Sell Out Amt Target MTD"
              },
              {
                "name": "Sell Out Amt Target MTD LM"
              },
              {
                "name": "Sell Out Amt Target YTD"
              },
              {
                "name": "Sell Out Amt Target YTD LY"
              },
              {
                "name": "Sell Out Amt YTD LY"
              },
              {
                "name": "Sell Out Qty Remaining vs Target"
              },
              {
                "name": "Sell Out Qty Target"
              },
              {
                "name": "Sell Out Qty Target MTD"
              },
              {
                "name": "Sell Out Qty Target MTD LM"
              },
              {
                "name": "Sell Out Qty Target YTD"
              },
              {
                "name": "Sell Out Qty Target YTD LY"
              }
            ]
          },
          {
            "name": "Selection Amt Qty",
            "columns": [
              {
                "name": "Abb"
              },
              {
                "name": "Value"
              }
            ]
          },
          {
            "name": "Selection AOP Target",
            "columns": [
              {
                "name": "Value"
              }
            ]
          },
          {
            "name": "Selection Members",
            "columns": [
              {
                "name": "Value"
              }
            ]
          },
          {
            "name": "Dim - In Location",
            "columns": [
              {
                "name": "INLOCATION_WID"
              },
              {
                "name": "Is Active"
              },
              {
                "name": "Location Code"
              },
              {
                "name": "Location Id"
              },
              {
                "name": "Location Name"
              }
            ]
          },
          {
            "name": "Dim - Route Type",
            "columns": [
              {
                "name": "Route Type Code"
              },
              {
                "name": "Route Type Name"
              },
              {
                "name": "ROUTE_TYPE_WID"
              }
            ]
          }
        ]
      },
      {
        "name": "Sell Out",
        "tables": [
          {
            "name": "Dim - Channel",
            "columns": [
              {
                "name": "Channel Name"
              },
              {
                "name": "Channel Order"
              },
              {
                "name": "CHANNEL_WID"
              },
              {
                "name": "Sub Channel Name"
              }
            ]
          },
          {
            "name": "Dim - Club Program",
            "columns": [
              {
                "name": "Accumulate By"
              },
              {
                "name": "CLUB_PROGRAM_WID"
              },
              {
                "name": "End Execution Date"
              },
              {
                "name": "End Register Date"
              },
              {
                "name": "Is Accumulate"
              },
              {
                "name": "Is Active"
              },
              {
                "name": "Is Ratio"
              },
              {
                "name": "Product Name"
              },
              {
                "name": "Program Code"
              },
              {
                "name": "Program Desc"
              },
              {
                "name": "Program Type"
              },
              {
                "name": "SAP Program Code"
              },
              {
                "name": "SAP Program Name"
              },
              {
                "name": "Start Execution Date"
              },
              {
                "name": "Start Register Date"
              },
              {
                "name": "Status"
              },
              {
                "name": "Program Level"
              },
              {
                "name": "Revenue Target"
              },
              {
                "name": "Quantity Target"
              },
              {
                "name": "Product Code"
              }
            ]
          },
          {
            "name": "Dim - Date",
            "columns": [
              {
                "name": "Back 30 Working Day"
              },
              {
                "name": "Closing Flag"
              },
              {
                "name": "Date"
              },
              {
                "name": "Date Name"
              },
              {
                "name": "Date Number"
              },
              {
                "name": "Date Type"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "Day Of Week VN"
              },
              {
                "name": "Holiday"
              },
              {
                "name": "Is Holiday"
              },
              {
                "name": "Month"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Month Number"
              },
              {
                "name": "Period Type"
              },
              {
                "name": "Period Type Order"
              },
              {
                "name": "Quarter"
              },
              {
                "name": "Quarter Name"
              },
              {
                "name": "Quarter Number"
              },
              {
                "name": "Week Name"
              },
              {
                "name": "Week Number"
              },
              {
                "name": "Week Of Month"
              },
              {
                "name": "Week Of Year"
              },
              {
                "name": "Year"
              },
              {
                "name": "Is Holiday NPP"
              },
              {
                "name": "Is Holiday THS"
              }
            ],
            "measures": [
              {
                "name": "% Days Left"
              },
              {
                "name": "Passing Months"
              },
              {
                "name": "Total Non - Working Day NPP"
              },
              {
                "name": "Total Non - Working Day THS"
              },
              {
                "name": "Total Working Day NPP"
              },
              {
                "name": "Total Working Day THS"
              },
              {
                "name": "ADS NPP"
              },
              {
                "name": "Days Left NPP"
              },
              {
                "name": "Passing Days THS"
              },
              {
                "name": "Passing Days NPP"
              },
              {
                "name": "vs Time Gone THS"
              },
              {
                "name": "vs Time Gone NPP"
              },
              {
                "name": "ADS THS"
              },
              {
                "name": "Days Left THS"
              },
              {
                "name": "Date Selected"
              },
              {
                "name": "Month Selected"
              },
              {
                "name": "Year Selected"
              },
              {
                "name": "Time Gone NPP"
              },
              {
                "name": "Time Gone THS"
              }
            ]
          },
          {
            "name": "Dim - Distributor",
            "columns": [
              {
                "name": "Address Level 1"
              },
              {
                "name": "Address Level 2"
              },
              {
                "name": "Address Level 3"
              },
              {
                "name": "Distributor Code"
              },
              {
                "name": "Distributor Name"
              },
              {
                "name": "Distributor Short Name"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "District Code"
              },
              {
                "name": "District Name"
              },
              {
                "name": "Email"
              },
              {
                "name": "Fax"
              },
              {
                "name": "First Order Date"
              },
              {
                "name": "Is Main Office"
              },
              {
                "name": "Linked Distributor Code"
              },
              {
                "name": "Linked Vendor Code"
              },
              {
                "name": "Phone No 1"
              },
              {
                "name": "Phone No 2"
              },
              {
                "name": "Province Code"
              },
              {
                "name": "Province Name"
              },
              {
                "name": "Region Code"
              },
              {
                "name": "Region Name"
              },
              {
                "name": "Role"
              },
              {
                "name": "Type"
              }
            ]
          },
          {
            "name": "Dim - Member Ths",
            "columns": [
              {
                "name": "Card Linked To Account"
              },
              {
                "name": "Card Number Series"
              },
              {
                "name": "Card Status"
              },
              {
                "name": "Club Code"
              },
              {
                "name": "Club Name"
              },
              {
                "name": "Member Account Code"
              },
              {
                "name": "Member Account Name"
              },
              {
                "name": "Member Account Status"
              },
              {
                "name": "Member Account Type"
              },
              {
                "name": "Member Card Code"
              },
              {
                "name": "Member Contact Address"
              },
              {
                "name": "Member Contact Address 2"
              },
              {
                "name": "Member Contact Birthday"
              },
              {
                "name": "Member Contact City"
              },
              {
                "name": "Member Contact Country"
              },
              {
                "name": "Member Contact Email"
              },
              {
                "name": "Member Contact Gender"
              },
              {
                "name": "Member Contact Name"
              },
              {
                "name": "Member Contact Number"
              },
              {
                "name": "Member Contact Phone"
              },
              {
                "name": "Member Contact Post Code"
              },
              {
                "name": "Member Contact Search Name"
              },
              {
                "name": "MEMBER_WID"
              },
              {
                "name": "Next Scheme"
              },
              {
                "name": "Points"
              },
              {
                "name": "Scheme Code"
              },
              {
                "name": "Scheme Name"
              },
              {
                "name": "Scheme Point For Update"
              },
              {
                "name": "Scheme Update Sequence"
              },
              {
                "name": "First Order Date"
              }
            ]
          },
          {
            "name": "Dim - Outlet",
            "columns": [
              {
                "name": "Address Detail"
              },
              {
                "name": "Baseline Date"
              },
              {
                "name": "Channel"
              },
              {
                "name": "Display Class"
              },
              {
                "name": "Distributor Channel"
              },
              {
                "name": "Email"
              },
              {
                "name": "First Order Date"
              },
              {
                "name": "Loyalty Class"
              },
              {
                "name": "Outlet Code"
              },
              {
                "name": "Outlet Name"
              },
              {
                "name": "Outlet Type"
              },
              {
                "name": "OUTLET_WID"
              },
              {
                "name": "Phone No 1"
              },
              {
                "name": "Phone No 2"
              },
              {
                "name": "Sales Level"
              },
              {
                "name": "Salutation"
              },
              {
                "name": "Shop Area"
              },
              {
                "name": "Shop Format"
              },
              {
                "name": "Shop Location"
              },
              {
                "name": "Shop Model"
              },
              {
                "name": "Sub Channel"
              },
              {
                "name": "Ward Name"
              },
              {
                "name": "Website"
              }
            ]
          },
          {
            "name": "Dim - Product",
            "columns": [
              {
                "name": "Attribute Category in EN"
              },
              {
                "name": "Attribute Category in VN"
              },
              {
                "name": "Category by Storage in EN"
              },
              {
                "name": "Category by Storage in VN"
              },
              {
                "name": "Category in eN"
              },
              {
                "name": "Category in VN"
              },
              {
                "name": "Distributor Category in EN"
              },
              {
                "name": "Distributor Category in VN"
              },
              {
                "name": "Flavor in EN"
              },
              {
                "name": "Flavor in VN"
              },
              {
                "name": "Industry in EN"
              },
              {
                "name": "Industry in VN"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Is POSM"
              },
              {
                "name": "Market"
              },
              {
                "name": "NPD Date"
              },
              {
                "name": "NPD Number Day"
              },
              {
                "name": "Package Size"
              },
              {
                "name": "Packaging"
              },
              {
                "name": "Packaging Type in EN"
              },
              {
                "name": "Packaging Type in VN"
              },
              {
                "name": "Product Abbr Name"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "Product Name"
              },
              {
                "name": "Product Short Name"
              },
              {
                "name": "Product Type in EN"
              },
              {
                "name": "Product Type in VN"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "Sub Category in EN"
              },
              {
                "name": "Sub Category in VN"
              },
              {
                "name": "Supplier"
              },
              {
                "name": "VAT"
              },
              {
                "name": "Convert Rate to Ml"
              },
              {
                "name": "Convert Rate to Gram"
              },
              {
                "name": "Type"
              }
            ]
          },
          {
            "name": "Dim - Promotion",
            "columns": [
              {
                "name": "Active"
              },
              {
                "name": "Applicable To"
              },
              {
                "name": "Apply For"
              },
              {
                "name": "Apply To"
              },
              {
                "name": "Close Date"
              },
              {
                "name": "Compound"
              },
              {
                "name": "Deal"
              },
              {
                "name": "Discount By"
              },
              {
                "name": "Discount By Free"
              },
              {
                "name": "Discount Type"
              },
              {
                "name": "Effective Date"
              },
              {
                "name": "End Date"
              },
              {
                "name": "Exclude"
              },
              {
                "name": "IO Code"
              },
              {
                "name": "Is Budget"
              },
              {
                "name": "Is Condition"
              },
              {
                "name": "Is Ho Discount"
              },
              {
                "name": "Is Sellin"
              },
              {
                "name": "Multi Type"
              },
              {
                "name": "Priority"
              },
              {
                "name": "Promotion Code"
              },
              {
                "name": "Promotion Desc"
              },
              {
                "name": "Promotion Rate"
              },
              {
                "name": "PROMOTION_WID"
              },
              {
                "name": "Scheme"
              },
              {
                "name": "Status"
              }
            ]
          },
          {
            "name": "Dim - Promotion Ths",
            "columns": [
              {
                "name": "Coupon Code"
              },
              {
                "name": "No Series"
              },
              {
                "name": "Offer Type"
              },
              {
                "name": "Pop Up Line"
              },
              {
                "name": "Price Group"
              },
              {
                "name": "Priority"
              },
              {
                "name": "Promotion Code"
              },
              {
                "name": "Promotion Name"
              },
              {
                "name": "Promotion Status"
              },
              {
                "name": "Promotion Type"
              },
              {
                "name": "PROMOTION_WID"
              }
            ]
          },
          {
            "name": "Dim - Route Type",
            "columns": [
              {
                "name": "Route Type Code"
              },
              {
                "name": "Route Type Name"
              },
              {
                "name": "ROUTE_TYPE_WID"
              }
            ]
          },
          {
            "name": "Dim - Sales Force",
            "columns": [
              {
                "name": "Area Store Name"
              },
              {
                "name": "ASM Name"
              },
              {
                "name": "District Sup Name"
              },
              {
                "name": "Employee Code"
              },
              {
                "name": "National Director Name"
              },
              {
                "name": "NSD Name"
              },
              {
                "name": "RSM Name"
              },
              {
                "name": "SALESFORCE_WID"
              },
              {
                "name": "SalesMan Name"
              },
              {
                "name": "SalesSup Name"
              },
              {
                "name": "SM Name"
              },
              {
                "name": "Store Manager ID"
              },
              {
                "name": "Store Manager Name"
              },
              {
                "name": "Type"
              }
            ],
            "hierarchies": [
              {
                "name": "GT&KA SF"
              },
              {
                "name": "THs SF"
              }
            ]
          },
          {
            "name": "Dim - Sales Territory",
            "columns": [
              {
                "name": "Area"
              },
              {
                "name": "Branch"
              },
              {
                "name": "Country Name"
              },
              {
                "name": "Distributor/Store Code"
              },
              {
                "name": "Distributor/Store Short Name"
              },
              {
                "name": "District Name"
              },
              {
                "name": "Location Code"
              },
              {
                "name": "Location Name"
              },
              {
                "name": "Province Name"
              },
              {
                "name": "Region"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "Sub Area"
              },
              {
                "name": "Territory Type"
              },
              {
                "name": "Branch Code Sort"
              }
            ]
          },
          {
            "name": "Dim - Sales Type",
            "columns": [
              {
                "name": "Name"
              },
              {
                "name": "Sale Type Code"
              },
              {
                "name": "SALE_TYPE_WID"
              }
            ]
          },
          {
            "name": "Dim - Shelf Life",
            "columns": [
              {
                "name": "Shelf Life Code"
              },
              {
                "name": "Shelf Life From"
              },
              {
                "name": "Shelf Life Group"
              },
              {
                "name": "Shelf Life Group Order"
              },
              {
                "name": "Shelf Life Name"
              },
              {
                "name": "Shelf Life To"
              },
              {
                "name": "SHELFLIFE_WID"
              }
            ]
          },
          {
            "name": "Dim - Store",
            "columns": [
              {
                "name": "Adress"
              },
              {
                "name": "City"
              },
              {
                "name": "First Order Date"
              },
              {
                "name": "Latitude"
              },
              {
                "name": "Location Code"
              },
              {
                "name": "Longtitude"
              },
              {
                "name": "Post Code"
              },
              {
                "name": "Store Code"
              },
              {
                "name": "Store Manager"
              },
              {
                "name": "Store Name"
              },
              {
                "name": "Store Status"
              },
              {
                "name": "Store Type"
              },
              {
                "name": "STORE_WID"
              }
            ]
          },
          {
            "name": "Dim - Tender",
            "columns": [
              {
                "name": "Account Name"
              },
              {
                "name": "Account Number"
              },
              {
                "name": "Tender Type Code"
              },
              {
                "name": "Tender Type Name"
              },
              {
                "name": "TENDER_TYPE_WID"
              }
            ]
          },
          {
            "name": "Dim - Time",
            "columns": [
              {
                "name": "Hour"
              },
              {
                "name": "Hour 12"
              },
              {
                "name": "Minute"
              },
              {
                "name": "time_wid"
              },
              {
                "name": "TT"
              },
              {
                "name": "Time Group"
              },
              {
                "name": "Time Group Sort"
              }
            ]
          },
          {
            "name": "Fact - Actual Visit",
            "columns": [
              {
                "name": "CHANNEL_WID"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "Distributor Code"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "End Time"
              },
              {
                "name": "Is Mcp"
              },
              {
                "name": "Order Number"
              },
              {
                "name": "Outlet Code"
              },
              {
                "name": "OUTLET_WID"
              },
              {
                "name": "REASON"
              },
              {
                "name": "Route Code"
              },
              {
                "name": "ROUTE_TYPE_WID"
              },
              {
                "name": "Sales Man"
              },
              {
                "name": "SALES_FORCE_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "Start Time"
              },
              {
                "name": "STATUS"
              },
              {
                "name": "Visit Date"
              },
              {
                "name": "Visited Duration Time"
              },
              {
                "name": "Visited Plan ID"
              },
              {
                "name": "Working Time in Route"
              },
              {
                "name": "TIME_WID"
              }
            ],
            "measures": [
              {
                "name": "# of SalesMan"
              },
              {
                "name": "First Visit Time in Day"
              },
              {
                "name": "Last Visit Time in Day"
              },
              {
                "name": "Visit Duration Time"
              },
              {
                "name": "WorkingTime on Route"
              },
              {
                "name": "# of ASO_ng_Lnh"
              },
              {
                "name": "# of ASO_Kh"
              },
              {
                "name": "# of ASO_Lnh"
              },
              {
                "name": "Actual Call/ Route/ Working Day"
              },
              {
                "name": "Plan Call/ Route/ Working Day"
              },
              {
                "name": "Visit Duration Time (mins)"
              },
              {
                "name": "Visited Call in Route"
              },
              {
                "name": "Visited Call in Route YTD"
              },
              {
                "name": "Visited Call out Route"
              },
              {
                "name": "Visited Call out Route YTD"
              },
              {
                "name": "Working Time on Route (mins)"
              },
              {
                "name": "canhnguyen"
              }
            ]
          },
          {
            "name": "Fact - AOP",
            "columns": [
              {
                "name": "AOP Type"
              },
              {
                "name": "AOP Value"
              },
              {
                "name": "AOP Version"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "Distributor/STore Code"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "STORE_WID"
              },
              {
                "name": "UOM"
              },
              {
                "name": "Type"
              },
              {
                "name": "CHANNEL_WID"
              }
            ],
            "measures": [
              {
                "name": "Sell Out Amt AOP"
              },
              {
                "name": "Sell Out Amt AOP FY"
              },
              {
                "name": "Sell Out Qty AOP"
              },
              {
                "name": "Sell Out Qty AOP FY"
              },
              {
                "name": "Sell Out Amt AOP Revised"
              },
              {
                "name": "Sell Out Qty AOP Revised"
              }
            ]
          },
          {
            "name": "Fact - Club Program",
            "columns": [
              {
                "name": "CHANNEL_WID"
              },
              {
                "name": "CLUB_PROGRAM_WID"
              },
              {
                "name": "Cooler Assigned Date"
              },
              {
                "name": "Customer Location Id"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "Distributor Id"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Freeze Assigned Date"
              },
              {
                "name": "Gross Amt"
              },
              {
                "name": "Net Amt"
              },
              {
                "name": "Order Qty"
              },
              {
                "name": "Outlet Code"
              },
              {
                "name": "OUTLET_WID"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "Program Code"
              },
              {
                "name": "Register Date"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "SALESFORCE_WID"
              },
              {
                "name": "PRODUCT_CODE"
              },
              {
                "name": "PRODUCT_NAME"
              },
              {
                "name": "Is Pass Club Program"
              }
            ],
            "measures": [
              {
                "name": "# of Club ASO Active"
              },
              {
                "name": "# of Club ASO Buy"
              },
              {
                "name": "# of Club ASO not Buy"
              },
              {
                "name": "# of Club ASO of Cooler"
              },
              {
                "name": "# of Club ASO of Freeze"
              },
              {
                "name": "# of Club SKUs Buy"
              },
              {
                "name": "% ASO not buy/ ASO active"
              },
              {
                "name": "% Club ASO Buy vs Active"
              },
              {
                "name": "Avg Club SKUs per ASO"
              },
              {
                "name": "Club Sell Out Amt"
              },
              {
                "name": "Club Sell Out Qty"
              },
              {
                "name": "Target Club Sell out"
              },
              {
                "name": "# of Club  SKUs of Freeze"
              },
              {
                "name": "# of Club ASO Active LM"
              },
              {
                "name": "# of Club ASO Active LY"
              },
              {
                "name": "# of Club SKUs Buy LM"
              },
              {
                "name": "# of Club SKUs of Cooler"
              },
              {
                "name": "Avg Club sell out/ Cooler"
              },
              {
                "name": "Avg Club sell out/ Freeze"
              },
              {
                "name": "Avg Club SKUs per ASO LM"
              },
              {
                "name": "Club Sell Out / Total Sell Out"
              },
              {
                "name": "Club Sell Out / Total Sell Out L2M"
              },
              {
                "name": "Club Sell Out / Total Sell Out LM"
              },
              {
                "name": "Club Sell Out Amt L2M"
              },
              {
                "name": "Club Sell Out Amt LM"
              },
              {
                "name": "Club Sell Out Amt LY"
              },
              {
                "name": "Club Sell Out Qty LM"
              },
              {
                "name": "Club Sell Out vs Target"
              }
            ]
          },
          {
            "name": "Fact - Club Target",
            "columns": [
              {
                "name": "Amt"
              },
              {
                "name": "CLUB_PROGRAM_WID"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "No Of Customer"
              },
              {
                "name": "No Of Skus"
              },
              {
                "name": "Program Code"
              },
              {
                "name": "Program Level"
              },
              {
                "name": "Qty"
              },
              {
                "name": "SALES_TERRITORY_WID"
              }
            ]
          },
          {
            "name": "Fact - DOS Target",
            "columns": [
              {
                "name": "DATE_WID"
              },
              {
                "name": "Distributor/STore Code"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Max DOS"
              },
              {
                "name": "Min DOS"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "STORE_WID"
              },
              {
                "name": "Type"
              }
            ]
          },
          {
            "name": "Fact - Inventory",
            "columns": [
              {
                "name": "CHANNEL_WID"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Expired Date"
              },
              {
                "name": "Lot Serial Number"
              },
              {
                "name": "Manufacturing Date"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "SHELFLIFE_WID"
              },
              {
                "name": "Total Shelf Life Days"
              },
              {
                "name": "Transaction Date"
              },
              {
                "name": "INLOCATION_WID"
              },
              {
                "name": "DISTRIBUTOR_ID"
              },
              {
                "name": "PRODUCT_ID"
              },
              {
                "name": "LOCATION_ID"
              },
              {
                "name": "Buy Promotion_In"
              },
              {
                "name": "Other_In"
              },
              {
                "name": "Customer Return In"
              },
              {
                "name": "Promotion Return In"
              },
              {
                "name": "Transfer In"
              },
              {
                "name": "Upper Adj In"
              },
              {
                "name": "Return In"
              },
              {
                "name": "Total In"
              },
              {
                "name": "Other Out"
              },
              {
                "name": "Transfer Out"
              },
              {
                "name": "Lower Adj Out"
              },
              {
                "name": "Debit Out"
              },
              {
                "name": "Sell Out"
              },
              {
                "name": "Promotion Out"
              },
              {
                "name": "Reward Out"
              },
              {
                "name": "Total Out"
              },
              {
                "name": "Is Free"
              },
              {
                "name": "Supplier Return Out"
              },
              {
                "name": "Year Expired Date"
              },
              {
                "name": "Month Expired Date"
              }
            ],
            "measures": [
              {
                "name": "# of Distributor Remaining Shelf life Days"
              },
              {
                "name": "# of Distributor Shelf life Days"
              },
              {
                "name": "%  Distributor Shelf life"
              },
              {
                "name": "AVG Daily Sales by day range"
              },
              {
                "name": "Distributor Actual DOS"
              },
              {
                "name": "Distributor Actual DOS by day range"
              },
              {
                "name": "Distributor Closing Stock Qty"
              },
              {
                "name": "Distributor Opening Stock Qty"
              },
              {
                "name": "Distributor Stock In Qty"
              },
              {
                "name": "Distributor Stock Out Qty"
              },
              {
                "name": "Distributor Target DOS"
              },
              {
                "name": "NPP/THs Min DOS"
              },
              {
                "name": "THs AVG 30 Daily Sales"
              },
              {
                "name": "Distributor AVG 30 Daily Sales"
              },
              {
                "name": "NPP/THs Max DOS"
              },
              {
                "name": "SKUs w Actual < Target DOS"
              }
            ]
          },
          {
            "name": "Fact - Inventory Ths",
            "columns": [
              {
                "name": "Adjust In Qty"
              },
              {
                "name": "Adjust Out Qty"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "Expired Date"
              },
              {
                "name": "In Qty"
              },
              {
                "name": "Internal Transport In Qty"
              },
              {
                "name": "Internal Transport Out Qty"
              },
              {
                "name": "Intrans Qty"
              },
              {
                "name": "Lot Serial Number"
              },
              {
                "name": "Manufacturing Date"
              },
              {
                "name": "Other Out Qty"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "Returned Qty"
              },
              {
                "name": "Shelf life Days"
              },
              {
                "name": "SHELFLIFE_WID"
              },
              {
                "name": "Sold Qty"
              },
              {
                "name": "Store Code"
              },
              {
                "name": "STORE_TERRITORY_WID"
              },
              {
                "name": "STORE_WID"
              },
              {
                "name": "THs Transport In Qty"
              },
              {
                "name": "Ths Transport Out Qty"
              },
              {
                "name": "Total In Qty"
              },
              {
                "name": "Total Out Qty"
              },
              {
                "name": "Total Shelf life Days"
              },
              {
                "name": "Year Expired Date"
              },
              {
                "name": "Month Expired Date"
              }
            ],
            "measures": [
              {
                "name": "# of THs Remaining Shelf life Days"
              },
              {
                "name": "# of Unique SKUs Cleared in Stock"
              },
              {
                "name": "# of Unique SKUs in Stock"
              },
              {
                "name": "THs Closing Stock Qty"
              },
              {
                "name": "THs Closing Stock Qty   other"
              },
              {
                "name": "THs Closing Stock Qty - Ambient"
              },
              {
                "name": "THs Closing Stock Qty - Chill"
              },
              {
                "name": "THs Closing Stock Qty - Frozen"
              },
              {
                "name": "THs DOS"
              },
              {
                "name": "THs Opening Stock Qty"
              },
              {
                "name": "THs Shelf life Days"
              },
              {
                "name": "THs Stock In Qty"
              },
              {
                "name": "THs Stock Intrans Qty"
              },
              {
                "name": "THs Stock Out Qty"
              }
            ]
          },
          {
            "name": "Fact - MCP",
            "columns": [
              {
                "name": "Baseline Date"
              },
              {
                "name": "Call Plan ID"
              },
              {
                "name": "CHANNEL_WID"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "Distributor ID"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Outlet ID"
              },
              {
                "name": "OUTLET_WID"
              },
              {
                "name": "Reference Number"
              },
              {
                "name": "Route"
              },
              {
                "name": "ROUTE_TYPE_WID"
              },
              {
                "name": "SALES_FORCE_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "Visit Date"
              },
              {
                "name": "Visit Order"
              }
            ]
          },
          {
            "name": "Fact - Order Detail",
            "columns": [
              {
                "name": "CHANNEL_WID"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "Delivery Qty"
              },
              {
                "name": "Discount Amt"
              },
              {
                "name": "Distributor Code"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Free Item"
              },
              {
                "name": "Gross Amt"
              },
              {
                "name": "Line Number"
              },
              {
                "name": "Net Amt"
              },
              {
                "name": "Order Number"
              },
              {
                "name": "Order Qty"
              },
              {
                "name": "Order Type"
              },
              {
                "name": "OUTLET_WID"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "Promotion Code"
              },
              {
                "name": "Route"
              },
              {
                "name": "ROUTE_TYPE_WID"
              },
              {
                "name": "SALES_PRICE"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "Shiped Qty"
              },
              {
                "name": "Unit Per Case"
              },
              {
                "name": "Unit Price"
              }
            ]
          },
          {
            "name": "Fact - POSM Assignment",
            "columns": [
              {
                "name": "Asset Code"
              },
              {
                "name": "OUTLET_WID"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "Serial Number"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "SALESFORCE_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "CHANNEL_WID"
              },
              {
                "name": "Distributor Id"
              },
              {
                "name": "OUTLET_CODE"
              },
              {
                "name": "Product ID"
              },
              {
                "name": "Asset Type"
              },
              {
                "name": "Asset Type Name"
              },
              {
                "name": "ORDER_QTY"
              },
              {
                "name": "GROSS_AMT"
              },
              {
                "name": "NET_AMT"
              }
            ]
          },
          {
            "name": "Fact - Promotion Ths",
            "columns": [
              {
                "name": "DATE_WID"
              },
              {
                "name": "Discount Amt"
              },
              {
                "name": "Discount Quantity"
              },
              {
                "name": "Pos Code"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "Promotion Code"
              },
              {
                "name": "PROMOTION_WID"
              },
              {
                "name": "Receipt Number"
              },
              {
                "name": "Store Code"
              },
              {
                "name": "STORE_WID"
              },
              {
                "name": "Transaction Number"
              },
              {
                "name": "CHANNEL_WID"
              },
              {
                "name": "STORE_TERRITORY_WID"
              },
              {
                "name": "SALE_FORCE_WID"
              },
              {
                "name": "SALE_TYPE_WID"
              },
              {
                "name": "Estimated Amt"
              },
              {
                "name": "Net Price"
              },
              {
                "name": "Original Quantity"
              },
              {
                "name": "Original Net Amt"
              },
              {
                "name": "VAT Amt"
              },
              {
                "name": "Is Return Order"
              },
              {
                "name": "Order Type"
              },
              {
                "name": "Discount Net Amt"
              }
            ],
            "measures": [
              {
                "name": "Promotion Qty"
              },
              {
                "name": "Ths Promotion Estimated Amt"
              },
              {
                "name": "Total THs Promotion Amt"
              },
              {
                "name": "THs Discount Amt"
              },
              {
                "name": "Promotion Sell Out Net Amt"
              },
              {
                "name": "Promotion Sell Out Net Amt Test"
              },
              {
                "name": "Promotion Sell Out Qty"
              }
            ]
          },
          {
            "name": "Fact - Sell Out",
            "columns": [
              {
                "name": "CHANNEL_WID"
              },
              {
                "name": "DATE_WID"
              },
              {
                "name": "Discount Amt"
              },
              {
                "name": "Distributor ID"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Estimated Amt"
              },
              {
                "name": "Gross Amt"
              },
              {
                "name": "Invoice Date"
              },
              {
                "name": "Invoice Number"
              },
              {
                "name": "Invoice Split Number"
              },
              {
                "name": "Is Free"
              },
              {
                "name": "Is Return Order Flg"
              },
              {
                "name": "MEMBER_WID"
              },
              {
                "name": "Net Amt"
              },
              {
                "name": "Order Line Number"
              },
              {
                "name": "Order Number"
              },
              {
                "name": "Order Qty"
              },
              {
                "name": "Order Type"
              },
              {
                "name": "Outlet ID/Member Code"
              },
              {
                "name": "OUTLET_WID"
              },
              {
                "name": "Product ID/Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "PROMOTION_WID"
              },
              {
                "name": "Route"
              },
              {
                "name": "Route Type Code"
              },
              {
                "name": "ROUTE_TYPE_WID"
              },
              {
                "name": "SALE_TYPE_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "SALESFORCE_WID"
              },
              {
                "name": "Shipped Qty"
              },
              {
                "name": "Store Code"
              },
              {
                "name": "STORE_WID"
              },
              {
                "name": "TENDER_WID"
              },
              {
                "name": "TIME_WID"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "UOM"
              },
              {
                "name": "Vat Amt"
              },
              {
                "name": "Convert Rate to Ml"
              },
              {
                "name": "Convert Rate to Gram"
              },
              {
                "name": "Source Type"
              },
              {
                "name": "Carton Shipped Qty"
              },
              {
                "name": "ORDER_AMT_RANGE_WID"
              },
              {
                "name": "STORE_AMT_RANGE_WID"
              },
              {
                "name": "Store Aging"
              },
              {
                "name": "Order Date"
              }
            ],
            "measures": [
              {
                "name": "# of Active Distributor"
              },
              {
                "name": "# of Active Members"
              },
              {
                "name": "# of Active Stores"
              },
              {
                "name": "# of ASO"
              },
              {
                "name": "# of ASO by Amt Range"
              },
              {
                "name": "# of ASO by Qty Range"
              },
              {
                "name": "# of ASO LM"
              },
              {
                "name": "# of ASO LY"
              },
              {
                "name": "# of ASO MTD"
              },
              {
                "name": "# of ASO MTD LM"
              },
              {
                "name": "# of ASO YTD"
              },
              {
                "name": "# of ASO YTD LY"
              },
              {
                "name": "# of AVG Calls Plan per Day"
              },
              {
                "name": "# of Bills by Amt Range"
              },
              {
                "name": "# of Bills of Members"
              },
              {
                "name": "# of Bills per Member"
              },
              {
                "name": "# of Calls Plan"
              },
              {
                "name": "# of Daily ASO"
              },
              {
                "name": "# of Distributor by Amt Range"
              },
              {
                "name": "# of Inactive Members"
              },
              {
                "name": "# of Invoiced Route"
              },
              {
                "name": "# of invoices"
              },
              {
                "name": "# of MCP"
              },
              {
                "name": "# of MCP Route"
              },
              {
                "name": "# of New ASO"
              },
              {
                "name": "# of New ASO by Date Range"
              },
              {
                "name": "# of New ASO LY"
              },
              {
                "name": "# of New ASO MTD"
              },
              {
                "name": "# of New ASO MTD LM"
              },
              {
                "name": "# of New ASO YTD"
              },
              {
                "name": "# of New ASO YTD LY"
              },
              {
                "name": "# of New Distributor"
              },
              {
                "name": "# of New Members"
              },
              {
                "name": "# of New Stores"
              },
              {
                "name": "# of Order by Qty Range"
              },
              {
                "name": "# of Orders"
              },
              {
                "name": "# of Repeated ASO"
              },
              {
                "name": "# of Repeated Members"
              },
              {
                "name": "# of Repurchased ASO"
              },
              {
                "name": "# of Repurchased ASO LM"
              },
              {
                "name": "# of Repurchased ASO LY"
              },
              {
                "name": "# of Repurchased ASO MTD"
              },
              {
                "name": "# of Repurchased ASO MTD LM"
              },
              {
                "name": "# of Repurchased ASO YTD"
              },
              {
                "name": "# of Repurchased ASO YTD LY"
              },
              {
                "name": "# of Repurchased Members"
              },
              {
                "name": "# of SKU per Bill"
              },
              {
                "name": "# of SKUs"
              },
              {
                "name": "# of SKUs per ASO"
              },
              {
                "name": "# of SKUs per Member"
              },
              {
                "name": "# of SKUs per Successful Order"
              },
              {
                "name": "# of Store LM"
              },
              {
                "name": "# of Store LY"
              },
              {
                "name": "# of Stores"
              },
              {
                "name": "# of Stores MTD"
              },
              {
                "name": "# of Stores MTD LM"
              },
              {
                "name": "# of Stores YTD"
              },
              {
                "name": "# of Stores YTD LY"
              },
              {
                "name": "# of Successful Calls"
              },
              {
                "name": "# of Successful Orders"
              },
              {
                "name": "# of Unique SKUs"
              },
              {
                "name": "# of Visited Route"
              },
              {
                "name": "% Strike Rate"
              },
              {
                "name": "ASO Growth % vs LM"
              },
              {
                "name": "ASO Growth % vs LY"
              },
              {
                "name": "ASO MTD Growth % vs LM"
              },
              {
                "name": "ASO YTD Growth % vs LM"
              },
              {
                "name": "ASO/ MCP"
              },
              {
                "name": "ASO/ Route"
              },
              {
                "name": "AVG Daily Sell Out Amt"
              },
              {
                "name": "AVG Daily Sell Out Qty"
              },
              {
                "name": "AVG Sell Out per Bill"
              },
              {
                "name": "AVG Sell Out per day/ Store"
              },
              {
                "name": "AVG Sell Out per Store"
              },
              {
                "name": "DropSize"
              },
              {
                "name": "Monthly Frequency ASO"
              },
              {
                "name": "Promotion Estimated Amt"
              },
              {
                "name": "Sell Out Amt"
              },
              {
                "name": "Sell Out Amt % vs AOP"
              },
              {
                "name": "Sell Out Amt % vs AOP FY"
              },
              {
                "name": "Sell Out Amt % vs Target"
              },
              {
                "name": "Sell Out Amt Excl Voucher"
              },
              {
                "name": "Sell Out Amt Growth % vs LM"
              },
              {
                "name": "Sell Out Amt Growth % vs LY"
              },
              {
                "name": "Sell Out Amt LM"
              },
              {
                "name": "Sell Out Amt LY"
              },
              {
                "name": "Sell Out Amt MTD"
              },
              {
                "name": "Sell Out Amt MTD LM"
              },
              {
                "name": "Sell Out Amt MTD LY"
              },
              {
                "name": "Sell Out Amt Projection"
              },
              {
                "name": "Sell Out Amt Projection % vs AOP"
              },
              {
                "name": "Sell Out Amt Projection % vs Target"
              },
              {
                "name": "Sell Out Amt Remaining vs AOP"
              },
              {
                "name": "Sell Out Amt Remaining vs AOP FY"
              },
              {
                "name": "Sell Out Amt THS AOP"
              },
              {
                "name": "Sell Out Amt THS AOP FY"
              },
              {
                "name": "Sell Out Amt Voucher"
              },
              {
                "name": "Sell Out Amt YTD"
              },
              {
                "name": "Sell Out Discount Amt"
              },
              {
                "name": "Sell Out Net Amt"
              },
              {
                "name": "Sell Out Net Amt Excl Voucher"
              },
              {
                "name": "Sell Out Promotion Qty"
              },
              {
                "name": "Sell Out Qty"
              },
              {
                "name": "Sell Out Qty % vs AOP"
              },
              {
                "name": "Sell Out Qty % vs AOP FY"
              },
              {
                "name": "Sell Out Qty % vs Target"
              },
              {
                "name": "Sell Out Qty Excl Voucher"
              },
              {
                "name": "Sell Out Qty Growth % vs LM"
              },
              {
                "name": "Sell Out Qty Growth % vs LY"
              },
              {
                "name": "Sell Out Qty LM"
              },
              {
                "name": "Sell Out Qty LY"
              },
              {
                "name": "Sell Out Qty MTD"
              },
              {
                "name": "Sell Out Qty MTD LM"
              },
              {
                "name": "Sell Out Qty MTD LY"
              },
              {
                "name": "Sell Out Qty Order THS"
              },
              {
                "name": "Sell Out Qty Projection"
              },
              {
                "name": "Sell Out Qty Projection % vs AOP"
              },
              {
                "name": "Sell Out Qty Projection % vs Target"
              },
              {
                "name": "Sell Out Qty Remaining vs AOP"
              },
              {
                "name": "Sell Out Qty YTD"
              },
              {
                "name": "Sell Out THs tnh thng"
              },
              {
                "name": "Sell Out THs tnh thng LM"
              },
              {
                "name": "Sell Out THs tnh thng MTD"
              },
              {
                "name": "Sell Out THs tnh thng MTD LM"
              },
              {
                "name": "Sell Out THs tnh thng YTD"
              },
              {
                "name": "Sell Out THs tnh thng YTD LY"
              },
              {
                "name": "Sell Out True Mart Amt"
              },
              {
                "name": "Sell Out True Mart Amt LM"
              },
              {
                "name": "Sell Out True Mart Amt MTD"
              },
              {
                "name": "Sell Out True Mart Amt MTD LM"
              },
              {
                "name": "Sell Out True Mart Amt YTD"
              },
              {
                "name": "Sell Out True Mart Amt YTD LY"
              },
              {
                "name": "Sell Out True Mart Net Amt"
              },
              {
                "name": "Sell Out True Mart Qty"
              },
              {
                "name": "Store Growth % vs LM"
              },
              {
                "name": "Store Growth % vs LY"
              },
              {
                "name": "Total Promotion Amt"
              },
              {
                "name": "VPO"
              },
              {
                "name": "Max Amt Selected"
              },
              {
                "name": "Min Amt Selected"
              },
              {
                "name": "# of Visited Calls"
              },
              {
                "name": "# of Calls Plan YTD"
              },
              {
                "name": "# of Order by Amt Range"
              },
              {
                "name": "Sell Out Amt Order"
              },
              {
                "name": "# of ASO_OFF"
              },
              {
                "name": "# of ASO_ON"
              },
              {
                "name": "# of AVG Calls Plan per Day YTD"
              },
              {
                "name": "# of Daily ASO YTD"
              },
              {
                "name": "# of Distributor by Amt Range YTD"
              },
              {
                "name": "# of invoices YTD"
              },
              {
                "name": "# of New Distributor YTD"
              },
              {
                "name": "# of Order by Amt Range YTD"
              },
              {
                "name": "# of Order by Qty Range YTD"
              },
              {
                "name": "# of Orders YTD"
              },
              {
                "name": "# of SKUs per ASO YTD"
              },
              {
                "name": "# of SKUs per Successful Order YTD"
              },
              {
                "name": "# of SKUs YTD"
              },
              {
                "name": "# of Successful Order per day"
              },
              {
                "name": "# of Successful Order per day YTD"
              },
              {
                "name": "# of Successful Orders YTD"
              },
              {
                "name": "# of Unique SKUs YTD"
              },
              {
                "name": "# of Visited Calls YTD"
              },
              {
                "name": "#of repeated ASO YTD"
              },
              {
                "name": "#of Successful Calls YTD"
              },
              {
                "name": "% New ASO / ASO"
              },
              {
                "name": "% Promotion Amt / Sell out"
              },
              {
                "name": "% Promotion Amt / Sell out LM"
              },
              {
                "name": "% Promotion Amt / Sell out LY"
              },
              {
                "name": "% Strike Rate YTD"
              },
              {
                "name": "% THs Provide Standard Stock  - Chill"
              },
              {
                "name": "ASO per Route per day"
              },
              {
                "name": "Distributor KPIs View"
              },
              {
                "name": "Distributor KPIs View LM"
              },
              {
                "name": "Distributor KPIs View LY"
              },
              {
                "name": "DropSize YTD"
              },
              {
                "name": "Icon for ASO vs LM"
              },
              {
                "name": "Icon for ASO vs LY"
              },
              {
                "name": "Icon for Sell Out Amt vs LM"
              },
              {
                "name": "Icon for Sell Out Amt vs LY"
              },
              {
                "name": "Icon for Sell Out Qty vs LM"
              },
              {
                "name": "Icon for Sell Out Qty vs LY"
              },
              {
                "name": "Icon for SO vs AOP/Target"
              },
              {
                "name": "Invoices per Route per day"
              },
              {
                "name": "Monthly Frequency ASO YTD"
              },
              {
                "name": "Promotion Estimated Amt LM"
              },
              {
                "name": "Refreshed Date"
              },
              {
                "name": "Sell Out % vs AOP/Target"
              },
              {
                "name": "Sell Out Amt/Qty"
              },
              {
                "name": "Sell Out AOP/Target"
              },
              {
                "name": "Sell Out Discount Amt LM"
              },
              {
                "name": "Sell Out Order Amt/Qty"
              },
              {
                "name": "Sell out Qty 3D- Chill"
              },
              {
                "name": "Sell Out Qty Order"
              },
              {
                "name": "Sell Out Qty per Route per day"
              },
              {
                "name": "Sell Out Qty Voucher"
              },
              {
                "name": "Sell Out THs tnh thng QTY"
              },
              {
                "name": "Sell Out True Mart Net Amt % vs AOP"
              },
              {
                "name": "Sell Out True Mart Net Amt % vs Target"
              },
              {
                "name": "Sell Out True Mart Qty % vs AOP"
              },
              {
                "name": "Sell Out True Mart Qty % vs Target"
              },
              {
                "name": "Today"
              },
              {
                "name": "Total Promotion Amt LM"
              },
              {
                "name": "VPO # of Repeated ASO"
              },
              {
                "name": "VPO LM"
              },
              {
                "name": "VPO of Repurchased ASO"
              },
              {
                "name": "VPO YTD"
              },
              {
                "name": "Sell Out Gross Amt"
              },
              {
                "name": "Sell Out /Salesman/ Month"
              },
              {
                "name": "Icon for Sell Out Amt/Qty vs LM"
              },
              {
                "name": "Icon for Sell Out Amt/Qty vs LY"
              },
              {
                "name": "Sell Out Amt/Qty Growth % vs LM"
              },
              {
                "name": "Sell Out Amt/Qty Growth % vs LY"
              },
              {
                "name": "Sell Out Amt/Qty LM"
              },
              {
                "name": "Sell Out Amt/Qty LY"
              },
              {
                "name": "Sell Out Amt/Qty MTD"
              },
              {
                "name": "Sell Out Amt/Qty MTD LM"
              },
              {
                "name": "Sell Out Amt/Qty YTD"
              },
              {
                "name": "Sell Out Amt/Qty YTD LY"
              },
              {
                "name": "To Show ASO"
              },
              {
                "name": "To Show VPO"
              },
              {
                "name": "AVG Sell Out by Route"
              },
              {
                "name": "AVG Sell Out by Month"
              },
              {
                "name": "AVG Sell Out Rolling n-month"
              },
              {
                "name": "Call Plan / MCP Route"
              },
              {
                "name": "Successful Calls / Actual Route"
              },
              {
                "name": "Visited Calls / Actual Route"
              },
              {
                "name": "Sell Out Amt Growth % vs LM Rolling n-month"
              },
              {
                "name": "Sell Out Amt Rolling n-month"
              },
              {
                "name": "# Members Show Report"
              },
              {
                "name": "Bills/Days/Store"
              },
              {
                "name": "# Total Distributor"
              },
              {
                "name": "Sell Out Net Amt ASO Asset LM"
              },
              {
                "name": "Sell Out Net Amt ASO Asset"
              },
              {
                "name": "Sell Out Net Amt ASO Asset Growth % vs LM"
              },
              {
                "name": "# of ASO Asset"
              },
              {
                "name": "# of ASO Asset LM"
              },
              {
                "name": "# of ASO Asset Growth % vs LM"
              },
              {
                "name": "Sell Out Net Amt ASO Asset / Sell Out Net Amt"
              },
              {
                "name": "SKUs / ASO Asset"
              },
              {
                "name": "Sell Out Net Amt ASO Asset LM/ Sell Out Net Amt LM"
              },
              {
                "name": "# ASO Assets/# ASO"
              },
              {
                "name": "% New Stores / Stores"
              },
              {
                "name": "Icon for Stores vs LM"
              },
              {
                "name": "Icon for Stores vs LY"
              },
              {
                "name": "Product Invoices/ Total Invoices"
              },
              {
                "name": "Club Sell Out Growth % vs LM"
              },
              {
                "name": "Club ASO Active Growth % vs LM"
              },
              {
                "name": "Icon for Sell Out Amt/Qty vs YTD LM"
              },
              {
                "name": "Icon for Sell Out Amt/Qty vs YTD LY"
              },
              {
                "name": "Sell Out Amt/Qty YTD Growth % vs LM YTD"
              },
              {
                "name": "Sell Out AOP/Target YTD"
              },
              {
                "name": "# of New Stores YTD"
              },
              {
                "name": "# Store YTD Growth % vs LM YTD"
              },
              {
                "name": "% New Stores / Stores YTD"
              },
              {
                "name": "Icon for # of Stores Growth % vs YTD LM"
              },
              {
                "name": "Icon for # of Stores Growth % vs YTD LY"
              },
              {
                "name": "# of Active Members YTD"
              },
              {
                "name": "# of Stores YTD LM"
              },
              {
                "name": "AVG Sell Out per Store YTD"
              },
              {
                "name": "Bills/Days/Store YTD"
              },
              {
                "name": "SKU Per Bill YTD"
              },
              {
                "name": "AVG Invoices"
              },
              {
                "name": "AVG Sell Out Amt/Qty"
              },
              {
                "name": "Icon for SO vs AOP/Target YTD"
              },
              {
                "name": "Sell Out % vs AOP/Target YTD"
              },
              {
                "name": "Sell Out Amt MTD Growth % vs MTD LM"
              },
              {
                "name": "Sell Out Amt YTD Growth % vs YTD LY"
              },
              {
                "name": "# Store YTD Growth % vs YTD LY"
              },
              {
                "name": "Icon for Sell Out Amt/Qty vs MTD LM"
              },
              {
                "name": "Icon for Sell Out Amt/Qty vs MTD LY"
              },
              {
                "name": "Sell Out Amt/Qty MTD Growth % vs MTD LY"
              },
              {
                "name": "Sell Out AOP/Target MTD"
              },
              {
                "name": "Sell Out Amt/Qty MTD Growth % vs LM MTD"
              },
              {
                "name": "Sell Out Amt/Qty YTD Growth % vs LY YTD"
              },
              {
                "name": "Icon for SO vs AOP/Target MTD"
              },
              {
                "name": "Sell Out % vs AOP/Target MTD"
              },
              {
                "name": "# of New Stores MTD"
              },
              {
                "name": "# of Stores MTD LY"
              },
              {
                "name": "# Store MTD Growth % vs MTD LM"
              },
              {
                "name": "# Store MTD Growth % vs MTD LY"
              },
              {
                "name": "% New Stores / Stores MTD"
              },
              {
                "name": "Icon for # of Stores Growth % vs MTD LM"
              },
              {
                "name": "Icon for # of Stores Growth % vs MTD LY"
              },
              {
                "name": "# ASO MTD Growth % vs MTD LM"
              },
              {
                "name": "# ASO MTD Growth % vs MTD LY"
              },
              {
                "name": "# ASO YTD Growth % vs YTD LM"
              },
              {
                "name": "# ASO YTD Growth % vs YTD LY"
              },
              {
                "name": "# of New Distributor MTD"
              },
              {
                "name": "Icon for # of ASO Growth % vs MTD LM"
              },
              {
                "name": "Icon for # of ASO Growth % vs MTD LY"
              },
              {
                "name": "Icon for # of ASO Growth % vs YTD LM"
              },
              {
                "name": "Icon for # of ASO Growth % vs YTD LY"
              },
              {
                "name": "VPO MTD"
              },
              {
                "name": "% New ASO / ASO MTD"
              },
              {
                "name": "% New ASO / ASO YTD"
              },
              {
                "name": "# of Active Stores by AMT Range"
              },
              {
                "name": "# of Store with AVG Amt Less Than BE Point"
              },
              {
                "name": "AVG Sell Out /Store/ Month"
              }
            ]
          },
          {
            "name": "Fact - Target",
            "columns": [
              {
                "name": "DATE_WID"
              },
              {
                "name": "Distributor/STore Code"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "STORE_WID"
              },
              {
                "name": "Target Type"
              },
              {
                "name": "Target Value"
              },
              {
                "name": "UOM"
              },
              {
                "name": "Type"
              },
              {
                "name": "CHANNEL_WID"
              }
            ],
            "measures": [
              {
                "name": "Sell Out Amt Remaining vs Target"
              },
              {
                "name": "Sell Out Amt Target"
              },
              {
                "name": "Sell Out Amt Target MTD"
              },
              {
                "name": "Sell Out Amt Target MTD LM"
              },
              {
                "name": "Sell Out Amt Target YTD"
              },
              {
                "name": "Sell Out Amt Target YTD LY"
              },
              {
                "name": "Sell Out Amt YTD LY"
              },
              {
                "name": "Sell Out Qty Remaining vs Target"
              },
              {
                "name": "Sell Out Qty Target"
              },
              {
                "name": "Sell Out Qty Target MTD"
              },
              {
                "name": "Sell Out Qty Target MTD LM"
              },
              {
                "name": "Sell Out Qty Target YTD"
              },
              {
                "name": "Sell Out Qty Target YTD LY"
              }
            ]
          },
          {
            "name": "Selection Amt Qty",
            "columns": [
              {
                "name": "Abb"
              },
              {
                "name": "Value"
              }
            ]
          },
          {
            "name": "Selection AOP Target",
            "columns": [
              {
                "name": "Value"
              }
            ]
          },
          {
            "name": "Selection Members",
            "columns": [
              {
                "name": "Value"
              }
            ]
          },
          {
            "name": "Fact - Forecast",
            "columns": [
              {
                "name": "DATE_WID"
              },
              {
                "name": "Distributor Code"
              },
              {
                "name": "DISTRIBUTOR_WID"
              },
              {
                "name": "Forecat Type"
              },
              {
                "name": "Forecat Value"
              },
              {
                "name": "Product Code"
              },
              {
                "name": "PRODUCT_WID"
              },
              {
                "name": "SALES_TERRITORY_WID"
              },
              {
                "name": "STORE_WID"
              },
              {
                "name": "UOM"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "Role",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DTDAI@THMILK.VN",
            "memberId": "DTDAI@THMILK.VN#AzureAD",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "thuy.dtt@thmilk.vn",
            "memberId": "thuy.dtt@thmilk.vn#AzureAD",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "khoa.nx@thmilk.vn",
            "memberId": "khoa.nx@thmilk.vn#AzureAD",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "ndnam@thmilk.vn",
            "memberId": "ndnam@thmilk.vn#AzureAD",
            "identityProvider": "AzureAD"
          },
          {
            "memberName": "pxchien@thmilk.vn",
            "memberId": "pxchien@thmilk.vn#AzureAD",
            "identityProvider": "AzureAD"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}